Repository SkriptLang/Skript, pull requests merged in 2018-11, with the labels that each got.

#1616 Add Difficulty
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprDifficulty.java
  src/main/java/ch/njol/skript/expressions/ExprSpawn.java
  src/main/resources/lang/english.lang
Labels: enhancement, feature

#1622 Update a few dependencies
  build.gradle
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Labels: enhancement

#1521 Add tropical fish support
  src/main/java/ch/njol/skript/entity/TropicalFishData.java
  src/main/resources/lang/english.lang
Labels: enhancement

#1678 Use 1 as default volume and pitch in EffPlaySound
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
Labels: bug
