Repository SkriptLang/Skript, pull requests merged in 2018-02, with the labels that each got.

#1118 Improve command cooldowns
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/command/ScriptCommandEvent.java
  src/main/java/ch/njol/skript/effects/EffCancelCooldown.java
  src/main/java/ch/njol/skript/expressions/ExprCmdCooldownInfo.java
  src/main/java/ch/njol/skript/expressions/ExprCmdElapsedRemainingTime.java
  src/main/resources/config.sk
Labels: enhancement

#1120 Additional documentation annotations
  src/main/java/ch/njol/skript/doc/DocumentationID.java
  src/main/java/ch/njol/skript/doc/RequiredPlugins.java
  src/main/java/ch/njol/skript/events/EvtPeriodical.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
Labels: documentation, feature

#1125 Added ExprHighestSolidBlock and ExprPlayerWeather
  src/main/java/ch/njol/skript/expressions/ExprHighestSolidBlock.java
  src/main/java/ch/njol/skript/expressions/ExprPlayerWeather.java
  src/main/java/ch/njol/skript/expressions/ExprWeather.java
  src/main/java/ch/njol/skript/util/WeatherType.java
Labels: feature

#1135 Fix parser issue with plurality
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: needs testing
