Repository SkriptLang/Skript, pull requests merged in 2018-08, with the labels that each got.

#1438 Fix documentation links
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/main/java/ch/njol/skript/effects/EffVisualEffect.java
  src/main/java/ch/njol/skript/events/EvtAtTime.java
  src/main/java/ch/njol/skript/events/EvtGameMode.java
  src/main/java/ch/njol/skript/expressions/ExprAmountOfItems.java
  src/main/java/ch/njol/skript/expressions/ExprChunk.java
  src/main/java/ch/njol/skript/expressions/ExprColorOf.java
  src/main/java/ch/njol/skript/expressions/ExprCommandSender.java
  src/main/java/ch/njol/skript/expressions/ExprDamageCause.java
  src/main/java/ch/njol/skript/expressions/ExprDifference.java
  src/main/java/ch/njol/skript/expressions/ExprExperience.java
  src/main/java/ch/njol/skript/expressions/ExprInventoryAction.java
  src/main/java/ch/njol/skript/expressions/ExprLastSpawnedEntity.java
  src/main/java/ch/njol/skript/expressions/ExprLocationAt.java
  src/main/java/ch/njol/skript/expressions/ExprTeleportCause.java
  src/main/java/ch/njol/skript/expressions/ExprTimeState.java
  src/main/java/ch/njol/skript/hooks/regions/conditions/CondCanBuild.java
  src/main/java/ch/njol/skript/hooks/regions/conditions/CondRegionContains.java
  src/main/java/ch/njol/skript/hooks/regions/events/EvtRegionBorder.java
  src/main/java/ch/njol/skript/hooks/regions/expressions/ExprBlocksInRegion.java
  src/main/java/ch/njol/skript/hooks/regions/expressions/ExprMembersOfRegion.java
  src/main/java/ch/njol/skript/hooks/regions/expressions/ExprRegionsAt.java
Labels: docs-issue, enhancement

#1364 Add CondIsSlimeChunk
  src/main/java/ch/njol/skript/conditions/CondIsSlimeChunk.java
Labels: feature

#1446 Update README to use JitPack for addons
  README.md
Labels: enhancement

#1487 Fix for list permissions
  src/main/java/ch/njol/skript/expressions/ExprPermissions.java
Labels: enhancement

#1485 Add scoreboard tags support
  src/main/java/ch/njol/skript/conditions/CondHasScoreboardTag.java
  src/main/java/ch/njol/skript/expressions/ExprScoreboardTags.java
Labels: feature

#1384 '%number% times' improvements
  src/main/java/ch/njol/skript/expressions/ExprNumbers.java
  src/main/java/ch/njol/skript/expressions/ExprTimes.java
Labels: enhancement
