Repository SkriptLang/Skript, pull requests merged in 2018-10, with the labels that each got.

#1497 Add various property condition types
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
Labels: enhancement

#1490 Add Swap Hand Items and Jump (simple-)events
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#1522 1.13 Enchantments
  src/main/java/ch/njol/skript/bukkitutil/EnchantmentIds.java
  src/main/resources/lang/english.lang
Labels: enhancement

#1451 Add a warning for single ':'s in variable names
  src/main/java/ch/njol/skript/lang/Variable.java
Labels: enhancement

#1536 Add EffDoIf
  src/main/java/ch/njol/skript/effects/EffDoIf.java
Labels: feature

#1606 1.13 Particles and Potion Effects
  src/main/java/ch/njol/skript/util/VisualEffect.java
  src/main/resources/lang/english.lang
Labels: enhancement

#1604 Delete the src/excluded directory
  src/excluded/ConfigCommandHandler.java
  src/excluded/EffExec.java
  src/excluded/EffFertilize.java
  src/excluded/ExprAttackerAlt.java
  src/excluded/FeatureConfigLol.java
  src/excluded/LitPi.java
  src/excluded/ParseOptionNode.java
  src/excluded/PlayerCommand.java
  src/excluded/SkriptCopy.java
Labels: enhancement

#1463 Add connect effect
  src/main/java/ch/njol/skript/effects/EffConnect.java
  src/main/java/ch/njol/skript/util/Utils.java
Labels: feature

#1607 Add gradle task for checking for aliases
  build.gradle
Labels: enhancement

#1636 EffTitle - New title/subtitle effect
  src/main/java/ch/njol/skript/effects/EffResetTitle.java
  src/main/java/ch/njol/skript/effects/EffSendTitle.java
Labels: feature

#1643 Swim event & Condition
  src/main/java/ch/njol/skript/conditions/CondIsSwimming.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#1639 Changes to the Color util due to compatibility issues
  src/main/java/ch/njol/skript/util/Color.java
Labels: bug, enhancement

#1633 Fix nav bar occasionally jumping on the docs
  docs/css/styles.css
Labels: enhancement
