Repository SkriptLang/Skript, pull requests merged in 2019-11, with the labels that each got.

#2590 ItemData - fixes
  src/main/java/ch/njol/skript/aliases/ItemData.java
Labels: bug

#2502 Entity Invulnerability Syntax
  src/main/java/ch/njol/skript/conditions/CondIsInvulnerable.java
  src/main/java/ch/njol/skript/effects/EffInvulnerability.java
  src/test/skript/tests/misc/entity-invulnerability.sk
Labels: feature

#2501 Entity Silence Syntax
  src/main/java/ch/njol/skript/conditions/CondIsSilent.java
  src/main/java/ch/njol/skript/effects/EffSilence.java
  src/test/skript/tests/misc/entity-silence.sk
Labels: feature

#2552 ExprPlayerWeather - fix
  src/main/java/ch/njol/skript/expressions/ExprPlayerWeather.java
  src/main/java/ch/njol/skript/util/WeatherType.java
Labels: bug

#2588 SkriptError - add addon version
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement

#2504 new ExprClientViewDistance expression
  src/main/java/ch/njol/skript/expressions/ExprClientViewDistance.java
Labels: feature

#2467 Random Fish Spawning
  src/main/java/ch/njol/skript/entity/FishData.java
Labels: enhancement

#2511 ExprExplodedBlocks - new
  src/main/java/ch/njol/skript/expressions/ExprExplodedBlocks.java
Labels: feature

#2628 Apply fix for reloading scripts proposed by NickAcPT
  src/main/java/ch/njol/skript/ScriptLoader.java
Labels: bug

#2620 BoatData - fix
  src/main/java/ch/njol/skript/entity/BoatData.java
Labels: bug

#2626 VillagerData - fix
  src/main/java/ch/njol/skript/entity/VillagerData.java
  src/main/resources/lang/english.lang
Labels: bug

#2634 EffColorItems - fix
  src/main/java/ch/njol/skript/effects/EffColorItems.java
Labels: bug

#2646 EffCancelDrops - fix
  src/main/java/ch/njol/skript/effects/EffCancelDrops.java
Labels: bug
