Repository SkriptLang/Skript, pull requests merged in 2019-12, with the labels that each got.

#2644 english lang - fixes
  src/main/resources/lang/english.lang
Labels: bug

#2589 Max Durability Expression
  src/main/java/ch/njol/skript/expressions/ExprMaxDurability.java
  src/test/skript/tests/syntaxes/expressions/ExprMaxDurability.sk
Labels: feature

#2550 new EntityPickupItemEvent
  src/main/java/ch/njol/skript/events/EvtItem.java
Labels: feature

#2622 Replace Effect Updates
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/main/java/ch/njol/util/StringUtils.java
  src/test/skript/tests/syntaxes/effects/EffReplace.sk
Labels: enhancement

#2648 InventoryClickEvent Hotbar Button
  src/main/java/ch/njol/skript/expressions/ExprHotbarButton.java
Labels: enhancement

#2633 Entity Tameable - NEW
  src/main/java/ch/njol/skript/conditions/CondIsTameable.java
  src/main/java/ch/njol/skript/expressions/ExprEntityTamer.java
  src/test/skript/tests/syntaxes/expressions/ExprEntityTamer.sk
Labels: feature

#2666 Add Number of Characters Expression
  src/main/java/ch/njol/skript/expressions/ExprNumberOfCharacters.java
  src/test/skript/tests/syntaxes/expressions/ExprNumberOfCharacters.sk
Labels: feature
