Repository SkriptLang/Skript, pull requests merged in 2019-10, with the labels that each got.

#2546 Fix ExprGlowing Example
  src/main/java/ch/njol/skript/expressions/ExprGlowing.java
Labels: enhancement

#2514 Gender-Neutral Pronouns
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/events/EvtItem.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprLevelProgress.java
  src/main/java/ch/njol/skript/expressions/ExprSpeed.java
Labels: enhancement

#2433 BlockCommandSender Convertor
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/expressions/ExprCommandSender.java
Labels: enhancement

#2481 ExprAmount Recursive Size of List
  src/main/java/ch/njol/skript/expressions/ExprAmount.java
  src/test/skript/tests/regressions/1869-Recursive List Size.sk
Labels: enhancement

#2569 Configure Github actions for Gradle
  .github/workflows/gradle.yml
Labels: enhancement

#2495 Prevent Invalid Function Parameter Type from AIOOB
  src/main/java/ch/njol/skript/lang/function/Function.java
  src/test/skript/tests/regressions/2384-Invalid Function Parameter Type.sk
Labels: bug

#2498 LivingEntity AI Syntax
  src/main/java/ch/njol/skript/conditions/CondAI.java
  src/main/java/ch/njol/skript/expressions/ExprAI.java
Labels: feature

#2499 EvtRiptide and CondIsRiptiding
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/conditions/CondIsRiptiding.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#2500 Add leashed condition
  src/main/java/ch/njol/skript/conditions/CondLeashed.java
Labels: feature

#2513 Clearer Syntax for CondIsBlocking
  src/main/java/ch/njol/skript/conditions/CondIsBlocking.java
Labels: enhancement

#2522 new ExprTimePlayed
  src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
Labels: feature

#2538 new MooshroomData class
  src/main/java/ch/njol/skript/entity/MooshroomData.java
  src/main/resources/lang/english.lang
  src/test/skript/tests/regressions/2537-missing mooshroom variations in 1.14+.sk
Labels: enhancement

#2574 LlamaData - fix
  src/main/java/ch/njol/skript/entity/LlamaData.java
  src/main/resources/lang/english.lang
Labels: bug

#2515 String Case Enhancement
  src/main/java/ch/njol/skript/expressions/ExprStringCase.java
  src/test/skript/tests/syntaxes/expressions/1860-ExprStringCase.sk
Labels: enhancement

#2593 Legacy Items - fix
  src/main/resources/materials/1.10.json
  src/main/resources/materials/1.11.json
  src/main/resources/materials/1.12.json
  src/main/resources/materials/1.9.json
Labels: bug
