Repository SkriptLang/Skript, pull requests merged in 2020-08, with the labels that each got.

#3178 Cleanup Redundant Code
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptEventHandler.java
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/bukkitutil/BukkitUnsafe.java
  src/main/java/ch/njol/skript/bukkitutil/ClickEventTracker.java
  src/main/java/ch/njol/skript/bukkitutil/Workarounds.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/classes/data/DefaultChangers.java
  src/main/java/ch/njol/skript/effects/EffPlayerVisibility.java
  src/main/java/ch/njol/skript/effects/EffSendTitle.java
  src/main/java/ch/njol/skript/entity/DroppedItemData.java
  src/main/java/ch/njol/skript/entity/EndermanData.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/SheepData.java
  src/main/java/ch/njol/skript/entity/ThrownPotionData.java
  src/main/java/ch/njol/skript/events/EvtResourcePackResponse.java
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
  src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java
  src/main/java/ch/njol/skript/expressions/ExprEntities.java
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
  src/main/java/ch/njol/skript/expressions/ExprVectorYawPitch.java
  src/main/java/ch/njol/skript/util/BlockUtils.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/main/java/ch/njol/yggdrasil/Yggdrasil.java
  src/main/java/ch/njol/yggdrasil/YggdrasilOutputStream.java
Labels: enhancement

#3268 Fix/filter issue
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
Labels: bug

#3264 ExprBlockData - fix link for types (classes)
  src/main/java/ch/njol/skript/expressions/ExprBlockData.java
Labels: documentation

#3280 Fix missing delay with setting BlockData in DelayedChangeBlock
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Labels: bug

#3282 Update docs for chunk unload event
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: documentation

#3281 Fix setting item amount of slots
  src/main/java/ch/njol/skript/expressions/ExprItemAmount.java
  src/main/java/ch/njol/skript/util/slot/CursorSlot.java
  src/main/java/ch/njol/skript/util/slot/DroppedItemSlot.java
  src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
  src/main/java/ch/njol/skript/util/slot/InventorySlot.java
  src/main/java/ch/njol/skript/util/slot/ItemFrameSlot.java
  src/main/java/ch/njol/skript/util/slot/Slot.java
  src/test/skript/tests/regressions/3281-itemamount fixes.sk
Labels: bug

#3253 Updates to EntityData
  src/main/java/ch/njol/skript/bukkitutil/EntityUtils.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/test/skript/tests/regressions/3253-entitydata fixes.sk
Labels: bug, enhancement

#3284 Fix issue with item crack particle not working
  src/main/java/ch/njol/skript/util/VisualEffect.java
  src/test/skript/tests/regressions/3284-itemcrack particle.sk
Labels: bug

#3302 Update/1.16.2
  build.gradle
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/resources/lang/english.lang
Labels: enhancement

#3305 Fix/custom inventory
  src/main/java/ch/njol/skript/expressions/ExprNamed.java
  src/test/skript/tests/regressions/3305-named inventory-item.sk
Labels: bug

#3303 ExprDurability - fix for 1.12.2 and below with block's data values
  src/main/java/ch/njol/skript/expressions/ExprDurability.java
  src/test/skript/tests/regressions/3303-item durability.sk
Labels: bug

#3314 Fix chunk is loaded condition
  src/main/java/ch/njol/skript/conditions/CondIsLoaded.java
  src/test/skript/tests/regressions/3314-chunk is loaded.sk
Labels: bug

#3317 Fix/entity data super
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/resources/lang/english.lang
Labels: bug

#3330 ExprBalance - add support for offline player balances
  src/main/java/ch/njol/skript/hooks/economy/expressions/ExprBalance.java
Labels: enhancement

#3322 ExprInventoryInfo - fix viewers returning a single value
  src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
Labels: bug

#3297 Adding "indirectly redstone powered" condition
  src/main/java/ch/njol/skript/conditions/CondIsBlockRedstonePowered.java
Labels: enhancement

#3329 Fix visual effect issues
  src/main/java/ch/njol/skript/util/VisualEffect.java
  src/main/resources/lang/english.lang
Labels: bug

#3345 ExprInventoryInfo - remove "owner" to fix a clash with "entity owner"
  src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
Labels: bug

#3348 ExprNamed - fix issue with named items failing
  src/main/java/ch/njol/skript/expressions/ExprNamed.java
  src/test/skript/tests/regressions/3305-named inventory-item.sk
Labels: bug

#3354 plugin.yml - fix soft-depend -> softdepend
  src/main/resources/plugin.yml
Labels: bug
