Repository SkriptLang/Skript, pull requests merged in 2020-07, with the labels that each got.

#3088 1.16 content update
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/java/ch/njol/skript/util/VisualEffect.java
  src/main/resources/lang/english.lang
Labels: feature

#3091 Addition of functionalities about redstone
  src/main/java/ch/njol/skript/conditions/CondIsBlockRedstonePowered.java
  src/main/java/ch/njol/skript/expressions/ExprRedstoneBlockPower.java
Labels: feature

#3105 Rewrite ExprName
  src/main/java/ch/njol/skript/expressions/ExprName.java
Labels: enhancement

#3098 Add Hex Color Support
  docs/text.html
  src/main/java/ch/njol/skript/effects/EffActionBar.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/main/java/ch/njol/skript/util/chat/BungeeConverter.java
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
  src/main/java/ch/njol/skript/util/chat/MessageComponent.java
  src/main/java/ch/njol/skript/util/chat/SkriptChatCode.java
Labels: feature

#2892 ThrownPotionData - fix syntax not working
  src/main/java/ch/njol/skript/entity/ThrownPotionData.java
  src/main/resources/lang/english.lang
  src/test/skript/tests/regressions/2891-thrown potion entity data.sk
Labels: bug

#3122 Level Progress Fixes + Floating Point Safety Function
  src/main/java/ch/njol/skript/expressions/ExprLevelProgress.java
  src/main/java/ch/njol/util/Math2.java
Labels: bug

#3128 Fix #2771
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug

#2757 Enchanting Events
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprAppliedEnchantments.java
  src/main/java/ch/njol/skript/expressions/ExprClicked.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantItem.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantingExpCost.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentBonus.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentExpCosts.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentOffer.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentOfferCost.java
Labels: feature

#3131 Add Korean Language
  src/main/resources/config.sk
  src/main/resources/lang/korean.lang
Labels: feature

#3066 Add more preload functionality
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/events/bukkit/PreScriptLoadEvent.java
Labels: enhancement

#2829 Fix the infamous #1415 issue (Default Expressions)
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug

#2907 Time Since Expression
  src/main/java/ch/njol/skript/expressions/ExprTimeSince.java
  src/test/skript/tests/syntaxes/expressions/ExprTimeSince.sk
Labels: feature

#3151 Fix Issues with ExprName
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
Labels: bug

#2664 Base Attributes
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
  src/main/resources/lang/english.lang
  src/test/skript/tests/regressions/2664-attributes.sk
Labels: feature

#3179 Fix villager data for legacy versions
  src/main/java/ch/njol/skript/entity/VillagerData.java
Labels: bug

#3180 Fix/inventory issue
  src/main/java/ch/njol/skript/effects/EffOpenInventory.java
Labels: bug

#2778 Explosion Event Block Yield
  src/main/java/ch/njol/skript/expressions/ExprExplosionBlockYield.java
Labels: feature

#2779 Fiery Explosion Effect and Condition
  src/main/java/ch/njol/skript/conditions/CondIncendiary.java
  src/main/java/ch/njol/skript/effects/EffIncendiary.java
  src/test/skript/tests/syntaxes/effects/EffExplodeWithFire.sk
Labels: feature

#2782 Explosive Entity Yield Expressions
  src/main/java/ch/njol/skript/expressions/ExprExplosionYield.java
  src/main/java/ch/njol/skript/expressions/ExprExplosiveYield.java
  src/test/skript/tests/syntaxes/expressions/ExprExplosiveYield.sk
Labels: feature

#2837 Add Persistent Data Expression and Condition
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/conditions/CondHasPersistentData.java
  src/main/java/ch/njol/skript/expressions/ExprPersistentData.java
  src/main/java/ch/njol/skript/util/ListVariablePersistentDataType.java
  src/main/java/ch/njol/skript/util/PersistentDataUtils.java
  src/main/java/ch/njol/skript/util/SingleVariablePersistentDataType.java
  src/main/resources/lang/english.lang
  src/test/skript/tests/syntaxes/expressions/ExprPersistentData.sk
Labels: feature

#2974 Gamerule Expression
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/expressions/ExprGameRule.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/main/java/ch/njol/skript/util/GameruleValue.java
Labels: feature

#2832 Update some documents
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/suggestion.md
  .github/contributing.md
  .github/issue_template/bug-report.md
  .github/issue_template/suggestion.md
  .github/pull_request_template.md
  DEVELOPMENT_MODEL.md
  README.md
  branches.md
  code-conventions.md
  security.md
  skript-worldguard6/.gitignore
Labels: documentation

#3166 Created Heal-Reason
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprHealReason.java
  src/main/resources/lang/english.lang
Labels: feature

#3172 Added ProjectileCollideEvent and entity and projectile event values
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#3201 Fix README.md Broken Links
  README.md
Labels: bug

#3195 Better StackOverflowError Handling
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement

#3232 Update testing environment for 1.16.1
  build.gradle
  src/test/skript/environments/extra/paper-1.14.4.json
  src/test/skript/environments/main/paper-1.16.1.json
  src/test/skript/tests/regressions/2535-foxdata fixes.sk
  src/test/skript/tests/regressions/2537-missing mooshroom variations in 1.14+.sk
  src/test/skript/tests/regressions/2625-villager comparisons.sk
  src/test/skript/tests/syntaxes/effects/EffExplodeCreeper.sk
  src/test/skript/tests/syntaxes/expressions/ExprCustomModelData.sk
Labels: enhancement

#3199 Introducing BlockData to Skript
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/DefaultChangers.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/expressions/ExprBlockData.java
  src/main/java/ch/njol/skript/util/BlockUtils.java
  src/main/resources/lang/english.lang
  src/test/skript/tests/syntaxes/expressions/ExprBlockData.sk
Labels: feature

#3250 Add missing lang file entries
  src/main/resources/lang/english.lang
Labels: enhancement
