Repository SkriptLang/Skript, pull requests merged in 2020-03, with the labels that each got.

#2834 Fix some item comparison issues
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
Labels: bug

#2841 Update docs to Skript 2.5-alpha2
  classes.html
  conditions.html
  docs.json
  effects.html
  events.html
  expressions.html
  functions.html
  index.html
  text.html
Labels: documentation

#2851 Fix an issue with actions failing on some PRs
  .github/workflows/gradle.yml
Labels: bug

#2836 Fix damaging items
  src/main/java/ch/njol/skript/effects/EffHealth.java
Labels: bug

#2846 Fix skriptTest and similar tasks not working on Windows
  build.gradle
Labels: bug

#2835 Fix function reloading
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/effects/EffScriptFile.java
Labels: bug

#2784 Explode Creeper Effect and Ignition Condition
  src/main/java/ch/njol/skript/conditions/CondIgnitionProcess.java
  src/main/java/ch/njol/skript/effects/EffExplodeCreeper.java
  src/test/skript/tests/syntaxes/effects/EffExplodeCreeper.sk
Labels: feature
