Repository SkriptLang/Skript, pull requests merged in 2020-09, with the labels that each got.

#3365 InventorySlot - fix issue with event-slot throwing error when clicking outside of an inventory
  src/main/java/ch/njol/skript/util/slot/InventorySlot.java
Labels: bug

#3400 Fix/zombiefied name
  src/main/resources/lang/english.lang
Labels: 2.5, bug

#3401 Fix/enchant exp cost example
  src/main/java/ch/njol/skript/expressions/ExprEnchantingExpCost.java
Labels: 2.5, bug

#3381 Updated docs description on ExprFilter
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
Labels: 2.5, documentation

#3362 Add CondIsOccluding
  src/main/java/ch/njol/skript/conditions/CondIsOccluding.java
Labels: 2.5, feature

#3206 Expr pierce level
  src/main/java/ch/njol/skript/expressions/ExprArrowPierceLevel.java
Labels: 2.5, feature

#3204 Create ExprArrowCriticalState.java
  src/main/java/ch/njol/skript/expressions/ExprProjectileCriticalState.java
Labels: 2.5, feature

#3205 Added ExprArrowKnockbackStrength
  src/main/java/ch/njol/skript/expressions/ExprArrowKnockbackStrength.java
Labels: 2.5, feature

#3402 Fix more VisualEffect bugs
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/util/ColorRGB.java
  src/main/java/ch/njol/skript/util/VisualEffect.java
Labels: 2.5, bug

#3208 Create ExprProjectileBounceState.java
  src/main/java/ch/njol/skript/conditions/CondProjectileCanBounce.java
  src/main/java/ch/njol/skript/expressions/ExprProjectileBounceState.java
Labels: 2.5, feature

#3320 ExprBlocks - update patterns to include locations, cuboid and chunks
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
Labels: 2.5, enhancement
