Repository SkriptLang/Skript, pull requests merged in 2020-11, with the labels that each got.

#3495 ExprNumbers bugfixes and decimal iterator revamp
  src/main/java/ch/njol/skript/expressions/ExprNumbers.java
Labels: 2.5, bug

#3533 Fix/ItemType#toString issue
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Labels: 2.5, bug

#3501 EffEquip - add support for steerable (ie: striders)
  src/main/java/ch/njol/skript/effects/EffEquip.java
Labels: 2.5, enhancement

#3497 VisualEffect - add even more missing particles
  src/main/java/ch/njol/skript/util/VisualEffect.java
  src/main/resources/lang/english.lang
Labels: 2.5, enhancement

#3173 Added regex support to the `split` expression
  src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
Labels: 2.5, enhancement

#3223 Added ExprWhitelist and CondServerIsWhitelisted
  src/main/java/ch/njol/skript/conditions/CondIsWhitelisted.java
  src/main/java/ch/njol/skript/expressions/ExprWhitelist.java
Labels: 2.5, feature

#3534 Skript - prevent loading when not running at least Minecraft 1.9
  src/main/java/ch/njol/skript/Skript.java
Labels: 2.5, enhancement

#3538 Added CondIsInteractable
  src/main/java/ch/njol/skript/conditions/CondIsInteractable.java
Labels: 2.5, enhancement

#3174 Created CondMatches.java
  src/main/java/ch/njol/skript/conditions/CondMatches.java
  src/test/skript/tests/syntaxes/conditions/CondMatches.sk
Labels: 2.5, feature

#3537 Add character at to ExprSubstring
  src/main/java/ch/njol/skript/expressions/ExprSubstring.java
Labels: 2.5, enhancement

#3547 Feature/falling block land event
  src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java
Labels: 2.5, enhancement

#3512 Adding Direction event value to the projectile hit event
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: 2.5, enhancement

#3549 Fix changers of ExprEnchantmentLevel
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentLevel.java
Labels: 2.5, bug

#3530 Fix slow variable saving
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: 2.5, enhancement

#3514 ExprBookAuthor/Title - fix the ItemType issue
  src/main/java/ch/njol/skript/expressions/ExprBookAuthor.java
  src/main/java/ch/njol/skript/expressions/ExprBookTitle.java
Labels: 2.5, bug

#3556 ExprGameMode - fix issue with past gamemode not working
  src/main/java/ch/njol/skript/expressions/ExprGameMode.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
Labels: 2.5, bug

#3510 Feature - Potion Effects
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/main/java/ch/njol/skript/expressions/ExprPotionEffect.java
  src/main/java/ch/njol/skript/expressions/ExprPotionEffects.java
  src/main/java/ch/njol/skript/expressions/ExprTypeOf.java
  src/main/java/ch/njol/skript/util/PotionDataUtils.java
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
  src/main/resources/lang/english.lang
  src/test/skript/tests/syntaxes/expressions/ExprPotionEffects.sk
Labels: 2.5, enhancement

#3558 Improve public syntax information API
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/lang/ExpressionInfo.java
  src/main/java/ch/njol/skript/lang/SyntaxElementInfo.java
  src/main/java/ch/njol/skript/lang/function/Parameter.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: 2.5, enhancement

#3559 ExprBlockData - add support to set blockdata of blocks
  src/main/java/ch/njol/skript/expressions/ExprBlockData.java
Labels: 2.5, enhancement

#3478 Make EffTeleport do teleports asynchronously on Paper
  build.gradle
  src/main/java/ch/njol/skript/effects/EffTeleport.java
Labels: 2.5, enhancement

#3577 EffMessage - add support for optional sender
  src/main/java/ch/njol/skript/effects/EffMessage.java
Labels: 2.5, enhancement

#3479 Fix AsyncEffect not being executed when last in trigger
  src/main/java/ch/njol/skript/util/AsyncEffect.java
Labels: 2.5, bug
