Repository SkriptLang/Skript, pull requests merged in 2020-06, with the labels that each got.

#2654 Add Scripts Expression
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/expressions/ExprScripts.java
Labels: feature

#2984 InfoCommand - add server version, skript version and installed addons
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/resources/lang/english.lang
Labels: enhancement

#3059 ExprFinalDamage - Fix returning getDamage instead of getFinalDamage
  src/main/java/ch/njol/skript/expressions/ExprFinalDamage.java
Labels: bug

#2969 Fix default block data applying to all placed blocks
  src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
Labels: bug
