Repository SkriptLang/Skript, pull requests merged in 2020-02, with the labels that each got.

#2766 Fix EffReplace
  src/main/java/ch/njol/skript/effects/EffReplace.java
Labels: bug

#2761 HealthUtils - Fix entity damage effect
  src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java
  src/test/skript/tests/syntaxes/effects/EffHealth.sk
Labels: bug

#2748 Arrows Stuck
  src/main/java/ch/njol/skript/expressions/ExprArrowsStuck.java
  src/test/skript/tests/syntaxes/expressions/ExprArrowsStuck.sk
Labels: feature

#2759 EffEquip - Add llama to entity equip effect
  src/main/java/ch/njol/skript/effects/EffEquip.java
Labels: enhancement

#2772 No Damage Ticks Expression
  src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java
  src/test/skript/tests/syntaxes/expressions/ExprNoDamageTicks.sk
Labels: feature

#2783 Explosion Effect Updates
  src/main/java/ch/njol/skript/effects/EffExplosion.java
Labels: feature

#2621 Apply potion effects without adding onto current duration
  src/main/java/ch/njol/skript/effects/EffPotion.java
Labels: enhancement

#2660 ExprEntities - add chunks
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/expressions/ExprEntities.java
  src/test/skript/tests/syntaxes/expressions/ExprEntities.sk
Labels: feature

#2775 Creeper Max Fuse Ticks Expression
  src/main/java/ch/njol/skript/expressions/ExprCreeperMaxFuseTicks.java
Labels: feature

#2824 Update Minecraft's versions that Skript supports in the README
  README.md
Labels: enhancement

#2828 Fix #2580
  src/main/java/ch/njol/skript/effects/EffTree.java
  src/main/resources/lang/english.lang
Labels: bug

#2505 Add newline literal
  src/main/java/ch/njol/skript/expressions/ExprLore.java
  src/main/java/ch/njol/skript/expressions/LitNewLine.java
Labels: feature

#2560 Add info command
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/resources/lang/english.lang
  src/main/resources/lang/german.lang
Labels: enhancement

#2811 Fix EvtExperienceSpawn firing more than once
  src/main/java/ch/njol/skript/events/EvtExperienceSpawn.java
Labels: bug

#2813 Fix drop item effect throwing error
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/effects/EffDrop.java
Labels: bug

#2785 Charge Creeper Effect and Condition
  src/main/java/ch/njol/skript/conditions/CondIsCharged.java
  src/main/java/ch/njol/skript/effects/EffChargeCreeper.java
  src/test/skript/tests/syntaxes/effects/EffChargeCreeper.sk
Labels: feature
