Repository SkriptLang/Skript, pull requests merged in 2021-10, with the labels that each got.

#4316 🛠️ Fix `drop 0 of item`
  src/main/java/ch/njol/skript/effects/EffDrop.java
Labels: bug

#4275 Do regex check before number parsing attempt
  src/main/java/ch/njol/skript/classes/Parser.java
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
  src/main/java/ch/njol/skript/hooks/economy/classes/Money.java
  src/main/java/ch/njol/skript/util/Timespan.java
Labels: enhancement

#4274 Update authors list
  src/main/resources/plugin.yml
Labels: enhancement

#4255 Spawn effect section
  src/main/java/ch/njol/skript/effects/EffDrop.java
  src/main/java/ch/njol/skript/effects/EffSpawn.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/events/EvtDamage.java
  src/main/java/ch/njol/skript/events/EvtItem.java
  src/main/java/ch/njol/skript/expressions/ExprLastSpawnedEntity.java
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: enhancement, feature

#4217 Add world of chunk support
  src/main/java/ch/njol/skript/expressions/ExprWorld.java
Labels: enhancement

#4282 Fix loop-value-1-1 parsing
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: bug

#4176 Pattern compiling
  src/main/java/ch/njol/skript/expressions/ExprSpeed.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/patterns/ChoicePatternElement.java
  src/main/java/ch/njol/skript/patterns/GroupPatternElement.java
  src/main/java/ch/njol/skript/patterns/LiteralPatternElement.java
  src/main/java/ch/njol/skript/patterns/MalformedPatternException.java
  src/main/java/ch/njol/skript/patterns/MatchResult.java
  src/main/java/ch/njol/skript/patterns/OptionalPatternElement.java
  src/main/java/ch/njol/skript/patterns/ParseTagPatternElement.java
  src/main/java/ch/njol/skript/patterns/PatternCompiler.java
  src/main/java/ch/njol/skript/patterns/PatternElement.java
  src/main/java/ch/njol/skript/patterns/RegexPatternElement.java
  src/main/java/ch/njol/skript/patterns/SkriptPattern.java
  src/main/java/ch/njol/skript/patterns/TypePatternElement.java
  src/main/java/ch/njol/skript/patterns/package-info.java
  src/main/resources/lang/english.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/korean.lang
Labels: enhancement

#3979 Remove variable conflict warnings
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/classes/Parser.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/effects/EffSuppressWarnings.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/EntityType.java
  src/main/java/ch/njol/skript/hooks/economy/classes/Money.java
  src/main/java/ch/njol/skript/hooks/regions/classes/Region.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/resources/config.sk
  src/test/skript/tests/regressions/2381-multiplication in list index.sk
  src/test/skript/tests/syntaxes/effects/EffReplace.sk
Labels: enhancement, 2.6

#3867 Update ExprParse.java
  src/main/java/ch/njol/skript/expressions/ExprParse.java
Labels: enhancement

#3801 Event value selection improvements
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug

#4162 More Item Comparison Improvements
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/conditions/CondContains.java
  src/main/java/ch/njol/skript/conditions/CondItemInHand.java
  src/main/java/ch/njol/skript/expressions/ExprAmountOfItems.java
  src/main/java/ch/njol/skript/registrations/Comparators.java
Labels: bug

#4172 Add get modified entity's attribute value
  src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
Labels: enhancement

#3761 Add victim support for the projectile hit event
  src/main/java/ch/njol/skript/expressions/ExprAttacked.java
Labels: enhancement

#3999 Update localization system
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/localization/Adjective.java
  src/main/java/ch/njol/skript/localization/ArgsMessage.java
  src/main/java/ch/njol/skript/localization/FormattedMessage.java
  src/main/java/ch/njol/skript/localization/GeneralWords.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/main/java/ch/njol/skript/localization/LanguageChangeListener.java
  src/main/java/ch/njol/skript/localization/Message.java
  src/main/java/ch/njol/skript/localization/Noun.java
  src/main/java/ch/njol/skript/localization/PluralizingArgsMessage.java
  src/main/java/ch/njol/skript/localization/RegexMessage.java
  src/main/java/ch/njol/skript/util/visual/VisualEffectType.java
  src/main/resources/lang/default.lang
  src/main/resources/lang/english.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/korean.lang
Labels: enhancement, 2.6

#4302 Add Inventory-InventoryType comparator
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Labels: feature

#4383 AABB - allow lower world height
  src/main/java/ch/njol/skript/bukkitutil/WorldUtils.java
  src/main/java/ch/njol/skript/util/AABB.java
Labels: bug, enhancement
