Repository SkriptLang/Skript, pull requests merged in 2021-04, with the labels that each got.

#3897 Add automatic module name
  build.gradle
Labels: 2.6, enhancement

#3914 Delete IDE configuration files
  .classpath
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/file.template.settings.xml
  .idea/fileTemplates/Effect.java
  .idea/fileTemplates/Expression.java
  .idea/fileTemplates/includes/License Header.java
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .project
  .settings/gradle/org.springsource.ide.eclipse.gradle.core.import.prefs
  .settings/gradle/org.springsource.ide.eclipse.gradle.core.prefs
  .settings/gradle/org.springsource.ide.eclipse.gradle.refresh.prefs
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  .settings/org.eclipse.ltk.core.refactoring.prefs
  .settings/org.eclipse.m2e.core.prefs
  .settings/org.eclipse.wst.validation.prefs
Labels: 2.5, enhancement

#3921 Fix world difficulty not spawning monsters
  src/main/java/ch/njol/skript/expressions/ExprDifficulty.java
Labels: 2.5, bug

#3234 Added a way to get the list of all commands or a specific command's info
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/expressions/ExprAllCommands.java
  src/main/java/ch/njol/skript/expressions/ExprCommandInfo.java
Labels: 2.5, feature

#3930 Fix default value, filter input, metadata, relational variable, ternary incorrectly converting
  src/main/java/ch/njol/skript/expressions/ExprDefaultValue.java
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
  src/main/java/ch/njol/skript/expressions/ExprMetadata.java
  src/main/java/ch/njol/skript/expressions/ExprRelationalVariable.java
  src/main/java/ch/njol/skript/expressions/ExprTernary.java
Labels: 2.5, bug

#3931 Add test_runners to .gitignore
  .gitignore
Labels: 2.5, enhancement
