Repository SkriptLang/Skript, pull requests merged in 2021-07, with the labels that each got.

#4144 Fix doubly nested variable parsing
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/regressions/4143-nested-variables-erroring-in-2.6-beta1.sk
Labels: bug

#4145 Fix JitPack publishing (maven)
  build.gradle
  jitpack.yml
Labels: enhancement

#4120 Improve Issue Templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/suggestion.md
  .github/ISSUE_TEMPLATE/suggestion.yml
Labels: enhancement

#4161 Improve unimplemented parse method error
  src/main/java/ch/njol/skript/classes/Parser.java
Labels: enhancement

#4170 Update code conventions to require Java 16 for compiling
  code-conventions.md
Labels: enhancement

#4175 Fix conditionals with inline conditions or exit section effects
  src/main/java/ch/njol/skript/sections/SecConditional.java
  src/test/skript/tests/syntaxes/sections/SecConditional.sk
Labels: bug

#4136 Add last color expression
  src/main/java/ch/njol/skript/expressions/ExprLastColor.java
Labels: feature

#4182 ExprName - add support to get/set names of blocks
  src/main/java/ch/njol/skript/expressions/ExprName.java
Labels: enhancement

#4204 Add magma to itemtype damage cause comparator
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Labels: bug

#4213 Fix combined conditional running on non-first runs
  src/main/java/ch/njol/skript/sections/SecConditional.java
Labels: bug
