Repository SkriptLang/Skript, pull requests merged in 2021-11, with the labels that each got.

#4399 Fix effect commands variable NPE on master branch
  src/main/java/ch/njol/skript/lang/Variable.java
  src/test/skript/tests/regressions/4143-nested-variables-erroring-in-2.6-beta1.sk
Labels: bug

#4400 Fix CSV storage not using the right temporary file
  src/main/java/ch/njol/skript/variables/FlatFileStorage.java
Labels: bug

#4401 Update korean.lang
  src/main/resources/lang/korean.lang
Labels: enhancement

#4394 Fix cancelling command cooldown after a delay
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/command/ScriptCommandEvent.java
Labels: bug

#4389 Remove ExprTargetedBlock cache
  src/main/java/ch/njol/skript/expressions/ExprTargetedBlock.java
Labels: enhancement

#4388 Allow past form of damage cause expression
  src/main/java/ch/njol/skript/expressions/ExprDamageCause.java
Labels: enhancement

#4387 Fix EffConnect NPE with no players
  src/main/java/ch/njol/skript/effects/EffConnect.java
  src/main/java/ch/njol/skript/util/Utils.java
Labels: bug

#4371 Remove 'Numeric ids are not supported anymore' error
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
Labels: enhancement

#3922 Implement sorting by value in ExprIndices
  src/main/java/ch/njol/skript/expressions/ExprIndices.java
  src/main/java/ch/njol/skript/expressions/ExprSlotIndex.java
  src/test/skript/tests/syntaxes/expressions/ExprIndices.sk
Labels: feature, 2.6

#4208 Add ExprMiddleOfLocation
  src/main/java/ch/njol/skript/expressions/ExprMiddleOfLocation.java
Labels: feature

#4286 🚀 Improve `/skript info`
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/main/resources/lang/english.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/korean.lang
Labels: enhancement

#4363 🚀 Add `has potion` condition
  src/main/java/ch/njol/skript/bukkitutil/EntityUtils.java
  src/main/java/ch/njol/skript/conditions/CondHasPotion.java
  src/main/java/ch/njol/skript/expressions/ExprSpawnerType.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/util/Utils.java
Labels: enhancement, feature

#4414 Fix looping single values
  src/main/java/ch/njol/skript/sections/SecLoop.java
Labels: bug

#3916 Add /skript command tab completer
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
Labels: feature, 2.6

#4412 🚀 Extend timespan (week/month/year)
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/util/Timespan.java
  src/main/resources/lang/default.lang
Labels: enhancement

#4184 Entity is in Rain/Lava/Water/BubbleColumn
  src/main/java/ch/njol/skript/conditions/CondEntityIsInLiquid.java
  src/main/java/ch/njol/skript/conditions/CondEntityIsWet.java
Labels: enhancement

#3920 Add hostname expression
  src/main/java/ch/njol/skript/expressions/ExprHostname.java
Labels: feature, 2.6

#4413 🚀 Add `world with name` expression
  src/main/java/ch/njol/skript/expressions/ExprWorldFromName.java
Labels: enhancement

#4417 Fix Gradle building
  .github/workflows/gradle.yml
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Labels: bug

#4397 Make Variable toString always include variable name
  src/main/java/ch/njol/skript/lang/Variable.java
Labels: enhancement

#4432 🛠 Fix timespan from date expr
  src/main/java/ch/njol/skript/expressions/ExprDateAgoLater.java
Labels: bug
