Repository SkriptLang/Skript, pull requests merged in 2021-08, with the labels that each got.

#4214 Fix WorldGuard 6 module not building to right Java version
  skript-worldguard6/build.gradle
Labels: bug

#4236 Fix broken link in README
  README.md
Labels: enhancement

#4193 Fix incorrect ending dash with ExprRawName
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
Labels: bug

#4147 Section API Improvements
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/effects/Delay.java
  src/main/java/ch/njol/skript/lang/EffectSection.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/SectionSkriptEvent.java
  src/main/java/ch/njol/skript/lang/TriggerSection.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: feature

#3813 Fix false positive 32-bit warning
  src/main/java/ch/njol/skript/Skript.java
Labels: bug

#4095 Fix number/integer stuff
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/expressions/ExprAmount.java
  src/main/java/ch/njol/skript/expressions/ExprAmountOfItems.java
  src/main/java/ch/njol/skript/expressions/ExprArrowKnockbackStrength.java
  src/main/java/ch/njol/skript/expressions/ExprArrowPierceLevel.java
  src/main/java/ch/njol/skript/expressions/ExprArrowsStuck.java
  src/main/java/ch/njol/skript/expressions/ExprClientViewDistance.java
  src/main/java/ch/njol/skript/expressions/ExprCreeperMaxFuseTicks.java
  src/main/java/ch/njol/skript/expressions/ExprDurability.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantingExpCost.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentBonus.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentExpCosts.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentLevel.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentOfferCost.java
  src/main/java/ch/njol/skript/expressions/ExprHotbarButton.java
  src/main/java/ch/njol/skript/expressions/ExprIdOf.java
  src/main/java/ch/njol/skript/expressions/ExprIndexOf.java
  src/main/java/ch/njol/skript/expressions/ExprItemAmount.java
  src/main/java/ch/njol/skript/expressions/ExprLength.java
  src/main/java/ch/njol/skript/expressions/ExprLevel.java
  src/main/java/ch/njol/skript/expressions/ExprMaxDurability.java
  src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
  src/main/java/ch/njol/skript/expressions/ExprMaxStack.java
  src/main/java/ch/njol/skript/expressions/ExprMendingRepairAmount.java
  src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java
  src/main/java/ch/njol/skript/expressions/ExprNumberOfCharacters.java
  src/main/java/ch/njol/skript/expressions/ExprOnlinePlayersCount.java
  src/main/java/ch/njol/skript/expressions/ExprPing.java
  src/main/java/ch/njol/skript/expressions/ExprPlayerViewDistance.java
  src/main/java/ch/njol/skript/expressions/ExprProtocolVersion.java
  src/main/java/ch/njol/skript/expressions/ExprRedstoneBlockPower.java
  src/main/java/ch/njol/skript/expressions/ExprRound.java
  src/main/java/ch/njol/skript/expressions/ExprSeaLevel.java
  src/main/java/ch/njol/skript/expressions/ExprSlotIndex.java
  src/main/java/ch/njol/skript/expressions/ExprTimes.java
Labels: bug

#4256 Fix entity rabbit comparison
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Labels: bug

#4135 Ignore hidden files & folders
  src/main/java/ch/njol/skript/ScriptLoader.java
Labels: bug

#4257 Make EffectSections available in effect commands and more
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/expressions/ExprArgument.java
  src/main/java/ch/njol/skript/lang/Effect.java
  src/main/java/ch/njol/skript/lang/EffectSectionEffect.java
  src/main/java/ch/njol/skript/lang/Statement.java
Labels: bug

#4258 Fix cannot get data class of modern material exception
  src/main/java/ch/njol/skript/util/Direction.java
Labels: bug

#4259 Fix CCE due to console literal
  src/main/java/ch/njol/skript/expressions/LitConsole.java
Labels: bug

#4262 Suppress bed colour setting exception on newer server versions
  src/main/java/ch/njol/skript/expressions/ExprColorOf.java
Labels: bug

#4264 Offline player stuff
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprArrowKnockbackStrength.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
Labels: bug, enhancement

#4267 Fix command permission and cooldown message quote parsing
  src/main/java/ch/njol/skript/command/Commands.java
Labels: bug

#4265 Make return type of ExprMe player
  src/main/java/ch/njol/skript/expressions/ExprMe.java
Labels: bug

#4271 Fix lenient link parsing
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
Labels: bug

#4273 More CondContains fixes
  src/main/java/ch/njol/skript/conditions/CondContains.java
  src/test/skript/tests/syntaxes/conditions/CondContains.sk
Labels: bug

#4277 Fix chat color stuff with expressions
  src/main/java/ch/njol/skript/effects/EffMessage.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
  src/main/java/ch/njol/skript/util/chat/MessageComponent.java
Labels: bug

#3935 Restyle Docs Site
  docs/assets/Logo/Skript Logo Circle 2.png
  docs/assets/Logo/Skript Logo Circle.png
  docs/assets/Logo/Skript Logo Trans.png
  docs/assets/Logo/Skript Logo.png
  docs/assets/icon.png
  docs/css/highlightjs.min.css
  docs/css/styles.css
  docs/functions.html
  docs/index.html
  docs/js/highlight.js
  docs/js/highlight.js.LICENSE
  docs/js/main.js
  docs/template.html
  docs/templates/desc_full.html
  docs/templates/navbar.html
  docs/text.html
  docs/tutorials.html
  src/main/java/ch/njol/skript/classes/ClassInfo.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/conditions/CondCanSee.java
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/effects/EffCancelCooldown.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/events/EvtChat.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprAmount.java
  src/main/java/ch/njol/skript/expressions/ExprChatFormat.java
  src/main/java/ch/njol/skript/expressions/ExprHash.java
  src/main/java/ch/njol/skript/expressions/ExprHiddenPlayers.java
  src/main/java/ch/njol/skript/expressions/ExprHoverList.java
  src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java
  src/main/java/ch/njol/skript/expressions/ExprLore.java
  src/main/java/ch/njol/skript/expressions/ExprMessage.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/main/java/ch/njol/skript/expressions/ExprNamed.java
  src/main/java/ch/njol/skript/expressions/ExprNumberOfCharacters.java
  src/main/java/ch/njol/skript/expressions/ExprParseError.java
  src/main/java/ch/njol/skript/expressions/ExprProtocolVersion.java
  src/main/java/ch/njol/skript/expressions/ExprTargetedBlock.java
  src/main/java/ch/njol/skript/expressions/ExprVersionString.java
  src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
  src/main/java/ch/njol/skript/hooks/permission/expressions/ExprAllGroups.java
  src/main/java/ch/njol/skript/hooks/regions/conditions/CondCanBuild.java
  src/main/java/ch/njol/skript/hooks/regions/expressions/ExprRegionsAt.java
Labels: enhancement, documentation, 2.6

#4261 Fix ExprXOf CCE
  src/main/java/ch/njol/skript/expressions/ExprXOf.java
Labels: bug

#4298 Fix ExprXOf converting
  src/main/java/ch/njol/skript/expressions/ExprXOf.java
  src/test/skript/tests/syntaxes/expressions/ExprXOf.sk
Labels: bug

#4290 Fix dropping in cancelled death event
  src/main/java/ch/njol/skript/effects/EffDrop.java
Labels: bug

#4291 Improve Experience Event
  src/main/java/ch/njol/skript/events/EvtExperienceSpawn.java
  src/main/java/ch/njol/skript/events/bukkit/ExperienceSpawnEvent.java
Labels: bug

#4280 Fix block direction getting
  src/main/java/ch/njol/skript/util/BlockUtils.java
Labels: bug

#4270 EvtMoveOn bug fixes
  src/main/java/ch/njol/skript/events/EvtMoveOn.java
Labels: bug

#4268 ExprElement converted expression
  src/main/java/ch/njol/skript/expressions/ExprElement.java
  src/main/java/ch/njol/util/StringUtils.java
Labels: bug

#4238 Fix location function without world arg
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
Labels: bug

#4310 Update Docs Website
  .DS_Store
  assets/icon.png
  classes.html
  conditions.html
  css/highlightjs.min.css
  css/styles.css
  docs.json
  effects.html
  events.html
  expressions.html
  functions.html
  index.html
  js/highlight.js
  js/highlight.js.LICENSE
  js/main.js
  old/classes.html
  old/conditions.html
  old/css/styles.css
  old/docs.json
  old/effects.html
  old/events.html
  old/expressions.html
  old/functions.html
  old/index.html
  old/text.html
  text.html
  tutorials.html
Labels: enhancement
