Repository SkriptLang/Skript, pull requests merged in 2022-08, with the labels that each got.

#5003 Add flavour to Skript info command
  src/main/java/ch/njol/skript/SkriptCommand.java
Labels: enhancement

#5009 Implement missing methods for Block implementations
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Labels: enhancement

#5011 Fix Actions not running on master branch
  .github/workflows/java-17-builds.yml
  .github/workflows/java-8-builds.yml
Labels: bug, unit testing

#4854 ⚒️ Enhance and Fix ExprAge
  src/main/java/ch/njol/skript/expressions/ExprAge.java
  src/main/java/ch/njol/skript/expressions/ExprBlockAge.java
Labels: bug, enhancement, 2.7

#4986 Fix ExprFunctionCall conversion
  src/main/java/ch/njol/skript/expressions/ExprVelocity.java
  src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java
  src/test/skript/tests/regressions/4524-function call conversion.sk
Labels: bug, 2.6, functions

#4972 🛠 Fix PrepareCraft event NPE
  src/main/java/ch/njol/skript/events/EvtItem.java
Labels: bug, 2.7, 2.6

#4632 Add potion effect tier
  src/main/java/ch/njol/skript/expressions/ExprPotionEffectTier.java
Labels: feature

#5039 Add providing plugin to pattern compilation exception
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: enhancement

#5044 Add testing community section to README
  README.md
Labels: feature

#4970 Egg API !
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/conditions/CondWillHatch.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/EffMakeEggHatch.java
  src/main/java/ch/njol/skript/expressions/ExprEgg.java
  src/main/java/ch/njol/skript/expressions/ExprHatchingNumber.java
  src/main/java/ch/njol/skript/expressions/ExprHatchingType.java
Labels: feature, 2.7
