Repository SkriptLang/Skript, pull requests merged in 2022-03, with the labels that each got.

#4511 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/suggestion.yml
Labels: enhancement

#4242 Allow normal object literal parsing when unparsed literals not allowed
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: bug

#4244 Fix function default value parsing and AIOOB
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/Parameter.java
  src/main/java/ch/njol/skript/lang/function/Signature.java
Labels: bug, enhancement

#4260 Fix 'all armor stands' expression not working
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/log/ParseLogHandler.java
Labels: bug

#4393 Fix ExprEnchantmentLevel changing
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentLevel.java
Labels: bug

#4395 Make ExprFilter not accept single expressions
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
Labels: enhancement

#4390 Fix DelayedChangeBlock comparison
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/BlockUtils.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Labels: bug

#4405 Fix ExprTypeOf return type
  src/main/java/ch/njol/skript/expressions/ExprTypeOf.java
Labels: bug

#4396 Add config option for player name regex
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/resources/config.sk
Labels: enhancement

#4408 Fix VariableString converting
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/VariableString.java
Labels: enhancement

#4647 ⚒️ Fix blocks between with minus Y
  src/main/java/ch/njol/skript/util/BlockLineIterator.java
Labels: bug
