Repository SkriptLang/Skript, pull requests merged in 2022-07, with the labels that each got.

#4362 Fix problems with EffSendTitle
  src/main/java/ch/njol/skript/effects/EffSendTitle.java
Labels: bug

#4857 Temporarily change composter particle pattern
  src/main/resources/lang/default.lang
Labels: bug, breaking changes, 2.6

#4796 Changed argumentPattern regex in Commands class.
  src/main/java/ch/njol/skript/command/Commands.java
Labels: bug

#4409 🚀 Add missing event values in crafting events + fix `PrepareItemCraftEvent`
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtItem.java
Labels: bug, enhancement

#4879 Add 1.19 spawn reasons to default.lang
  src/main/resources/lang/default.lang
Labels: enhancement, 2.6

#3802 Fix player parsing issue
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: enhancement

#4510 Add gender support to EnumUtils
  src/main/java/ch/njol/skript/localization/Noun.java
  src/main/java/ch/njol/skript/util/EnumUtils.java
Labels: enhancement

#4620 ⚒️ Fix parser formatting in debug mode
  src/main/java/ch/njol/skript/log/LogEntry.java
Labels: enhancement

#4641 ⚒️ Remove CondWeather and add it to default comparators
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/conditions/CondWeather.java
Labels: enhancement, 2.7, breaking changes

#4901 Update version on master branch
  gradle.properties
Labels: enhancement

#4833 🛠 Support multiple players in `CondPlayedBefore`
  src/main/java/ch/njol/skript/conditions/CondPlayedBefore.java
Labels: enhancement

#4900 Disable watchdog in tests
  src/main/java/ch/njol/skript/tests/platform/Environment.java
Labels: enhancement, unit testing

#3821 Make random vector expression components signed
  src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java
Labels: enhancement

#4906 Fix test servers crashing part 2
  src/main/java/ch/njol/skript/Skript.java
Labels: bug, unit testing

#4764 Remove WorldGuard 6 support
  build.gradle
  settings.gradle
  skript-worldguard6/.gitignore
  skript-worldguard6/build.gradle
  skript-worldguard6/src/main/java/ch/njol/skript/module/worldguard6/WorldGuard6Hook.java
  skript-worldguard6/src/main/java/ch/njol/skript/module/worldguard6/package-info.java
  src/main/java/ch/njol/skript/hooks/regions/WorldGuardHook.java
Labels: enhancement, 2.7

#4903 🚀 Update docs to 2.6.3
  classes.html
  conditions.html
  docs.json
  effects.html
  events.html
  expressions.html
  functions.html
  index.html
  text.html
  tutorials.html
Labels: documentation

#4907 Update maven publish workflow and JitPack Java version
  .github/workflows/repo.yml
  jitpack.yml
Labels: enhancement

#4870 Remove travis.yml
  .travis.yml
Labels: enhancement

#4243 Fix and improve some errors and exceptions
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/expressions/ExprDrops.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/variables/FlatFileStorage.java
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: enhancement

#4128 Make event values return item stacks instead of item types if possible
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug

#4884 isCurrentEvent API changes
  src/main/java/ch/njol/skript/conditions/CondIncendiary.java
  src/main/java/ch/njol/skript/conditions/CondResourcePack.java
  src/main/java/ch/njol/skript/effects/EffCancelCooldown.java
  src/main/java/ch/njol/skript/effects/EffHidePlayerFromServerList.java
  src/main/java/ch/njol/skript/effects/EffIncendiary.java
  src/main/java/ch/njol/skript/effects/EffPlayerInfoVisibility.java
  src/main/java/ch/njol/skript/expressions/ExprAbsorbedBlocks.java
  src/main/java/ch/njol/skript/expressions/ExprAppliedEnchantments.java
  src/main/java/ch/njol/skript/expressions/ExprAttacked.java
  src/main/java/ch/njol/skript/expressions/ExprBurnCookTime.java
  src/main/java/ch/njol/skript/expressions/ExprChatFormat.java
  src/main/java/ch/njol/skript/expressions/ExprChatRecipients.java
  src/main/java/ch/njol/skript/expressions/ExprClicked.java
  src/main/java/ch/njol/skript/expressions/ExprDrops.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantItem.java
  src/main/java/ch/njol/skript/expressions/ExprEnchantmentOffer.java
  src/main/java/ch/njol/skript/expressions/ExprExplodedBlocks.java
  src/main/java/ch/njol/skript/expressions/ExprExplosionBlockYield.java
  src/main/java/ch/njol/skript/expressions/ExprExplosionYield.java
  src/main/java/ch/njol/skript/expressions/ExprFertilizedBlocks.java
  src/main/java/ch/njol/skript/expressions/ExprHealAmount.java
  src/main/java/ch/njol/skript/expressions/ExprHealReason.java
  src/main/java/ch/njol/skript/expressions/ExprHostname.java
  src/main/java/ch/njol/skript/expressions/ExprHoverList.java
  src/main/java/ch/njol/skript/expressions/ExprIP.java
  src/main/java/ch/njol/skript/expressions/ExprLevel.java
  src/main/java/ch/njol/skript/expressions/ExprMOTD.java
  src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
  src/main/java/ch/njol/skript/expressions/ExprMe.java
  src/main/java/ch/njol/skript/expressions/ExprMendingRepairAmount.java
  src/main/java/ch/njol/skript/expressions/ExprOnlinePlayersCount.java
  src/main/java/ch/njol/skript/expressions/ExprPortal.java
  src/main/java/ch/njol/skript/expressions/ExprProtocolVersion.java
  src/main/java/ch/njol/skript/expressions/ExprPushedBlocks.java
  src/main/java/ch/njol/skript/expressions/ExprRespawnLocation.java
  src/main/java/ch/njol/skript/expressions/ExprServerIcon.java
  src/main/java/ch/njol/skript/expressions/ExprTamer.java
  src/main/java/ch/njol/skript/expressions/ExprVersionString.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
  src/main/java/ch/njol/util/coll/CollectionUtils.java
Labels: enhancement

#4836 Update Target
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
  src/main/java/ch/njol/skript/util/Utils.java
Labels: enhancement

#4781 Syntax for 1.18 Freezing Mechanics
  src/main/java/ch/njol/skript/conditions/CondIsFrozen.java
  src/main/java/ch/njol/skript/expressions/ExprFreezeTicks.java
  src/main/java/ch/njol/skript/expressions/ExprMaxFreezeTicks.java
  src/test/skript/tests/syntaxes/expressions/ExprFreezeTicks.sk
Labels: feature

#4655 Update branch model
  branches.md
Labels: enhancement

#4772 Fix double function signature error
  src/main/java/ch/njol/skript/lang/function/Functions.java
Labels: bug

#3873 Add last struck lightning
  src/main/java/ch/njol/skript/effects/EffLightning.java
  src/main/java/ch/njol/skript/expressions/ExprLastSpawnedEntity.java
Labels: enhancement

#4671 Add EffPathfind
  src/main/java/ch/njol/skript/effects/EffPathfind.java
Labels: feature

#4896 Fix function converters and plural arguments when single expected
  src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/test/skript/tests/regressions/4524-function call conversion.sk
  src/test/skript/tests/regressions/4859-function error with plural argument for single parameter.sk
Labels: bug, enhancement

#4515 Make scripts in directories load before rest
  src/main/java/ch/njol/skript/ScriptLoader.java
Labels: enhancement, breaking changes

#4664 ⚒️ Fix ExprFormatTime CCE + Support non-literals
  src/main/java/ch/njol/skript/expressions/ExprFormatDate.java
  src/main/java/ch/njol/skript/expressions/ExprFormatTime.java
  src/test/skript/tests/regressions/4664-formatted time.sk
Labels: bug, enhancement

#4690 ⚒️ Improve Time class
  src/main/java/ch/njol/skript/util/Time.java
Labels: enhancement

#4199 Add all plugins expression
  src/main/java/ch/njol/skript/expressions/ExprPlugins.java
Labels: feature

#4660 🚀 Support offline players in ExprBed
  src/main/java/ch/njol/skript/expressions/ExprBed.java
Labels: enhancement

#4935 Fixes sound category on 1.10.2
  src/main/java/ch/njol/skript/effects/EffStopSound.java
Labels: bug, legacy versions, 2.6

#4936 Fix 1.11.2 sweeping edge
  src/main/java/ch/njol/skript/bukkitutil/EnchantmentUtils.java
Labels: bug, legacy versions, 2.6

#4845 Fixes test system and adds 1.19 test environment
  .github/workflows/java-17-builds.yml
  .github/workflows/java-8-builds.yml
  .github/workflows/repo.yml
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/tests/TestResults.java
  src/main/java/ch/njol/skript/tests/platform/Environment.java
  src/main/java/ch/njol/skript/tests/platform/PlatformMain.java
  src/main/java/ch/njol/skript/tests/runner/TestMode.java
  src/main/java/ch/njol/skript/tests/runner/TestTracker.java
  src/test/resources/runner_data/server.properties.generic
  src/test/skript/README.md
  src/test/skript/environments/java17/paper-1.17.1.json
  src/test/skript/environments/java17/paper-1.18.2.json
  src/test/skript/environments/java17/paper-1.19.json
  src/test/skript/environments/java8/paper-1.13.2.json
  src/test/skript/environments/java8/paper-1.14.4.json
  src/test/skript/environments/java8/paper-1.15.2.json
  src/test/skript/environments/java8/paper-1.16.5.json
Labels: bug, enhancement, feature, unit testing

#4847 Add dependabot
  .github/dependabot.yml
Labels: feature, up for debate

#4937 🚀 Update Dev/2.6 -> 2.6.4
  gradle.properties
  src/main/java/ch/njol/skript/entity/ThrownPotionData.java
Labels: 2.6

#4619 🚀 Add Anvil Damage Event
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: enhancement

#4899 Add colours to the collection expression
  src/main/java/ch/njol/skript/expressions/ExprItems.java
  src/main/java/ch/njol/skript/expressions/ExprSets.java
  src/test/skript/tests/syntaxes/expressions/ExprSets.sk
Labels: enhancement

#4895 Improve event values move events
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtMove.java
Labels: bug, enhancement

#4784 Implement warning system for long parse times
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/resources/config.sk
Labels: feature, 2.7

#4700 Add world null check
  src/main/java/ch/njol/skript/bukkitutil/EntityUtils.java
  src/main/java/ch/njol/skript/effects/EffTeleport.java
Labels: bug

#4946 Fix nightly uploads
  .github/workflows/java-17-builds.yml
  .github/workflows/java-8-builds.yml
Labels: bug, unit testing

#4883 Added 'Raw String' expression
  src/main/java/ch/njol/skript/expressions/ExprRawString.java
Labels: feature

#4962 Attempts to fix the random zombie health test failing
  src/test/skript/tests/syntaxes/effects/EffHealth.sk
Labels: bug

#4940 Add testing environment to dev/2.6
  .github/dependabot.yml
  .github/workflows/java-17-builds.yml
  .github/workflows/java-8-builds.yml
  .github/workflows/legacy-tests.yml
  .github/workflows/repo.yml
  README.md
  build.gradle
  gradle.properties
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
  src/main/java/ch/njol/skript/tests/TestResults.java
  src/main/java/ch/njol/skript/tests/platform/Environment.java
  src/main/java/ch/njol/skript/tests/platform/PlatformMain.java
  src/main/java/ch/njol/skript/tests/runner/TestMode.java
  src/main/java/ch/njol/skript/tests/runner/TestTracker.java
  src/test/skript/environments/java17/paper-1.17.1.json
  src/test/skript/environments/java17/paper-1.18.2.json
  src/test/skript/environments/java17/paper-1.19.json
  src/test/skript/environments/java8/paper-1.12.2.json
  src/test/skript/environments/java8/paper-1.13.2.json
  src/test/skript/environments/java8/paper-1.14.4.json
  src/test/skript/environments/java8/paper-1.15.2.json
  src/test/skript/environments/java8/paper-1.16.5.json
  src/test/skript/environments/legacy/paper-1.10.2.json
  src/test/skript/environments/legacy/paper-1.11.2.json
  src/test/skript/environments/legacy/paper-1.12.2.json
  src/test/skript/environments/legacy/paper-1.9.4.json
  src/test/skript/tests/syntaxes/expressions/ExprEntityAttribute.sk
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: bug, enhancement, unit testing, legacy versions, 2.6

#4921 Add support for wolf collar colours
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/WolfData.java
  src/main/resources/lang/default.lang
Labels: bug, enhancement

#4964 Fix silverfish events
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/effects/EffDrop.java
  src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java
Labels: bug
