Repository SkriptLang/Skript, pull requests merged in 2022-05, with the labels that each got.

#4753 Add error when spawn section used on 1.9.4
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: bug, pre-1.13

#4754 Prepare for 2.6.2 release
  gradle.properties
  src/main/java/ch/njol/skript/expressions/ExprHanging.java
  src/main/java/ch/njol/skript/expressions/ExprPlayerProtocolVersion.java
  src/main/java/ch/njol/skript/expressions/ExprSaturation.java
Labels: 2.6

#4755 Update docs for 2.6.2
  classes.html
  conditions.html
  docs.json
  effects.html
  events.html
  expressions.html
  functions.html
  index.html
  text.html
  tutorials.html
Labels: documentation
