Repository SkriptLang/Skript, pull requests merged in 2022-04, with the labels that each got.

#4539 Add time states to biomes
  src/main/java/ch/njol/skript/expressions/ExprBiome.java
Labels: enhancement

#4540 Exclude entity event values from death events
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug, enhancement, up for debate

#4545 Fix message and broadcast with or list, redesign or ExpressionList getting
  src/main/java/ch/njol/skript/effects/EffBroadcast.java
  src/main/java/ch/njol/skript/effects/EffMessage.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
Labels: bug, enhancement, up for debate

#4551 Re-add ExprIndices pattern 'all' part
  src/main/java/ch/njol/skript/expressions/ExprIndices.java
Labels: bug

#4554 Fix ExprSaturation issues
  src/main/java/ch/njol/skript/expressions/ExprSaturation.java
Labels: bug

#4555 Re-add error from EffChange
  src/main/java/ch/njol/skript/effects/EffChange.java
Labels: bug

#4569 Add ExprPlayerProtocolVersion
  src/main/java/ch/njol/skript/expressions/ExprPlayerProtocolVersion.java
  src/main/java/ch/njol/skript/expressions/ExprProtocolVersion.java
Labels: feature

#4570 Fix another EventValue selection checkInstanceOf issue
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug

#4575 Make Skript only accept registrations if it is enabled
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement

#4592 🚀 Add Hanging Entity/Remover expression
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/ExprHanging.java
Labels: feature

#4699 Add string to region converter
  src/main/java/ch/njol/skript/hooks/regions/classes/Region.java
Labels: bug

#4710 Fix the pitch of locations of blocks
  src/main/java/ch/njol/skript/util/BlockUtils.java
Labels: bug

#4717 Fix falling block spawning with sections
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/FallingBlockData.java
  src/main/java/ch/njol/skript/entity/PlayerData.java
  src/main/java/ch/njol/skript/entity/ThrownPotionData.java
  src/main/java/ch/njol/skript/entity/XpOrbData.java
Labels: bug

#4646 Fix broken comparisons on 1.12 and below
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/test/skript/tests/regressions/3419-item comparisons.sk
Labels: bug

#4627 Fix variable iterator and EffReplace with items
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/test/skript/tests/regressions/4672-looping-expression-list-single-variables.sk
Labels: bug

#4532 Make EffectCommandEvent trigger as a Bukkit event
  src/main/java/ch/njol/skript/command/CommandEvent.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/command/EffectCommandEvent.java
Labels: enhancement

#4604 🚀 Fix some extra and missing `[the]`s
  src/main/java/ch/njol/skript/expressions/ExprAmount.java
  src/main/java/ch/njol/skript/expressions/ExprArrowPierceLevel.java
  src/main/java/ch/njol/skript/expressions/ExprFallDistance.java
  src/main/java/ch/njol/skript/expressions/ExprProjectileBounceState.java
  src/main/java/ch/njol/skript/expressions/ExprProjectileCriticalState.java
Labels: bug

#4611 Docs update to 2.6.1
  classes.html
  conditions.html
  docs.json
  effects.html
  events.html
  expressions.html
  functions.html
  index.html
  text.html
  tutorials.html
Labels: documentation

#4626 Fix vector length reset when adding/setting pitch & yaw
  src/main/java/ch/njol/skript/expressions/ExprYawPitch.java
Labels: bug

#4628 Utils#parseHexColor detail
  src/main/java/ch/njol/skript/util/Utils.java
Labels: enhancement

#4701 Add VectorMath#copyVector and fix ExprYawPitch changing
  src/main/java/ch/njol/skript/expressions/ExprYawPitch.java
  src/main/java/ch/njol/util/VectorMath.java
Labels: bug

#4630 ⚒️ Replace color char in debug statements
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/lang/TriggerItem.java
  src/main/java/ch/njol/skript/util/SkriptColor.java
Labels: enhancement

#4702 Add error when disabling hooks via config after server start
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptConfig.java
Labels: bug

#4711 Fix typo in empty folder warning
  src/main/resources/lang/english.lang
Labels: enhancement

#4735 Fix damage cause projectile comparison
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Labels: bug

#4728 Fix console colors
  src/main/java/ch/njol/skript/log/RedirectingLogHandler.java
  src/main/java/ch/njol/skript/log/RetainingLogHandler.java
  src/main/java/ch/njol/skript/log/SkriptLogger.java
  src/main/resources/lang/english.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/korean.lang
Labels: bug

#4138 Fix ConcurrentModificationException when reloading script during event execution
  src/main/java/ch/njol/skript/SkriptEventHandler.java
Labels: bug

#4615 ⚒️ Fix event-player in drop/pickup events
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug

#4739 Fix ExprChestInventory exceptions from too large chest inventories
  src/main/java/ch/njol/skript/expressions/ExprChestInventory.java
Labels: bug

#4649 Fix aliases duplicating item data for default item types
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
Labels: bug

#4688 ⚒️ Fix clicked enchantment button
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprClicked.java
Labels: bug, enhancement

#4683 ⚒️ Fix double chest inventory holder converter
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
Labels: bug
