Repository SkriptLang/Skript, pull requests merged in 2022-02, with the labels that each got.

#4587 Fix tests
  src/main/java/ch/njol/skript/SkriptAddon.java
  src/test/skript/tests/syntaxes/expressions/ExprIndices.sk
Labels: bug, unit-testing

#4616 Fix legacy method invocation in ExprLanguage
  src/main/java/ch/njol/skript/expressions/ExprLanguage.java
Labels: bug

#4546 Improve exception throwing of PatternCompiler
  src/main/java/ch/njol/skript/patterns/PatternCompiler.java
Labels: enhancement

#4529 Hex Color Fix
  src/main/java/ch/njol/skript/util/Utils.java
Labels: bug

#4530 Fix EffectSection parsing unrelated errors
  src/main/java/ch/njol/skript/lang/Effect.java
  src/main/java/ch/njol/skript/lang/Statement.java
Labels: bug

#4549 Fix 'no scripts found' warning displaying with a config line
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: enhancement

#4562 Update test system README.md
  src/test/skript/README.md
Labels: enhancement
