Repository SkriptLang/Skript, pull requests merged in 2022-06, with the labels that each got.

#4795 Changed from check against Material.AIR to Material#isAir in drop effect.
  src/main/java/ch/njol/skript/effects/EffDrop.java
Labels: bug

#4798 Change Material#isAir since the method is only avalible in versions 1.15 and later
  src/main/java/ch/njol/skript/effects/EffDrop.java
Labels: bug

#4767 Remove old tests
  build.gradle
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/lang/TriggerItem.java
  src/test/skript/environments/extra/paper-1.10.2.json
  src/test/skript/environments/extra/paper-1.11.2.json
  src/test/skript/environments/extra/paper-1.15.2.json
  src/test/skript/environments/main/paper-1.17.1.json
  src/test/skript/environments/main/paper-1.18.1.json
  src/test/skript/environments/main/paper-1.18.2.json
Labels: enhancement, 2.7

#4822 Fix Locale-related String conversion issues
  build.gradle
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/main/java/ch/njol/skript/aliases/AliasesParser.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/command/CommandHelp.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/effects/EffLog.java
  src/main/java/ch/njol/skript/expressions/ExprCommandInfo.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/UnparsedLiteral.java
  src/main/java/ch/njol/skript/lang/function/Parameter.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/main/java/ch/njol/skript/patterns/LiteralPatternElement.java
  src/main/java/ch/njol/skript/patterns/SkriptPattern.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/util/EnchantmentType.java
  src/main/java/ch/njol/skript/util/PotionDataUtils.java
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
  src/main/java/ch/njol/skript/util/SkriptColor.java
  src/main/java/ch/njol/skript/util/StructureType.java
  src/main/java/ch/njol/skript/util/Timespan.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
  src/main/java/ch/njol/skript/util/chat/MessageComponent.java
  src/main/java/ch/njol/util/Kleenean.java
Labels: bug

#4763 Update Paper API Endpoints
  build.gradle
  src/main/java/ch/njol/skript/tests/platform/Environment.java
Labels: enhancement

#4801 SimpleEntityData - cleanup
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
Labels: enhancement, 2.7

#4834 Update Minecraft 1.19 stuff
  build.gradle
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/entity/BoatChestData.java
  src/main/java/ch/njol/skript/entity/FrogData.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/java/ch/njol/skript/hooks/biomes/BiomeMapUtil.java
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
  src/main/resources/lang/default.lang
Labels: enhancement

#4740 Add Expression#getOptionalSingle
  src/main/java/ch/njol/skript/lang/Expression.java
Labels: enhancement

#4223 Fix spelling mistake in Classes
  src/main/java/ch/njol/skript/registrations/Classes.java
Labels: enhancement

#4631 Update bStats
  build.gradle
  src/main/java/ch/njol/skript/Metrics.java
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement

#4852 Fix for PrepareItemCraftEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug, completed

#4851 Improve visualeffect syntax
  src/main/resources/lang/default.lang
Labels: enhancement

#4837 ⚒️ Update config.sk examples to use `::` instead of `.`
  src/main/resources/config.sk
Labels: enhancement

#4808 Make both sound syntaxes similar
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
Labels: enhancement

#4805 Avoid negative level experience
  src/main/java/ch/njol/skript/expressions/ExprLevel.java
Labels: bug

#4594 🚀 Add age of block expression
  src/main/java/ch/njol/skript/expressions/ExprBlockAge.java
Labels: feature

#4776 Parse more UnparsedLiterals, but only if they're actually meaningful
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: bug

#4839 Allow for continue in while loops
  src/main/java/ch/njol/skript/effects/EffContinue.java
  src/test/skript/tests/syntaxes/effects/EffContinue.sk
Labels: enhancement
