Repository SkriptLang/Skript, pull requests merged in 2022-11, with the labels that each got.

#5182 Remove Testable interface
  src/main/java/ch/njol/skript/effects/EffEquip.java
  src/main/java/ch/njol/skript/lang/Testable.java
Labels: enhancement, hacktoberfest-accepted

#5175 Remove cap on freeze time in 1.18 freeze syntax
  src/main/java/ch/njol/skript/expressions/ExprFreezeTicks.java
  src/test/skript/tests/syntaxes/expressions/ExprFreezeTicks.sk
Labels: enhancement, hacktoberfest-accepted

#5185 Add LivingEntity invisibility syntax
  src/main/java/ch/njol/skript/conditions/CondIsInvisible.java
  src/main/java/ch/njol/skript/effects/EffInvisible.java
  src/test/skript/tests/syntaxes/effects/EffInvisible.sk
Labels: feature, hacktoberfest-accepted

#5123 SimpleEvents: Add EntityJumpEvent (Paper 1.15+)
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#5171 Add exact event checking when converting event-values in last attempt
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug, 2.6, hacktoberfest-accepted

#5139 Local Functions
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/function/Function.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
  src/main/java/ch/njol/skript/lang/function/JavaFunction.java
  src/main/java/ch/njol/skript/lang/function/Namespace.java
  src/main/java/ch/njol/skript/lang/function/Parameter.java
  src/main/java/ch/njol/skript/lang/function/Signature.java
  src/main/java/ch/njol/skript/structures/StructFunction.java
  src/test/skript/tests/syntaxes/structures/StructFunction.sk
Labels: feature, 2.7, hacktoberfest-accepted

#5189 Fix EffConnect exception when given players are offline
  src/main/java/ch/njol/skript/effects/EffConnect.java
Labels: bug, 2.6

#4677 Add ExprNearestEntity
  src/main/java/ch/njol/skript/expressions/ExprNearestEntity.java
  src/test/skript/tests/syntaxes/expressions/ExprNearestEntity.sk
Labels: feature

#5183 Improve ExprElement to use iterators
  src/main/java/ch/njol/skript/expressions/ExprElement.java
  src/test/skript/tests/syntaxes/expressions/ExprElement.sk
Labels: enhancement, hacktoberfest-accepted

#5213 Update contributing.md
  .github/contributing.md
Labels: enhancement

#5207 Add Location Within Radius condition
  src/main/java/ch/njol/skript/conditions/CondWithinRadius.java
Labels: feature

#4949 Update Version -> 2.6.4 on Master
  gradle.properties
Labels: enhancement, 2.6

#5129 Add EnumClassInfo
  src/main/java/ch/njol/skript/classes/EnumClassInfo.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/util/BiomeUtils.java
  src/main/java/ch/njol/skript/util/DamageCauseUtils.java
  src/main/java/ch/njol/skript/util/InventoryActions.java
Labels: enhancement, hacktoberfest-accepted

#5205 All Banned Players Expression
  src/main/java/ch/njol/skript/expressions/ExprAllBannedEntries.java
Labels: feature

#5068 add within location condition
  src/main/java/ch/njol/skript/conditions/CondIsWithinLocation.java
Labels: feature

#5061 Add moon phase expression
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprMoonPhase.java
  src/main/resources/lang/default.lang
Labels: feature

#5199 Use provided expression's iterator in ExprFilter
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
  src/test/skript/tests/syntaxes/expressions/ExprFilter.sk
Labels: enhancement

#5217 Add delete variable api
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: feature
