Repository SkriptLang/Skript, pull requests merged in 2022-12, with the labels that each got.

#5228 change subtext doc name to substring to find easier
  src/main/java/ch/njol/skript/expressions/ExprSubstring.java
Labels: documentation

#5234 Fix EffReplace incorrectly setting ExpressionList values
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/test/skript/tests/syntaxes/effects/EffReplace.sk
Labels: bug

#5233 Fix "target falling block" not working
  src/main/java/ch/njol/skript/entity/FallingBlockData.java
Labels: bug

#5172 Add Block Data support to ExprTypeOf
  src/main/java/ch/njol/skript/expressions/ExprTypeOf.java
Labels: enhancement, hacktoberfest-accepted

#4618 🚀 Add anvil input text expression
  src/main/java/ch/njol/skript/expressions/ExprAnvilText.java
Labels: feature, 2.7

#5051 Removed Op EntityData.
  src/main/java/ch/njol/skript/conditions/CondIsOp.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/PlayerData.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/java/ch/njol/skript/expressions/ExprOps.java
  src/main/resources/lang/default.lang
Labels: enhancement, breaking changes

#5165 Implement and/or condition sections
  src/main/java/ch/njol/skript/sections/SecConditional.java
  src/test/skript/tests/syntaxes/sections/SecConditional.sk
Labels: feature, hacktoberfest-accepted

#5252 DefaultComparators - add comparator for BlockData - BlockData
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
Labels: bug

#5212 Update code-conventions.md
  code-conventions.md
Labels: enhancement

#5248 Add setTime to the code-conventions
  code-conventions.md
Labels: enhancement

#5221 Add missing lang nodes
  build.gradle
  src/main/resources/lang/default.lang
Labels: bug

#4985 Adds lookAt for entities and players
  src/main/java/ch/njol/skript/bukkitutil/EntityUtils.java
  src/main/java/ch/njol/skript/bukkitutil/PaperEntityUtils.java
  src/main/java/ch/njol/skript/effects/EffLook.java
Labels: feature

#5274 Fix ExprParse wrong return type
  src/main/java/ch/njol/skript/expressions/ExprParse.java
  src/test/skript/tests/regressions/5262-exprparse return type array.sk
Labels: bug

#5227 Allow modification of real player cap
  src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
  src/test/skript/tests/syntaxes/expressions/ExprMaxPlayers.sk
Labels: feature

#4994 Set the string flavour tag of the jar in the actions artifacts to nightly
  .github/workflows/java-17-builds.yml
  .github/workflows/java-8-builds.yml
  .github/workflows/repo.yml
  build.gradle
Labels: enhancement, unit testing

#4999 Adds spectator start/stop/swap Paper events and spectator target event value expression
  src/main/java/ch/njol/skript/events/EvtSpectate.java
  src/main/java/ch/njol/skript/expressions/ExprSpectatorTarget.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
Labels: bug, enhancement, feature

#4605 Rewrite the Default Examples
  src/main/resources/scripts/-examples/chest menus.sk
  src/main/resources/scripts/-examples/commands.sk
  src/main/resources/scripts/-examples/events.sk
  src/main/resources/scripts/-examples/functions.sk
  src/main/resources/scripts/-examples/loops.sk
  src/main/resources/scripts/-examples/options and meta.sk
  src/main/resources/scripts/-examples/text formatting.sk
  src/main/resources/scripts/-examples/timings.sk
  src/main/resources/scripts/-examples/variables.sk
  src/main/resources/scripts/command with cooldown.sk
  src/main/resources/scripts/custom helmet.sk
  src/main/resources/scripts/disable weather.sk
  src/main/resources/scripts/eternal day.sk
  src/main/resources/scripts/furnace automatisation.sk
  src/main/resources/scripts/homes.sk
  src/main/resources/scripts/item command.sk
  src/main/resources/scripts/kill counter.sk
  src/main/resources/scripts/nerf endermen.sk
  src/main/resources/scripts/realistic drops.sk
  src/main/resources/scripts/simple god mode.sk
  src/main/resources/scripts/simple join and leave message.sk
  src/main/resources/scripts/simple motd.sk
  src/main/resources/scripts/teleport with compass.sk
  src/main/resources/scripts/vanilla gui.sk
Labels: enhancement, 2.7

#5283 Clean up ExprBlockData.sk test after running
  src/test/skript/tests/syntaxes/expressions/ExprBlockData.sk
Labels: bug

#5025 Add changers to ExprBookPages
  src/main/java/ch/njol/skript/expressions/ExprBookPages.java
Labels: enhancement

#5282 Improve book edit event `event values`
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug

#5280 Add `a/an` support for some type enums
  src/main/resources/lang/default.lang
Labels: enhancement

#4855 Respawn Anchor Support
  src/main/java/ch/njol/skript/conditions/CondAnchorWorks.java
  src/main/java/ch/njol/skript/conditions/CondRespawnLocation.java
  src/main/java/ch/njol/skript/expressions/ExprCharges.java
Labels: feature

#5289 Add pi literal
  src/main/java/ch/njol/skript/expressions/LitPi.java
Labels: feature

#5143 command prefix entry
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/structures/StructCommand.java
Labels: feature, 2.7

#4241 Fix rounding accuracy
  src/main/java/ch/njol/util/Math2.java
  src/test/skript/tests/regressions/4235-floating point errors rounding functions.sk
Labels: bug

#5144 Structure API Improvements and Fixes
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptEventHandler.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/conditions/CondScriptLoaded.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/effects/EffSuppressWarnings.java
  src/main/java/ch/njol/skript/structures/StructCommand.java
  src/main/java/ch/njol/skript/structures/StructFunction.java
  src/main/java/org/skriptlang/skript/lang/entry/EntryContainer.java
  src/main/java/org/skriptlang/skript/lang/entry/EntryValidator.java
Labels: bug, enhancement, 2.7

#5278 Add MarkedForRemoval annotation
  src/main/java/ch/njol/skript/util/MarkedForRemoval.java
Labels: enhancement

#5294 Update EffActionBar.java
  src/main/java/ch/njol/skript/effects/EffActionBar.java
Labels: enhancement
