Repository SkriptLang/Skript, pull requests merged in 2022-10, with the labels that each got.

#4087 Improve command expressions for command events and script commands
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/command/ScriptCommandEvent.java
  src/main/java/ch/njol/skript/expressions/ExprArgument.java
  src/main/java/ch/njol/skript/expressions/ExprCmdCooldownInfo.java
  src/main/java/ch/njol/skript/expressions/ExprCommand.java
Labels: feature

#5089 Allow parse tags to be expanded onto optional pattern elements
  src/main/java/ch/njol/skript/patterns/OptionalPatternElement.java
  src/main/java/ch/njol/skript/patterns/ParseTagPatternElement.java
Labels: enhancement

#4797 Fixed only highest event super class getting registered.
  src/main/java/ch/njol/skript/SkriptEventHandler.java
  src/main/java/ch/njol/skript/events/EvtCommand.java
Labels: bug

#5072 Add lang file updates on version change
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/config/Config.java
  src/main/java/ch/njol/skript/config/SectionNode.java
  src/main/java/ch/njol/skript/localization/Language.java
Labels: enhancement

#5136 Fix toString of TypePatternElement
  src/main/java/ch/njol/skript/patterns/TypePatternElement.java
Labels: enhancement, 2.6

#5047 Make defendExpression create new ExpressionList
  src/main/java/ch/njol/skript/util/LiteralUtils.java
Labels: bug

#5071 Escape colons in ExprParse
  src/main/java/ch/njol/skript/expressions/ExprParse.java
Labels: bug, 2.6

#5131 Fix wrong array component type for ExprEntities
  src/main/java/ch/njol/skript/expressions/ExprEntities.java
Labels: bug, 2.6

#5118 Fix pattern issue with EffPotion
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/test/skript/tests/syntaxes/effects/EffPotion.sk
Labels: bug, 2.6

#5132 Pickup Delay Expression
  src/main/java/ch/njol/skript/expressions/ExprPickupDelay.java
Labels: feature

#5106 Fix message sending on legacy versions
  src/main/java/ch/njol/skript/effects/EffBroadcast.java
  src/main/java/ch/njol/skript/effects/EffMessage.java
Labels: bug, 2.6

#5150 Fix isQuotedCorrectly, to account for 1-char string `"`
  src/main/java/ch/njol/skript/lang/VariableString.java
Labels: bug

#5164 Add translation to the Polish language
  src/main/resources/config.sk
  src/main/resources/lang/english.lang
  src/main/resources/lang/polish.lang
Labels: enhancement

#4966 Cleanup ExprSpawn
  src/main/java/ch/njol/skript/expressions/ExprSpawn.java
Labels: enhancement, 2.7

#4976 🚀 Add `last launched firework`
  src/main/java/ch/njol/skript/effects/EffFireworkLaunch.java
  src/main/java/ch/njol/skript/expressions/ExprLastSpawnedEntity.java
Labels: enhancement

#5141 Implement unregistering event listeners when possible
  src/main/java/ch/njol/skript/SkriptEventHandler.java
  src/main/java/ch/njol/skript/events/EvtClick.java
Labels: feature, 2.7

#4961 Fix ItemData Serialization
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/main/java/ch/njol/skript/aliases/MaterialRegistry.java
  src/main/java/ch/njol/skript/bukkitutil/block/BlockValues.java
  src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
  src/test/skript/tests/misc/item data serialization.sk
Labels: bug, breaking changes, 2.6

#5169 dev/2.6 Implement missing methods for Block implementations
  build.gradle
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Labels: bug, 2.6

#5052 Fix conversion for list-modifying expressions
  src/main/java/ch/njol/skript/expressions/ExprReversedList.java
  src/main/java/ch/njol/skript/expressions/ExprShuffledList.java
  src/main/java/ch/njol/skript/expressions/ExprSortedList.java
Labels: enhancement, 2.6

#5158 Remove Relational Variables
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/conditions/CondHasRelationalVariable.java
  src/main/java/ch/njol/skript/expressions/ExprRelationalVariable.java
  src/main/java/ch/njol/skript/util/ListVariablePersistentDataType.java
  src/main/java/ch/njol/skript/util/PersistentDataUtils.java
  src/main/java/ch/njol/skript/util/SingleVariablePersistentDataType.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprRelationalVariable.sk
Labels: dev needed, up for debate, 2.6

#5070 add environment expression
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprWorldEnvironment.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprWorldEnvironment.sk
Labels: feature

#5095 Fix offhand tool getter in tool change event
  src/main/java/ch/njol/skript/expressions/ExprTool.java
Labels: bug, 2.6

#5173 Resolves EffFireworkLaunch's IAE from out-of-range power number input
  src/main/java/ch/njol/skript/effects/EffFireworkLaunch.java
Labels: bug, 2.6

#5153 Is Gliding Condition (#5145)
  src/main/java/ch/njol/skript/conditions/CondIsGliding.java
Labels: feature, hacktoberfest-accepted
