Repository SkriptLang/Skript, pull requests merged in 2022-09, with the labels that each got.

#4640 ⚒️ Improve ExprBalance
  src/main/java/ch/njol/skript/hooks/economy/expressions/ExprBalance.java
Labels: enhancement

#5084 Remove Dependabot language label
  .github/dependabot.yml
Labels: enhancement

#5012 Plus symbol new line standard
  code-conventions.md
Labels: enhancement, documentation

#5035 Add french translation
  src/main/resources/config.sk
  src/main/resources/lang/french.lang
Labels: enhancement

#4938 ⚒️ Fix Time Played NSME
  src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
  src/test/skript/tests/regressions/4938-time played.sk
Labels: bug, 2.7, 2.6

#5091 allow multiple livingentities in EffEquip's pattern
  src/main/java/ch/njol/skript/effects/EffEquip.java
Labels: enhancement

#5049 Add Paper's PlayerTradeEvent in SimpleEvents
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#4967 Update tests readme
  src/test/skript/README.md
Labels: enhancement

#5115 Move EffMakeHatch to effect folder
  src/main/java/ch/njol/skript/effects/EffMakeEggHatch.java
Labels: enhancement

#4911 EffSecSpawn improvements and fixes
  src/main/java/ch/njol/skript/effects/Delay.java
  src/main/java/ch/njol/skript/effects/IndeterminateDelay.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/Trigger.java
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: bug, 2.7

#5066 ExprJoinSplit config case sensitivity
  src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
Labels: enhancement

#5057 Fix falling block NPE
  src/main/java/ch/njol/skript/entity/FallingBlockData.java
Labels: bug, 2.6
