Repository SkriptLang/Skript, pull requests merged in 2023-06, with the labels that each got.

#5667 Make aliases faster
  src/main/java/ch/njol/skript/aliases/AliasesParser.java
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
  src/main/java/ch/njol/skript/aliases/ItemData.java
Labels: enhancement, needs testing, 2.7

#5503 Fix the legendary compare issue with two same literals
  src/main/java/ch/njol/skript/conditions/CondCompare.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/test/runner/EffAssert.java
  src/main/java/ch/njol/skript/test/runner/EvtTestCase.java
  src/main/java/ch/njol/skript/test/runner/SkriptJUnitTest.java
  src/main/java/ch/njol/skript/test/runner/TestTracker.java
  src/test/skript/tests/misc/dummy.sk
  src/test/skript/tests/regressions/2711-item-compares.sk
  src/test/skript/tests/regressions/4769-fire-visualeffect.sk
  src/test/skript/tests/regressions/4773-composter-the-imposter.sk
  src/test/skript/tests/regressions/pull-5566-block iterator being 100 always.sk
  src/test/skript/tests/syntaxes/expressions/ExprBlockData.sk
Labels: bug, priority: medium, 2.7

#5714 Improve documentation workflows
  .github/workflows/docs.yml
  .github/workflows/docs/generate-docs/action.yml
  .github/workflows/docs/push-docs/action.yml
  .github/workflows/docs/setup-docs/action.yml
  .github/workflows/nightly-docs.yml
  .github/workflows/release-docs.yml
  build.gradle
  src/main/java/ch/njol/skript/test/platform/Environment.java
  src/main/java/ch/njol/skript/test/utils/TestResults.java
Labels: enhancement, documentation, 2.7, github related

#5574 Bump version to 2.7.0-beta3
  gradle.properties
  src/main/java/ch/njol/skript/expressions/ExprDurability.java
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
Labels: feature, 2.7

#5729 Remove hidden files from tab complete
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
Labels: enhancement

#5618 Add is climbing
  src/main/java/ch/njol/skript/conditions/CondIsClimbing.java
Labels: feature

#5482 Add Vector Projection Expression
  src/main/java/ch/njol/skript/expressions/ExprVectorProjection.java
Labels: feature

#5359 Condition LivingEntity is Jumping
  src/main/java/ch/njol/skript/conditions/CondIsJumping.java
Labels: feature

#5474 Add InventoryDragEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature, 2.7

#5357 Adds EffToggleCanPickUpItems + CondCanPickUpItems
  src/main/java/ch/njol/skript/conditions/CondCanPickUpItems.java
  src/main/java/ch/njol/skript/effects/EffToggleCanPickUpItems.java
  src/test/skript/tests/syntaxes/effects/EffToggleCanPickUpItems.sk
Labels: feature

#4617 🚀 Add anvil repair cost expression
  src/main/java/ch/njol/skript/expressions/ExprAnvilRepairCost.java
Labels: feature

#5573 Adds Clamp Function
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/test/skript/tests/syntaxes/functions/clamp.sk
Labels: feature

#5763 Add quit reason
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/ExprQuitReason.java
  src/main/resources/lang/default.lang
Labels: feature

#4595 🚀 Add `loop-counter` & Improve loops
  src/main/java/ch/njol/skript/effects/EffContinue.java
  src/main/java/ch/njol/skript/effects/EffExit.java
  src/main/java/ch/njol/skript/effects/EffReturn.java
  src/main/java/ch/njol/skript/expressions/ExprLoopIteration.java
  src/main/java/ch/njol/skript/expressions/ExprLoopValue.java
  src/main/java/ch/njol/skript/lang/LoopSection.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/main/java/ch/njol/skript/sections/SecWhile.java
  src/test/skript/tests/regressions/4595-loop-iteration.sk
Labels: feature

#5494 Add CondIsLeftHanded and EffHandedness
  src/main/java/ch/njol/skript/conditions/CondIsLeftHanded.java
  src/main/java/ch/njol/skript/effects/EffHandedness.java
  src/test/skript/tests/syntaxes/effects/EffHandedness.sk
Labels: feature

#5757 [2.7.0 target] Add InventoryDragEvent (#5474) to 2.7.0 release
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature, 2.7

#5588 New Event: PlayerPickupArrowEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#5271 Add time states for PlayerItemHeldEvent and hotbar slot
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
Labels: enhancement

#5760 [2.7.0 target] Update 2.7.0 to Spigot 1.20.1
  build.gradle
  gradle.properties
  src/main/resources/lang/default.lang
  src/test/skript/environments/java17/paper-1.20.1.json
Labels: 2.7, dependencies

#5502 Vector from direction
  src/main/java/ch/njol/skript/expressions/ExprVectorFromDirection.java
  src/main/java/ch/njol/skript/util/Direction.java
Labels: feature

#5683 Add event-item and event-slot to Resurrect Event
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: enhancement
