Repository SkriptLang/Skript, pull requests merged in 2023-02, with the labels that each got.

#5231 Add Simplified Chinese Translation
  src/main/resources/config.sk
  src/main/resources/lang/simplifiedchinese.lang
Labels: feature, 2.7

#5418 Add Japanese Translation
  src/main/resources/config.sk
  src/main/resources/lang/japanese.lang
Labels: feature, 2.7

#5224 Fix uncoloured expression
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
  src/test/skript/tests/syntaxes/expressions/ExprColoured.sk
Labels: bug, 2.7

#5374 Improve ItemMeta comparisons
  src/main/java/ch/njol/skript/aliases/ItemData.java
Labels: bug, 2.7

#5383 Automatically generate and push docs for nightly editions
  .github/workflows/docs.yml
  build.gradle
  src/main/java/ch/njol/skript/doc/Documentation.java
Labels: feature

#5420 Fix issue with nightly docs job not working when javadocs dir is already present
  .github/workflows/docs.yml
Labels: bug

#4930 Stop using String for enum serialization
  src/main/java/ch/njol/skript/classes/EnumSerializer.java
  src/main/java/ch/njol/skript/classes/YggdrasilSerializer.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/entity/EntityType.java
Labels: variables, 2.7

#5423 Fix expression list checking
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/test/skript/tests/misc/expression list checking.sk
Labels: bug, 2.7

#5376 💣 Remove docs folder
  docs/README.md
  docs/assets/Logo/Skript Logo Circular.png
  docs/assets/Logo/Skript Logo.jpg
  docs/assets/Logo/Skript Logo.png
  docs/assets/icon.png
  docs/assets/light-off.svg
  docs/assets/light-on.svg
  docs/assets/search.svg
  docs/classes.html
  docs/conditions.html
  docs/css/styles.css
  docs/docs.html
  docs/docs.json
  docs/effects.html
  docs/events.html
  docs/expressions.html
  docs/functions.html
  docs/index.html
  docs/js/functions.js
  docs/js/main.js
  docs/js/theme-switcher.js
  docs/sections.html
  docs/template.html
  docs/templates/desc_full.html
  docs/templates/desc_full.json
  docs/templates/desc_nav.html
  docs/templates/navbar.html
  docs/templates/pattern_element.html
  docs/templates/pattern_element.json
  docs/text.html
  docs/tutorials.html
Labels: documentation

#5353 Add copy to clipboard tag
  src/main/java/ch/njol/skript/util/Utils.java
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
  src/main/java/ch/njol/skript/util/chat/MessageComponent.java
  src/main/java/ch/njol/skript/util/chat/SkriptChatCode.java
  src/main/resources/lang/default.lang
Labels: feature

#5426 🛠 Fix a forgotten Typo in Docs Bot
  .github/workflows/docs.yml
Labels: bug

#5397 Create CondIsPreferredTool.java
  src/main/java/ch/njol/skript/conditions/CondIsPreferredTool.java
  src/test/skript/tests/syntaxes/conditions/CondIsPreferredTool.sk
Labels: feature

#5370 Add method exists condition for testing
  src/main/java/ch/njol/skript/tests/runner/CondMethodExists.java
  src/test/skript/tests/syntaxes/conditions/CondMethodExists.sk
Labels: feature, unit testing

#5381 It checks if the item is stackable.
  src/main/java/ch/njol/skript/conditions/CondIsStackable.java
Labels: feature

#5410 Update README.md
  README.md
Labels: enhancement

#5427 🚀 Add a cover to README.md
  .github/assets/Cover.jpg
  README.md
Labels: enhancement

#5333 ExprPlayerViewDistance - re-enable this expression
  src/main/java/ch/njol/skript/expressions/ExprPlayerViewDistance.java
Labels: enhancement

#5433 🚀 Update docs link in README
  README.md
Labels: bug

#5077 Get all the values of a classinfo
  src/main/java/ch/njol/skript/classes/ClassInfo.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/expressions/ExprItems.java
  src/main/java/ch/njol/skript/expressions/ExprSets.java
  src/main/java/ch/njol/skript/registrations/Classes.java
Labels: enhancement

#5399 Create ExprBreakSpeed.java
  src/main/java/ch/njol/skript/expressions/ExprBreakSpeed.java
Labels: feature

#5249 Improve sound effects
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
  src/main/java/ch/njol/skript/effects/EffStopSound.java
Labels: enhancement

#5272 Add a default expression register to property expression
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
Labels: feature, 2.8

#5317 Fix default variables
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/structures/StructVariables.java
  src/main/java/ch/njol/skript/variables/Variables.java
  src/test/skript/tests/misc/default variables.sk
Labels: bug, feature, variables, 2.7

#5436 Allow using alises when parsing BlockData
  src/main/java/ch/njol/skript/util/BlockUtils.java
  src/test/skript/tests/misc/blockdata parser.sk
Labels: enhancement

#5449 Fix Function NPE
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
  src/main/java/ch/njol/skript/lang/function/Namespace.java
Labels: bug, 2.7

#5321 Further Structure API Enhancements
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/structures/StructAliases.java
  src/main/java/ch/njol/skript/structures/StructCommand.java
  src/main/java/ch/njol/skript/structures/StructOptions.java
  src/main/java/org/skriptlang/skript/lang/script/Script.java
  src/main/java/org/skriptlang/skript/lang/script/ScriptEvent.java
  src/main/java/org/skriptlang/skript/lang/script/ScriptEventHandler.java
  src/test/skript/tests/syntaxes/structures/StructCommand.sk
Labels: bug, enhancement, 2.7

#5198 Add Value Within expression
  src/main/java/ch/njol/skript/expressions/ExprValueWithin.java
  src/test/skript/tests/syntaxes/expressions/ExprValueWithin.sk
Labels: feature

#5454 Remove buildbot
  buildbot-compile.sh
  updaterepo.sh
Labels: enhancement

#5391 Add EffKnockback
  src/main/java/ch/njol/skript/effects/EffKnockback.java
Labels: feature

#5295 Add rounding by decimal placement
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/test/skript/tests/syntaxes/functions/round.sk
Labels: feature

#5354 Adds PlayerInventorySlotChangeEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#5448 Adds PlayerDeepSleepEvent
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature

#5447 Event Player Enter Chunk
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/events/EvtPlayerChunkEnter.java
Labels: feature

#5200 Update Expression#stream to specify Stream elements should be non-null
  src/main/java/ch/njol/skript/lang/Expression.java
Labels: breaking changes

#5470 Fix double space in toString of ExprPermissions
  src/main/java/ch/njol/skript/expressions/ExprPermissions.java
Labels: enhancement

#5466 Script handling improvements
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/expressions/ExprScript.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/org/skriptlang/skript/lang/script/Script.java
  src/test/skript/tests/misc/effect commands.sk
Labels: bug, enhancement, 2.7

#5475 Fix plural event values exception
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
Labels: bug
