Repository SkriptLang/Skript, pull requests merged in 2023-08, with the labels that each got.

#5462 Adds InventoryMoveItemEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtItem.java
  src/main/java/ch/njol/skript/expressions/ExprEvtInitiator.java
Labels: feature

#5589 New Expression: Attached Block of Arrow
  src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
Labels: feature

#5734 Bump master to 2.8.0-dev
  gradle.properties
Labels: feature

#5887 🚀 Add Teleport Cause EXIT_BED
  src/main/resources/lang/default.lang
Labels: enhancement

#5888 [2.7] 🚀 Add Teleport Cause EXIT_BED
  src/main/resources/lang/default.lang
Labels: enhancement

#5892 Address Variable Loading Changes
  src/main/java/ch/njol/skript/Skript.java
Labels: 2.7

#5897 [2.7] Address Variable Loading Changes (#5892)
  src/main/java/ch/njol/skript/Skript.java
Labels: bug, 2.7

#5863 Fix and add chat format to books
  src/main/java/ch/njol/skript/expressions/ExprBookPages.java
  src/test/skript/tests/syntaxes/expressions/ExprBookPages.sk
Labels: bug, enhancement, feature, 2.7

#5894 Add support for keybind components
  src/main/java/ch/njol/skript/util/chat/BungeeConverter.java
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
  src/main/java/ch/njol/skript/util/chat/MessageComponent.java
  src/main/java/ch/njol/skript/util/chat/SkriptChatCode.java
  src/main/resources/lang/default.lang
Labels: enhancement, require docs update

#5899 [2.7.0 target] Enhancement/books 5863
  src/main/java/ch/njol/skript/expressions/ExprBookPages.java
  src/test/skript/tests/syntaxes/expressions/ExprBookPages.sk
Labels: bug, enhancement, 2.7

#5817 Explain luck perms group
  src/main/java/ch/njol/skript/hooks/permission/expressions/ExprGroup.java
Labels: enhancement, documentation

#5917 Disable Timings for 1.19.4+
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/resources/config.sk
Labels: enhancement, 2.7

#5872 Fix issue where mixing different types of conditionals sometimes isn't allowed
  src/main/java/ch/njol/skript/sections/SecConditional.java
  src/test/skript/tests/syntaxes/sections/SecConditional.sk
Labels: bug, 2.7

#5926 [2.7.0 target] Disable Timings for 1.19.4+ 5917
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/resources/config.sk
Labels: enhancement, 2.7

#5416 🛠 Fix Duplicated Spaces in StructCommand
  src/main/java/ch/njol/skript/structures/StructCommand.java
Labels: bug, 2.7

#5845 🚀 Add `player(nameOrUUID: string, getExactPlayer: boolean)` function
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/registrations/DefaultClasses.java
Labels: feature

#5811 Add the ability to execute as a bungeecord command
  src/main/java/ch/njol/skript/effects/EffCommand.java
Labels: enhancement

#5932 [2.7.0 target] Fix issue where mixing different types of conditionals
  src/main/java/ch/njol/skript/sections/SecConditional.java
  src/test/skript/tests/syntaxes/sections/SecConditional.sk
Labels: bug, 2.7

#5927 ⚒ Fix enchanting multiple items
  src/main/java/ch/njol/skript/effects/EffEnchant.java
Labels: bug, 2.7

#5680 🚀 Add `inventory close reasons`
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/ExprInventoryCloseReason.java
  src/main/resources/lang/default.lang
Labels: feature

#5934 ⚒ [2.7] Fix enchanting multiple items
  src/main/java/ch/njol/skript/effects/EffEnchant.java
Labels: bug, 2.7

#5874 Add defending for simple property expressions
  src/main/java/ch/njol/skript/expressions/base/SimplePropertyExpression.java
Labels: bug, enhancement

#5949 Adds ExprPercent
  src/main/java/ch/njol/skript/expressions/ExprPercent.java
  src/test/skript/tests/syntaxes/expressions/ExprPercent.sk
Labels: feature

#5898 Added "apply bone meal" effect.
  src/main/java/ch/njol/skript/effects/EffApplyBoneMeal.java
Labels: feature

#5636 New Expression: Free / Max / Total Memory
  src/main/java/ch/njol/skript/expressions/ExprMemory.java
Labels: feature

#5629 EvtPlayerChunkEnter - Fix Docs
  src/main/java/ch/njol/skript/events/EvtPlayerChunkEnter.java
Labels: enhancement

#5947 Change ExprTarget to use raytracing
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
  src/test/skript/tests/syntaxes/expressions/ExprYawPitch.sk
Labels: enhancement

#5929 🛠 [2.7] Fix Duplicated Spaces in StructCommand (#5416)
  src/main/java/ch/njol/skript/structures/StructCommand.java
Labels: bug, 2.7

#5886 SimpleEntityData - Display should be super entity
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
Labels: bug
