Repository SkriptLang/Skript, pull requests merged in 2023-12, with the labels that each got.

#6205 Improve Location Comparison
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/test/skript/tests/regressions/6205-location comparison.sk
Labels: bug, 2.7

#6201 Allow asynchronous SkriptEvent#check execution
  src/main/java/ch/njol/skript/SkriptEventHandler.java
Labels: bug, enhancement

#6123 Fix ExprSets conflicting
  src/main/java/ch/njol/skript/expressions/ExprSets.java
Labels: bug, 2.7

#6208 Prepare for Release (2.7.3)
  gradle.properties
Labels: 2.7

#6224 Fix incorrect examples for EffPotion
  src/main/java/ch/njol/skript/effects/EffPotion.java
Labels: bug

#5867 Add characters between and random characters expressions
  src/main/java/ch/njol/skript/expressions/ExprCharacters.java
  src/main/java/ch/njol/skript/expressions/ExprRandomCharacter.java
  src/test/skript/tests/syntaxes/expressions/ExprCharacters.sk
  src/test/skript/tests/syntaxes/expressions/ExprRandomCharacters.sk
Labels: feature, feature-ready

#5958 Removes Projectile Bounce State Expr and Cond
  src/main/java/ch/njol/skript/conditions/CondProjectileCanBounce.java
  src/main/java/ch/njol/skript/expressions/ExprProjectileBounceState.java
Labels: enhancement, breaking changes

#5815 More(!?) Converter and Comparator Improvements
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/main/java/ch/njol/skript/lang/LiteralList.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/util/LiteralUtils.java
  src/main/java/org/skriptlang/skript/lang/comparator/ComparatorInfo.java
  src/main/java/org/skriptlang/skript/lang/comparator/Comparators.java
  src/main/java/org/skriptlang/skript/lang/comparator/ConvertedComparator.java
  src/main/java/org/skriptlang/skript/lang/comparator/InverseComparator.java
  src/main/java/org/skriptlang/skript/lang/converter/ChainedConverter.java
  src/main/java/org/skriptlang/skript/lang/converter/Converter.java
  src/main/java/org/skriptlang/skript/lang/converter/ConverterInfo.java
  src/main/java/org/skriptlang/skript/lang/converter/Converters.java
  src/test/skript/tests/regressions/5848-converter comparator issues.sk
Labels: bug, enhancement, 2.8

#5440 Add parse section for testing
  src/main/java/ch/njol/skript/log/RetainingLogHandler.java
  src/main/java/ch/njol/skript/test/runner/ExprParseLogs.java
  src/main/java/ch/njol/skript/test/runner/SecParse.java
  src/test/skript/tests/syntaxes/sections/SecParse.sk
Labels: feature, unit testing

#5367 Add glowing sign text support
  src/main/java/ch/njol/skript/conditions/CondGlowingText.java
  src/main/java/ch/njol/skript/effects/EffGlowingText.java
  src/test/skript/tests/syntaxes/effects/EffGlowingText.sk
Labels: feature, feature-ready

#5365 Active Item API
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/conditions/CondIsHandRaised.java
  src/main/java/ch/njol/skript/effects/EffCancelItemUse.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprActiveItem.java
  src/main/java/ch/njol/skript/expressions/ExprEntityItemUseTime.java
  src/main/java/ch/njol/skript/expressions/ExprMaxItemUseTime.java
  src/main/java/ch/njol/skript/expressions/ExprReadiedArrow.java
Labels: feature, feature-ready

#5366 Add support for getting and modifying ItemType inventories
  src/main/java/ch/njol/skript/expressions/ExprInventory.java
  src/test/skript/tests/syntaxes/expressions/ExprInventory.sk
Labels: enhancement, feature-ready

#6239 (Patch) Fix NPE issue with drops in 1.20.2
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/expressions/ExprDrops.java
Labels: bug

#4614 Add filter support to ExprItemsIn
  src/main/java/ch/njol/skript/expressions/ExprItemsIn.java
  src/test/skript/tests/syntaxes/expressions/ExprItemsIn.sk
Labels: enhancement

#6229 Remove init override in anvil text expression.
  src/main/java/ch/njol/skript/expressions/ExprAnvilText.java
Labels: bug

#6172 Proper plurality on EffCommand
  src/main/java/ch/njol/skript/effects/EffCommand.java
Labels: enhancement

#6266 Fix CondCompare Logging
  src/main/java/ch/njol/skript/conditions/CondCompare.java
Labels: bug, 2.8, feature-ready

#6261 Remove final on 'cleanup' method and provide JUnit implementation warnings.
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/test/runner/SkriptJUnitTest.java
Labels: bug, 2.8, feature-ready

#6146 Allow multiple hashtags to start comments at the beginning of a line.
  src/main/java/ch/njol/skript/config/Node.java
  src/test/java/org/skriptlang/skript/test/tests/config/NodeTest.java
Labels: enhancement, 2.8, hacktoberfest-accepted, feature-ready
