Repository SkriptLang/Skript, pull requests merged in 2023-01, with the labels that each got.

#5300 Fix examples and lang files not generating
  src/main/java/ch/njol/skript/Skript.java
Labels: bug

#5290 Support Worlds into ExprName.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
Labels: enhancement

#5275 ExprParse improvements
  src/main/java/ch/njol/skript/expressions/ExprParse.java
  src/main/java/ch/njol/skript/patterns/MatchResult.java
  src/main/java/ch/njol/skript/patterns/PatternCompiler.java
  src/main/java/ch/njol/skript/patterns/SkriptPattern.java
Labels: enhancement

#5313 Add isValid for entities
  src/main/java/ch/njol/skript/conditions/CondIsValid.java
Labels: feature

#5316 Fix inconsistency in README.md
  README.md
Labels: enhancement

#5335 EvtItem - add support for EntityDropItemEvent
  src/main/java/ch/njol/skript/events/EvtItem.java
Labels: enhancement

#5310 SimpleEntityData - add Enemy/Camel entities
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/resources/lang/default.lang
Labels: enhancement

#5320 Fix scripts example folder generation
  src/main/java/ch/njol/skript/Skript.java
Labels: bug, priority: high, 2.7

#5343 BukkitEventValues - current/past event-block both return the same for BlockSpreadEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug

#5273 Bump to 2.7 developer version tag
  gradle.properties
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/main/java/ch/njol/skript/util/Version.java
  src/main/resources/config.sk
Labels: core task, 2.7

#5368 🛠 Removes 1.13 code from ItemUtils.isAir
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
Labels: bug, enhancement

#5377 add event value for BlockSpreadEvent.getSource();
  src/main/java/ch/njol/skript/expressions/ExprSourceBlock.java
Labels: enhancement

#5375 Add support for LootGenerateEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprLoot.java
Labels: feature

#5372 Fix isCurrentEvent checks
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
Labels: bug, 2.7

#5348 Fix getting random literal lists not being random
  src/main/java/ch/njol/skript/expressions/ExprRandom.java
  src/main/java/ch/njol/skript/lang/util/ConvertedLiteral.java
  src/test/skript/tests/regressions/5345-any-aliases-random.sk
Labels: bug, 2.7

#5168 Plural Event Values
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/expressions/ExprEventExpression.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/util/coll/CollectionUtils.java
Labels: enhancement, needs testing, breaking changes

#5076 Wacky Wednesday's #1: The Pickle API
  src/main/java/ch/njol/skript/expressions/ExprSeaPickles.java
Labels: feature

#5385 Allow the readme.txt to be generated in lang folder
  src/main/java/ch/njol/skript/Skript.java
Labels: bug

#5103 Use keyword searching to improve parsing speeds
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/patterns/LiteralPatternElement.java
  src/main/java/ch/njol/skript/patterns/TypePatternElement.java
Labels: enhancement, 2.7

#5214 Add deprecated methods to support old API for now
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
Labels: bug, 2.7

#5363 Support for unequipping items for EffEquip
  src/main/java/ch/njol/skript/effects/EffEquip.java
Labels: enhancement

#5349 Fix assertion effect throwing errors when verbose is in debug
  src/main/java/ch/njol/skript/tests/runner/EffAssert.java
Labels: bug, unit testing, 2.7

#5362 EffCancelEvent - update player inventory after cancelling
  src/main/java/ch/njol/skript/effects/EffCancelEvent.java
Labels: bug

#5079 Fix/number converters
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/test/skript/tests/regressions/4445-number-conversion.sk
Labels: bug, 2.7

#5407 Improve hashCode of Pair
  src/main/java/ch/njol/util/Pair.java
Labels: enhancement

#5413 Update ExprFormatDate.java
  src/main/java/ch/njol/skript/expressions/ExprFormatDate.java
Labels: bug

#5415 Fix empty string parsing
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: bug

#5412 FishData - add tadpole
  src/main/java/ch/njol/skript/entity/FishData.java
Labels: enhancement

#5140 Deprecate SelfRegisteringSkriptEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtAtTime.java
  src/main/java/ch/njol/skript/events/EvtChat.java
  src/main/java/ch/njol/skript/events/EvtExperienceSpawn.java
  src/main/java/ch/njol/skript/events/EvtMoveOn.java
  src/main/java/ch/njol/skript/events/EvtPeriodical.java
  src/main/java/ch/njol/skript/events/EvtScript.java
  src/main/java/ch/njol/skript/events/EvtSkript.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/events/util/PlayerChatEventHandler.java
  src/main/java/ch/njol/skript/events/util/package-info.java
  src/main/java/ch/njol/skript/expressions/ExprMessage.java
  src/main/java/ch/njol/skript/hooks/regions/events/EvtRegionBorder.java
  src/main/java/ch/njol/skript/lang/SelfRegisteringSkriptEvent.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
Labels: enhancement, 2.7

#5329 Make SimpleExpression copy the received array before returning it
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
Labels: bug, enhancement, 2.7
