Repository SkriptLang/Skript, pull requests merged in 2023-09, with the labels that each got.

#5735 Documentation actions improvements
  .github/workflows/cleanup-docs.yml
  .github/workflows/docs/generate-docs/action.yml
  .github/workflows/docs/push-docs/action.yml
  .github/workflows/docs/setup-docs/action.yml
  .github/workflows/nightly-docs.yml
  .github/workflows/release-docs.yml
  build.gradle
Labels: enhancement, documentation, github related

#5777 Add infinite and icon to potion effects
  src/main/java/ch/njol/skript/conditions/CondIsInfinite.java
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
Labels: bug, enhancement, 2.7

#5669 Structure API Finalization
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/structures/StructCommand.java
  src/main/java/ch/njol/skript/structures/StructOptions.java
  src/main/java/org/skriptlang/skript/lang/entry/EntryContainer.java
  src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/util/LiteralEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/util/TriggerEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/util/VariableStringEntryData.java
  src/main/java/org/skriptlang/skript/lang/script/Script.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
Labels: bug, enhancement, 2.7, breaking changes

#5976 Add decrease to EffChange
  src/main/java/ch/njol/skript/effects/EffChange.java
Labels: enhancement

#5699 Fixes an exception from being thrown on async events
  src/main/java/ch/njol/skript/SkriptEventHandler.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
Labels: bug, 2.7

#5982 🍒 [2.7] Add infinite and icon to potion effects
  src/main/java/ch/njol/skript/conditions/CondIsInfinite.java
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
Labels: bug, enhancement, 2.7

#5981 🍒 [2.7] Structure API Finalization (#5669)
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/structures/StructCommand.java
  src/main/java/ch/njol/skript/structures/StructOptions.java
  src/main/java/org/skriptlang/skript/lang/entry/EntryContainer.java
  src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/util/LiteralEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/util/TriggerEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/util/VariableStringEntryData.java
  src/main/java/org/skriptlang/skript/lang/script/Script.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
Labels: bug, enhancement, 2.7

#5980 🍒 [2.7] Fixes an exception from being thrown on async events
  src/main/java/ch/njol/skript/SkriptEventHandler.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
Labels: bug, 2.7

#6001 Rename Slot classinfo name to Slot
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
Labels: enhancement

#5658 🛠 Fix keep inv/exp and other bugs related to death event
  src/main/java/ch/njol/skript/effects/EffKeepInventory.java
  src/main/java/ch/njol/skript/effects/EffRespawn.java
  src/main/java/ch/njol/skript/expressions/ExprLevel.java
Labels: bug

#5877 Fix event-item not being present in book sign
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug, 2.7

#5997 ⚒ [2.7] EffPotion - fix potion duration issue
  src/main/java/ch/njol/skript/effects/EffPotion.java
Labels: bug, 2.7, patch-ready

#6003 🛠 [2.7] Fix keep inv/exp and other bugs related to death event (#5658)
  src/main/java/ch/njol/skript/effects/EffKeepInventory.java
  src/main/java/ch/njol/skript/effects/EffRespawn.java
  src/main/java/ch/njol/skript/expressions/ExprLevel.java
Labels: bug, 2.7, patch-ready

#6004 Fix book sign event item
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug, 2.7, patch-ready

#6006 ⚒️ Add `NoDoc` annotation to test elements
  src/main/java/ch/njol/skript/test/runner/CondMethodExists.java
  src/main/java/ch/njol/skript/test/runner/CondMinecraftVersion.java
  src/main/java/ch/njol/skript/test/runner/EvtTestCase.java
Labels: enhancement, documentation

#6002 Add GitHub's gradle wrapper checker for security
  .github/workflows/java-17-builds.yml
  .github/workflows/java-8-builds.yml
  .github/workflows/junit-17-builds.yml
  .github/workflows/junit-8-builds.yml
  .github/workflows/repo.yml
Labels: feature, github related, feature-ready

#6022 Fix ExprRandomNumber using a method from Java 17
  src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
Labels: bug, 2.7, patch-ready

#6021 Fix changing remaining time of command cooldown
  src/main/java/ch/njol/skript/command/ScriptCommand.java
Labels: bug, patch-ready

#5978 Fix NPE with invalid attributes and clean up ExprEntityAttribute
  src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
Labels: bug, patch-ready

#5993 Bump version to 2.7.1
  gradle.properties
Labels: enhancement, 2.7, patch-ready

#5942 Fix cast throwing if existing variable for command storage exists
  src/main/java/ch/njol/skript/command/ScriptCommand.java
Labels: bug, patch-ready

#6010 Allow and with for the title effect
  src/main/java/ch/njol/skript/effects/EffSendTitle.java
Labels: enhancement, feature-ready

#6027 fix 3 stray INSERT VERSIONs from 2.7.0
  src/main/java/ch/njol/skript/conditions/CondIsInfinite.java
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: bug, patch-ready

#5456 Add get all armour of living entities
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/test/skript/tests/syntaxes/expressions/ExprArmorSlot.sk
Labels: feature, breaking changes, feature-ready

#5571 Enhance Shearing Related Elements
  src/main/java/ch/njol/skript/conditions/CondIsSheared.java
  src/main/java/ch/njol/skript/effects/EffShear.java
Labels: enhancement, feature, feature-ready

#5580 Move documentation into its own folder
  src/main/java/ch/njol/skript/doc/Documentation.java
Labels: enhancement, documentation, feature-ready

#6024 Allow 'continue' the continue outer loops
  src/main/java/ch/njol/skript/effects/EffContinue.java
  src/test/skript/tests/syntaxes/effects/EffContinue.sk
Labels: enhancement, feature-ready

#6025 Tidy up parts of config class.
  src/main/java/ch/njol/skript/config/Config.java
Labels: enhancement, patch-ready

#6041 Add Release Model Document
  CLOCKWORK_RELEASE_MODEL.md
  README.md
Labels: enhancement, patch-ready

#6026 (Cherry Pick) Fix cast throwing if existing variable for command storage exists (#5942)
  src/main/java/ch/njol/skript/command/ScriptCommand.java
Labels: patch-ready

#6023 (Cherry Pick) Fix NPE with invalid attributes and clean up ExprEntityAttribute (#5978)
  src/main/java/ch/njol/skript/expressions/ExprEntityAttribute.java
Labels: 2.7, patch-ready

#5408 Yggdrasil Cleanup
  src/main/java/ch/njol/yggdrasil/ClassResolver.java
  src/main/java/ch/njol/yggdrasil/DefaultYggdrasilInputStream.java
  src/main/java/ch/njol/yggdrasil/DefaultYggdrasilOutputStream.java
  src/main/java/ch/njol/yggdrasil/FieldHandler.java
  src/main/java/ch/njol/yggdrasil/Fields.java
  src/main/java/ch/njol/yggdrasil/JRESerializer.java
  src/main/java/ch/njol/yggdrasil/PseudoEnum.java
  src/main/java/ch/njol/yggdrasil/SimpleClassResolver.java
  src/main/java/ch/njol/yggdrasil/Tag.java
  src/main/java/ch/njol/yggdrasil/Yggdrasil.java
  src/main/java/ch/njol/yggdrasil/YggdrasilException.java
  src/main/java/ch/njol/yggdrasil/YggdrasilID.java
  src/main/java/ch/njol/yggdrasil/YggdrasilInputStream.java
  src/main/java/ch/njol/yggdrasil/YggdrasilOutputStream.java
  src/main/java/ch/njol/yggdrasil/YggdrasilSerializable.java
  src/main/java/ch/njol/yggdrasil/YggdrasilSerializer.java
  src/main/java/ch/njol/yggdrasil/util/JREFieldHandler.java
  src/main/java/ch/njol/yggdrasil/xml/YggXMLInputStream.java
  src/main/java/ch/njol/yggdrasil/xml/YggXMLOutputStream.java
  src/main/java/ch/njol/yggdrasil/xml/package-info.java
Labels: enhancement

#5974 Update gradle to gradle 8.3
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#6050 Fix multiple aliases sections not working
  src/main/java/ch/njol/skript/structures/StructAliases.java
  src/test/skript/tests/syntaxes/structures/StructAliases.sk
Labels: bug

#6054 Remove 'MarkedForRemoval' Annotation
  src/main/java/ch/njol/skript/util/MarkedForRemoval.java
  src/main/java/ch/njol/util/Math2.java
Labels: enhancement, feature-ready

#6047 Fix error when unloading a script with multiple variables sections
  src/main/java/ch/njol/skript/structures/StructVariables.java
  src/test/skript/tests/syntaxes/structures/StructVariables.sk
Labels: bug, patch-ready

#6059 ⚒ Disable Javadocs generation for nightly docs & improvements
  .github/workflows/docs/generate-docs/action.yml
  .github/workflows/nightly-docs.yml
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
  src/main/resources/lang/english.lang
  src/main/resources/lang/french.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/simplifiedchinese.lang
Labels: enhancement, documentation, github related

#6063 Change the target branch of dependabot
  .github/dependabot.yml
Labels: github related

#6067 ⚒ Fix stop all sounds NPE
  src/main/java/ch/njol/skript/effects/EffStopSound.java
Labels: bug, patch-ready

#5307 Remove deprecated getTicks
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/effects/Delay.java
  src/main/java/ch/njol/skript/effects/EffIgnite.java
  src/main/java/ch/njol/skript/effects/EffPoison.java
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/main/java/ch/njol/skript/effects/EffSendTitle.java
  src/main/java/ch/njol/skript/effects/IndeterminateDelay.java
  src/main/java/ch/njol/skript/events/EvtPeriodical.java
  src/main/java/ch/njol/skript/expressions/ExprBurnCookTime.java
  src/main/java/ch/njol/skript/expressions/ExprFireTicks.java
  src/main/java/ch/njol/skript/expressions/ExprFreezeTicks.java
  src/main/java/ch/njol/skript/expressions/ExprMaxFreezeTicks.java
  src/main/java/ch/njol/skript/expressions/ExprPickupDelay.java
  src/main/java/ch/njol/skript/expressions/ExprPotionEffect.java
  src/main/java/ch/njol/skript/expressions/ExprRemainingAir.java
  src/main/java/ch/njol/skript/expressions/ExprTime.java
  src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
  src/main/java/ch/njol/skript/util/Timespan.java
  src/main/java/ch/njol/skript/variables/VariablesStorage.java
Labels: enhancement, breaking changes, 2.8, feature-ready

#5796 Allow for all possible entity change block states
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java
Labels: enhancement, feature-ready

#5841 Add chat format support for inventories
  src/main/java/ch/njol/skript/expressions/ExprChestInventory.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
Labels: feature, feature-ready

#5941 Change NORMAL ExpressionType to EVENT
  src/main/java/ch/njol/skript/expressions/ExprCommandSender.java
  src/main/java/ch/njol/skript/expressions/ExprDamageCause.java
  src/main/java/ch/njol/skript/expressions/ExprEgg.java
  src/main/java/ch/njol/skript/expressions/ExprEvtInitiator.java
  src/main/java/ch/njol/skript/expressions/ExprInventoryAction.java
  src/main/java/ch/njol/skript/expressions/ExprItem.java
  src/main/java/ch/njol/skript/expressions/ExprQuitReason.java
  src/main/java/ch/njol/skript/expressions/ExprSpawnReason.java
  src/main/java/ch/njol/skript/expressions/ExprTeleportCause.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/hooks/regions/expressions/ExprRegion.java
  src/main/java/ch/njol/skript/lang/ExpressionType.java
Labels: enhancement, 2.8, feature-ready

#5460 Adds PlayerStonecutterRecipeSelectEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtItem.java
Labels: feature

#5665 Pull request template defaults
  .github/pull_request_template.md
Labels: enhancement, github related

#5678 🚀 Add Item Damge event to ExprDamage
  src/main/java/ch/njol/skript/expressions/ExprDamage.java
Labels: bug, enhancement, feature-ready

#5965 Fix EvtPlayerChunkEnter Comparison & Cleanup
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtPlayerChunkEnter.java
Labels: bug, enhancement, patch-ready

#6033 Fixes EffSecSpawn not properly handling local variables created within the section
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/test/skript/tests/regressions/6032-local-vars-created-in-effsecspawn.sk
Labels: bug, patch-ready

#5966 Remove PlayerPreprocessCommandEvent listener and clean up Commands
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/conditions/CondIsSkriptCommand.java
  src/main/resources/config.sk
Labels: bug, enhancement, needs testing, patch-ready, feature-ready

#5308 Add support for InventoryClickEvent cursor
  src/main/java/ch/njol/skript/expressions/ExprCursorSlot.java
  src/main/java/ch/njol/skript/util/slot/CursorSlot.java
Labels: enhancement

#5952 Clean up vector classes and fix a few bugs.
  src/main/java/ch/njol/skript/effects/EffVectorRotateAroundAnother.java
  src/main/java/ch/njol/skript/effects/EffVectorRotateXYZ.java
  src/main/java/ch/njol/skript/expressions/ExprVectorAngleBetween.java
  src/main/java/ch/njol/skript/expressions/ExprVectorArithmetic.java
  src/main/java/ch/njol/skript/expressions/ExprVectorBetweenLocations.java
  src/main/java/ch/njol/skript/expressions/ExprVectorCrossProduct.java
  src/main/java/ch/njol/skript/expressions/ExprVectorCylindrical.java
  src/main/java/ch/njol/skript/expressions/ExprVectorDotProduct.java
  src/main/java/ch/njol/skript/expressions/ExprVectorFromXYZ.java
  src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java
  src/main/java/ch/njol/skript/expressions/ExprVectorLength.java
  src/main/java/ch/njol/skript/expressions/ExprVectorNormalize.java
  src/main/java/ch/njol/skript/expressions/ExprVectorOfLocation.java
  src/main/java/ch/njol/skript/expressions/ExprVectorSpherical.java
  src/main/java/ch/njol/skript/expressions/ExprVectorSquaredLength.java
  src/main/java/ch/njol/skript/expressions/ExprVectorXYZ.java
Labels: enhancement, patch-ready
