Repository SkriptLang/Skript, pull requests merged in 2023-04, with the labels that each got.

#5443 ExprRandomNumber ArithmeticException fix
  src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
Labels: bug

#5564 Removal of ExprIdOf
  src/main/java/ch/njol/skript/aliases/MaterialRegistry.java
  src/main/java/ch/njol/skript/expressions/ExprIdOf.java
Labels: enhancement, breaking changes

#5585 EvtPlayerChunkEnter - Make 'player' Keyword Optional
  src/main/java/ch/njol/skript/events/EvtPlayerChunkEnter.java
Labels: enhancement

#5587 Fix Comparison Mistake in CondIsWithin
  src/main/java/ch/njol/skript/conditions/CondIsWithin.java
Labels: bug

#5522 Remove travis CI tag
  README.md
Labels: bug

#5566 Fix two bugs with block iterator
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
  src/main/java/ch/njol/skript/expressions/ExprDirection.java
  src/main/java/ch/njol/skript/util/BlockLineIterator.java
  src/test/skript/tests/regressions/pull-5566-block iterator being 100 always.sk
Labels: bug, 2.7

#4667 Allow literal-only string parsing
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
Labels: enhancement, needs testing

#5605 Change loading order for BukkitClasses
  src/main/java/ch/njol/skript/Skript.java
Labels: bug, 2.7

#5623 Include the Adventure API BungeeComponentSerializer
  build.gradle
Labels: feature, dependencies

#4873 Add support for registering custom VariableStorage
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/variables/MySQLStorage.java
  src/main/java/ch/njol/skript/variables/SQLStorage.java
  src/main/java/ch/njol/skript/variables/SQLiteStorage.java
  src/main/java/ch/njol/skript/variables/Variables.java
  src/main/java/ch/njol/skript/variables/VariablesStorage.java
Labels: enhancement, feature, variables

#5621 ExprVectorRandom - Fix Vectors not Unit & Not True Random Generations
  src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java
Labels: bug

#5643 Fix databases not currently registering
  src/main/java/ch/njol/skript/variables/FlatFileStorage.java
  src/main/java/ch/njol/skript/variables/SQLStorage.java
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: bug, priority: critical, 2.7

#4221 🚀 Fix `Delete` changer & Add `Reset` changer to ExprTarget
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
Labels: bug, enhancement
