Repository SkriptLang/Skript, pull requests merged in 2023-11, with the labels that each got.

#6154 Fix ExprDurability's Changer
  src/main/java/ch/njol/skript/expressions/ExprDurability.java
  src/test/skript/tests/syntaxes/expressions/ExprDurability.sk
Labels: bug, needs testing

#5639 Rework EvtGrow
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/events/EvtGrow.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/EvtGrowTest.java
  src/test/skript/tests/junit/EvtGrow.sk
Labels: bug, breaking changes, feature-ready

#6170 Fix arm swing description
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: enhancement

#6181 Ensure EvtGrow Junit test always grows the plants/trees
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/EvtGrowTest.java
Labels: enhancement

#5961 Orientation Change Support for Move Event
  src/main/java/ch/njol/skript/events/EvtMove.java
Labels: enhancement, feature-ready

#6162 add isNaN() function
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/expressions/ExprSpecialNumber.java
  src/test/skript/tests/syntaxes/functions/isNaN.sk
Labels: enhancement, feature-ready

#6171 Prevent InventoryHolder -> X chaining
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
Labels: bug, 2.7, patch-ready

#5900 Make event parsing more reliable
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/java/ch/njol/skript/structures/StructEvent.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
Labels: enhancement, breaking changes, 2.8, feature-ready
