Repository SkriptLang/Skript, pull requests merged in 2023-10, with the labels that each got.

#6081 Fix Logging Issues In ExpressionEntryData
  src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java
Labels: bug

#6078 Update Minecraft wiki links to new domain
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/conditions/CondIsSlimeChunk.java
  src/main/java/ch/njol/skript/effects/EffExplosion.java
  src/main/java/ch/njol/skript/expressions/ExprAge.java
  src/main/java/ch/njol/skript/expressions/ExprExplosionYield.java
  src/main/java/ch/njol/skript/expressions/ExprExplosiveYield.java
  src/main/java/ch/njol/skript/expressions/ExprGlidingState.java
  src/main/java/ch/njol/skript/expressions/ExprScoreboardTags.java
Labels: enhancement, documentation, patch-ready

#6090 ⚒ Fix fake player count paper check error
  src/main/java/ch/njol/skript/expressions/ExprOnlinePlayersCount.java
Labels: bug, patch-ready

#6080 Fix Command Help
  src/main/java/ch/njol/skript/command/CommandHelp.java
Labels: bug, patch-ready

#5955 Add WILL to property condition
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
Labels: enhancement, feature-ready

#6106 Fix unloading/reloading a directory in the scripts effect
  src/main/java/ch/njol/skript/effects/EffScriptFile.java
Labels: bug, 2.7, hacktoberfest-accepted, patch-ready

#6103 Force UTF-8 encoding for Gradle daemon
  gradle.properties
Labels: bug, enhancement, hacktoberfest-accepted, patch-ready

#6038 Corrected Javadocs name, title
  .gitignore
  build.gradle
Labels: enhancement, documentation, patch-ready, feature-ready

#6057 Rebase JUnit references fix for dev/patch
  build.gradle
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/conditions/CondMinecraftVersion.java
  src/main/java/ch/njol/skript/test/runner/CondRunningJUnit.java
  src/main/java/ch/njol/skript/test/runner/EffObjectives.java
  src/main/java/ch/njol/skript/test/runner/TestTracker.java
  src/test/java/org/skriptlang/skript/test/junit/registration/ExprJUnitTest.java
  src/test/java/org/skriptlang/skript/test/junit/registration/package-info.java
  src/test/skript/junit/README.md
  src/test/skript/junit/SimpleJUnitTest.sk
Labels: bug, 2.7

#6121 Fix options issue in functions
  src/main/java/ch/njol/skript/structures/StructFunction.java
  src/test/skript/tests/syntaxes/structures/StructCommand.sk
  src/test/skript/tests/syntaxes/structures/StructFunction.sk
Labels: bug, patch-ready

#6126 Fix command permission messages (2.7.1 issue)
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/command/ScriptCommand.java
Labels: bug, patch-ready

#6117 Fix stack overflow when stringifying block inventories.
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: hacktoberfest-accepted, patch-ready

#5889 ExprCommandInfo Enhancements
  src/main/java/ch/njol/skript/expressions/ExprCommandInfo.java
Labels: bug, enhancement, breaking changes

#5550 Allow profilers to run
  build.gradle
  src/main/java/ch/njol/skript/test/platform/Environment.java
  src/main/java/ch/njol/skript/test/platform/PlatformMain.java
Labels: bug, unit testing

#6128 Fix comparison of cyclical types (specifically comparing times)
  src/main/java/ch/njol/skript/conditions/CondCompare.java
  src/main/java/ch/njol/skript/util/Time.java
  src/main/java/org/skriptlang/skript/lang/util/Cyclical.java
  src/main/java/org/skriptlang/skript/lang/util/package-info.java
  src/test/skript/tests/syntaxes/conditions/CondCompare.sk
Labels: bug, 2.7, hacktoberfest-accepted

#6132 Fix floating point rounding error in loop N times
  src/main/java/ch/njol/skript/expressions/ExprTimes.java
  src/test/skript/tests/syntaxes/expressions/ExprTimes.sk
Labels: bug, hacktoberfest-accepted

#5878 Fix some issues with ExprParse
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/expressions/ExprParse.java
  src/main/java/ch/njol/skript/hooks/regions/classes/Region.java
  src/main/java/ch/njol/skript/lang/ParseContext.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/test/skript/tests/syntaxes/expressions/ExprParse.sk
Labels: bug

#6139 Allow numbers in the changer for ExprHotbarSlot
  src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
Labels: enhancement

#6102 Fix Sorted List Expression
  src/main/java/ch/njol/skript/expressions/ExprSortedList.java
  src/test/skript/tests/syntaxes/expressions/ExprSortedList.sk
Labels: bug, 2.7, hacktoberfest-accepted, patch-ready

#6150 Fix colour codes being reset in reload message.
  src/main/resources/lang/english.lang
  src/main/resources/lang/french.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/japanese.lang
  src/main/resources/lang/korean.lang
  src/main/resources/lang/polish.lang
Labels: bug, hacktoberfest-accepted
