Repository SkriptLang/Skript, pull requests merged in 2023-05, with the labels that each got.

#5660 ExprBlocks: Fix ArrayStoreException
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
Labels: bug, 2.7

#5654 Revert "Allow literal-only string parsing"
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
Labels: bug, 2.7

#5591 [BUG] CondIsPreferredTool invalid checks
  src/main/java/ch/njol/skript/conditions/CondIsPreferredTool.java
  src/test/skript/tests/syntaxes/conditions/CondIsPreferredTool.sk
Labels: bug

#5649 Fix error in non default variables
  src/main/java/ch/njol/skript/lang/VariableString.java
Labels: bug, 2.7

#5668 Add info about clearing your tests in the test README
  src/test/skript/README.md
Labels: enhancement, documentation

#5017 Fix ExprDurability
  src/main/java/ch/njol/skript/expressions/ExprDurability.java
  src/test/skript/tests/regressions/3303-item durability.sk
Labels: enhancement, needs testing, breaking changes

#5303 🛠 Fix toFormattedString for null nodes
  src/main/java/ch/njol/skript/log/LogEntry.java
Labels: bug

#5297 Rewrite Math2
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/util/AABB.java
  src/main/java/ch/njol/util/Math2.java
Labels: enhancement, 2.8

#5099 Better chest inventory syntax
  src/main/java/ch/njol/skript/expressions/ExprChestInventory.java
Labels: enhancement, up for debate

#4696 Clarify error message about leftclick on entity
  src/main/java/ch/njol/skript/events/EvtClick.java
Labels: enhancement

#5673 Fixes IllegalArgumentException throwing with unloaded worlds in location serialization
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: bug, 2.7

#5609 Fix ExprVersionString Unusable in Server List Ping Event
  src/main/java/ch/njol/skript/expressions/ExprVersionString.java
Labels: bug, 2.7

#5607 New Event: Falling Block Fall
  src/main/java/ch/njol/skript/events/EvtEntityBlockChange.java
Labels: enhancement, 2.7

#5579 Fix for exact event values in the event value expression
  src/main/java/ch/njol/skript/expressions/ExprEgg.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug, 2.7

#5685 🛠 Fix docs examples non HTML tags not escaped
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
Labels: bug, documentation

#5712 Apply entity data changes before calling consumer
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/test/skript/tests/syntaxes/expressions/ExprTotalExperience.sk
Labels: bug, 2.7, breaking changes

#5694 Fix Item Comparisons For "Base" ItemTypes
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/test/skript/tests/regressions/3419-item comparisons.sk
Labels: bug, enhancement, 2.7

#5577 Rework Event-Trigger Matching to use MultiMap instead of List of Pairs
  src/main/java/ch/njol/skript/SkriptEventHandler.java
Labels: enhancement

#5684 🛠 Fix fireworkeffect classinfo doesn't have usage
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: enhancement, documentation

#5688 🛠 Fix docs searching keywords not included in classinfos and functions
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/lang/function/JavaFunction.java
Labels: bug, documentation

#5686 🛠 Fix docs returntype check inverted
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
Labels: bug, documentation

#5062 Implement serial comma support in lists
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: bug, breaking changes
