Repository SkriptLang/Skript, pull requests merged in 2023-03, with the labels that each got.

#5479 Fix Variables in Effect Commands
  src/main/java/ch/njol/skript/lang/Variable.java
Labels: enhancement

#5389 added event value and experience change event
  src/main/java/ch/njol/skript/events/EvtExperienceChange.java
  src/main/java/ch/njol/skript/expressions/ExprExperience.java
Labels: feature

#5371 Add Support for Entities/Chunks/Worlds/Blocks in CondIsWithin
  src/main/java/ch/njol/skript/conditions/CondIsInWorld.java
  src/main/java/ch/njol/skript/conditions/CondIsWithin.java
  src/main/java/ch/njol/skript/conditions/CondIsWithinLocation.java
  src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
Labels: enhancement, breaking changes

#4979 Adds back the JUnit testing system
  .github/workflows/junit-17-builds.yml
  .github/workflows/junit-8-builds.yml
  .gitignore
  build.gradle
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptAddon.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
  src/main/java/ch/njol/skript/test/platform/Environment.java
  src/main/java/ch/njol/skript/test/platform/PlatformMain.java
  src/main/java/ch/njol/skript/test/platform/package-info.java
  src/main/java/ch/njol/skript/test/runner/CondMethodExists.java
  src/main/java/ch/njol/skript/test/runner/CondMinecraftVersion.java
  src/main/java/ch/njol/skript/test/runner/EffAssert.java
  src/main/java/ch/njol/skript/test/runner/EffObjectives.java
  src/main/java/ch/njol/skript/test/runner/EvtTestCase.java
  src/main/java/ch/njol/skript/test/runner/ExprJUnitTest.java
  src/main/java/ch/njol/skript/test/runner/SkriptJUnitTest.java
  src/main/java/ch/njol/skript/test/runner/SkriptTestEvent.java
  src/main/java/ch/njol/skript/test/runner/TestFunctions.java
  src/main/java/ch/njol/skript/test/runner/TestMode.java
  src/main/java/ch/njol/skript/test/runner/TestTracker.java
  src/main/java/ch/njol/skript/test/runner/package-info.java
  src/main/java/ch/njol/skript/test/utils/TestResults.java
  src/main/java/ch/njol/skript/test/utils/package-info.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/test/java/ch/njol/skript/variables/FlatFileStorageTest.java
  src/test/java/org/skriptlang/skript/test/tests/aliases/AliasesTest.java
  src/test/java/org/skriptlang/skript/test/tests/aliases/package-info.java
  src/test/java/org/skriptlang/skript/test/tests/classes/ClassesTest.java
  src/test/java/org/skriptlang/skript/test/tests/classes/package-info.java
  src/test/java/org/skriptlang/skript/test/tests/config/NodeTest.java
  src/test/java/org/skriptlang/skript/test/tests/config/package-info.java
  src/test/java/org/skriptlang/skript/test/tests/localization/NounTest.java
  src/test/java/org/skriptlang/skript/test/tests/localization/UtilsPlurals.java
  src/test/java/org/skriptlang/skript/test/tests/localization/package-info.java
  src/test/java/org/skriptlang/skript/test/tests/regression/SimpleJUnitTest.java
  src/test/java/org/skriptlang/skript/test/tests/regression/package-info.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/package-info.java
  src/test/java/org/skriptlang/skript/test/tests/utils/UtilsTest.java
  src/test/java/org/skriptlang/skript/test/tests/utils/package-info.java
  src/test/skript/README.md
  src/test/skript/tests/junit/README.md
  src/test/skript/tests/junit/SimpleJUnitTest.sk
Labels: feature, unit testing, 2.7

#5437 Support .lang Skript Prefix
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/localization/Message.java
  src/main/resources/lang/english.lang
  src/main/resources/lang/french.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/japanese.lang
  src/main/resources/lang/korean.lang
  src/main/resources/lang/polish.lang
  src/main/resources/lang/simplifiedchinese.lang
Labels: enhancement

#5481 Add Translatable Tags
  src/main/java/ch/njol/skript/util/chat/BungeeConverter.java
  src/main/java/ch/njol/skript/util/chat/MessageComponent.java
  src/main/java/ch/njol/skript/util/chat/SkriptChatCode.java
  src/main/resources/lang/default.lang
Labels: enhancement

#5403 Converter and Comparator improvements
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/registrations/Comparators.java
  src/main/java/ch/njol/skript/registrations/Converters.java
  src/main/java/org/skriptlang/skript/lang/comparator/Comparators.java
  src/main/java/org/skriptlang/skript/lang/comparator/ConvertedComparator.java
  src/main/java/org/skriptlang/skript/lang/comparator/Relation.java
  src/main/java/org/skriptlang/skript/lang/converter/ChainedConverter.java
  src/main/java/org/skriptlang/skript/lang/converter/Converters.java
Labels: bug, enhancement, 2.7

#5508 Fix ExprAttacker not working in damage events
  src/main/java/ch/njol/skript/expressions/ExprAttacker.java
Labels: bug, 2.7

#5507 Fix Converter compatibility for Property Expressions
  src/main/java/ch/njol/skript/expressions/ExprChunk.java
  src/main/java/ch/njol/skript/expressions/ExprColoured.java
  src/main/java/ch/njol/skript/expressions/ExprGameMode.java
  src/main/java/ch/njol/skript/expressions/ExprLightLevel.java
  src/main/java/ch/njol/skript/expressions/ExprShooter.java
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
  src/main/java/ch/njol/skript/expressions/ExprVehicle.java
  src/main/java/ch/njol/skript/expressions/ExprWorld.java
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
  src/main/java/ch/njol/skript/expressions/base/SimplePropertyExpression.java
  src/main/java/ch/njol/skript/util/Getter.java
Labels: bug, 2.7

#5501 Disable JUnit in build
  build.gradle
Labels: bug, unit testing

#5511 Fix false negatives with some item comparisons
  src/main/java/ch/njol/skript/aliases/ItemData.java
Labels: bug, 2.7

#5299 Adds support for debugging and profiling
  build.gradle
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/test/platform/Environment.java
  src/main/java/ch/njol/skript/test/platform/PlatformMain.java
  src/main/java/ch/njol/skript/test/runner/TestMode.java
Labels: feature

#5496 Add default file junit tests
  src/test/java/org/skriptlang/skript/test/tests/files/FilesGenerate.java
  src/test/java/org/skriptlang/skript/test/tests/files/package-info.java
Labels: feature, unit testing

#5442 Adapt consistancy in dependabot.yml
  .github/dependabot.yml
Labels: bug, dependencies

#5513 Adds Explicit ItemStack Support to ExprItemAmount, fixing issue with item amount of variables.
  src/main/java/ch/njol/skript/expressions/ExprItemAmount.java
  src/test/skript/tests/regressions/551-item amount on itemstacks.sk
Labels: bug

#5523 🚀 Add Structure Support to Docs
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/java/ch/njol/skript/structures/StructFunction.java
  src/main/java/ch/njol/skript/structures/StructOptions.java
  src/main/java/ch/njol/skript/structures/StructVariables.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
Labels: enhancement, documentation

#5534 Revert currentEvents nullability changes
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
Labels: 2.7

#5535 Fix #5532
  build.gradle
Labels: bug, 2.7

#5529 Fix unrelated default variables
  src/main/java/ch/njol/skript/structures/StructVariables.java
  src/test/skript/tests/misc/default variables.sk
Labels: bug, 2.7

#5516 Fix Raw String of non-literal
  src/main/java/ch/njol/skript/expressions/ExprRawString.java
Labels: bug

#5527 Update to 1.19.4
  build.gradle
  gradle.properties
  src/main/java/ch/njol/skript/entity/BoatData.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/java/ch/njol/skript/util/visual/VisualEffects.java
  src/main/resources/lang/default.lang
  src/test/skript/environments/java17/paper-1.19.4.json
Labels: feature, 2.7

#5537 Add debug effect
  src/main/java/ch/njol/skript/test/runner/EffDebug.java
Labels: feature, unit testing

#5350 Fix a few script tests
  src/test/skript/tests/regressions/590-escaping quotes is required in some places it shouldn't be.sk
  src/test/skript/tests/syntaxes/effects/EffReplace.sk
  src/test/skript/tests/syntaxes/expressions/ExprArrowsStuck.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityAttribute.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityTamer.sk
  src/test/skript/tests/syntaxes/structures/StructCommand.sk
Labels: bug, unit testing

#5541 Gradle auto apply correct JDK version
  build.gradle
  settings.gradle
Labels: bug, feature

#5491 Fix EffDrop overwriting values of merged xp orbs.
  src/main/java/ch/njol/skript/bukkitutil/PlayerUtils.java
  src/main/java/ch/njol/skript/effects/EffDrop.java
  src/main/java/ch/njol/skript/entity/XpOrbData.java
  src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
  src/test/skript/tests/regressions/5491-xp orb merge overwrite.sk
  src/test/skript/tests/syntaxes/expressions/ExprTotalExperience.sk
Labels: bug, 2.7

#5411 Clean up variables package
  src/main/java/ch/njol/skript/variables/FlatFileStorage.java
  src/main/java/ch/njol/skript/variables/SerializedVariable.java
  src/main/java/ch/njol/skript/variables/Variables.java
  src/main/java/ch/njol/skript/variables/VariablesMap.java
  src/main/java/ch/njol/skript/variables/VariablesStorage.java
Labels: bug, enhancement, variables, 2.7

#5543 Fix profiler causing exception when building
  build.gradle
Labels: bug, 2.7

#5476 Fix Entity Changer
  src/main/java/ch/njol/skript/classes/data/DefaultChangers.java
Labels: bug, 2.7

#5548 Add missing .lang values for 1.19.4
  src/main/resources/lang/default.lang
Labels: bug, 2.7

#5509 Bump version to 2.7.0-beta2
  gradle.properties
  src/main/java/ch/njol/skript/expressions/ExprTotalExperience.java
  src/main/java/ch/njol/skript/test/runner/EffDebug.java
Labels: 2.7

#5455 Remove final on isSingle PropertyExpression
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
Labels: enhancement
