Repository SkriptLang/Skript, pull requests merged in 2023-07, with the labels that each got.

#5790 Fix null pointer exception in ExprBlocks when using the ExprDirection without a number defined.
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
Labels: bug

#5795 Fix ExprRawString using a Java 9 feature
  src/main/java/ch/njol/skript/expressions/ExprRawString.java
Labels: bug, 2.7

#5798 Fixes error not properly being caught
  src/main/java/ch/njol/skript/util/Utils.java
Labels: bug, priority: medium, 2.7

#5759 [2.7.0 target cherry pick] Fix the stop sound effect pattern
  src/main/java/ch/njol/skript/effects/EffStopSound.java
Labels: bug, 2.7

#5823 Allow on pickup to be found easier on docs
  src/main/java/ch/njol/skript/events/EvtItem.java
Labels: enhancement, documentation

#5816 Fix loot generate example
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: bug, documentation

#5356 Adds ExprPortalCooldown
  src/main/java/ch/njol/skript/expressions/ExprPortalCooldown.java
  src/test/skript/tests/syntaxes/expressions/ExprPortalCooldown.sk
Labels: feature

#5833 Fix EffActionBar NullPointException when message is null
  src/main/java/ch/njol/skript/effects/EffActionBar.java
Labels: bug, enhancement, 2.7

#5814 Update the return function regex
  src/main/java/ch/njol/skript/effects/EffReturn.java
  src/main/java/ch/njol/skript/structures/StructFunction.java
Labels: enhancement, needs testing

#5765 Catch the exception when pushing entity by non finite vector
  src/main/java/ch/njol/skript/effects/EffPush.java
Labels: bug

#5799 [2.7.0 target] Fix ExprRawString using a Java 9 feature
  src/main/java/ch/njol/skript/expressions/ExprRawString.java
Labels: bug, 2.7

#5748 Fix bugs in the random number expression
  src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
  src/test/skript/tests/regressions/pull-5748-fix bugs in the random number expression.sk
Labels: bug, 2.7

#5844 🛠 Fix ExprTarget UOE
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
Labels: bug, 2.7

#5856 [2.7.0 target] Fix ExprTarget UOE
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
Labels: bug, 2.7

#5853 [2.7.0 target] Fix bugs in the random number expression (#5748)
  src/main/java/ch/njol/skript/expressions/ExprRandomNumber.java
  src/test/skript/tests/regressions/pull-5748-fix bugs in the random number expression.sk
Labels: bug, 2.7

#5840 [2.7.0 target] Fix EffActionBar NullPointException when message is null
  src/main/java/ch/njol/skript/effects/EffActionBar.java
Labels: bug, enhancement, 2.7

#5813 Add warning to notify the user about using teleport in the spawn section
  src/main/java/ch/njol/skript/effects/EffTeleport.java
Labels: enhancement

#5808 Add proper error for BlockData failing
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/util/BlockUtils.java
Labels: enhancement

#5803 Delete CondIsWithinLocation in favor of CondIsWithin
  src/main/java/ch/njol/skript/conditions/CondIsWithinLocation.java
Labels: 2.7

#5793 [2.7.0 target] Fix null pointer exception in ExprBlocks when using the ExprDirection without a number defined
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
Labels: bug, 2.7

#5806 [2.7.0 target] Fixes error not properly being caught (#5798)
  src/main/java/ch/njol/skript/util/Utils.java
Labels: bug, 2.7

#5860 [2.7.0 target] delete cond is within location
  src/main/java/ch/njol/skript/conditions/CondIsWithinLocation.java
Labels: 2.7

#5807 Fix example in ExprTeleportCause
  src/main/java/ch/njol/skript/expressions/ExprTeleportCause.java
Labels: bug, documentation

#4198 🚀 Item cooldown expression + condition
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/conditions/CondHasItemCooldown.java
  src/main/java/ch/njol/skript/expressions/ExprItemCooldown.java
Labels: feature

#5662 New Expression: Loaded Chunks of World
  src/main/java/ch/njol/skript/expressions/ExprChunk.java
Labels: feature
