Repository SkriptLang/Skript, pull requests merged in 2024-01, with the labels that each got.

#6204 Add tests for effects
  build.gradle
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/effects/EffApplyBoneMeal.java
  src/main/java/ch/njol/skript/effects/EffSwingHand.java
  src/main/java/ch/njol/skript/test/runner/SkriptJUnitTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffActionBarTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffApplyBoneMealTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffFeedTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffMakeFlyTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffOpTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffSwingHandTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtGrowTest.java
  src/test/skript/junit/EvtGrow.sk
  src/test/skript/tests/syntaxes/effects/EffDoIf.sk
  src/test/skript/tests/syntaxes/effects/EffPvP.sk
Labels: enhancement, 2.8, feature-ready

#6180 Re-enable the vector from location syntax
  src/main/java/ch/njol/skript/expressions/ExprLocationFromVector.java
  src/test/skript/tests/syntaxes/expressions/ExprLocationFromVector.sk
Labels: enhancement, 2.8, feature-ready

#6157 Fix ExprTarget not accounting for Spigot servers and add ignore blocks
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
Labels: bug, 2.8, feature-ready

#6122 Make the multiple event-values less strict
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug, 2.8, feature-ready

#5875 🛠 Change player parsing to use `name starting with`
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: enhancement, breaking changes, 2.8, feature-ready

#5800 Entity transform events
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtEntityTransform.java
  src/main/java/ch/njol/skript/expressions/ExprTransformReason.java
  src/main/resources/lang/default.lang
Labels: feature, 2.8, feature-ready

#5744 Cleanup EnumUtils
  src/main/java/ch/njol/skript/util/EnumUtils.java
Labels: enhancement, 2.8, feature-ready

#5406 Fix ExprDifference issues
  src/main/java/ch/njol/skript/expressions/ExprDifference.java
  src/test/skript/tests/syntaxes/expressions/ExprDifference.sk
Labels: bug, 2.8, feature-ready

#6271 Add warnings for using %player% without using the UUID config setting.
  src/main/java/ch/njol/skript/lang/VariableString.java
Labels: enhancement, 2.8, feature-ready

#5948 Add ExprSentCommands and EvtPlayerCommandSend
  src/main/java/ch/njol/skript/events/EvtPlayerCommandSend.java
  src/main/java/ch/njol/skript/expressions/ExprSentCommands.java
Labels: feature, 2.8, feature-ready

#5098 Repeat Expression
  src/main/java/ch/njol/skript/expressions/ExprRepeat.java
  src/test/skript/tests/syntaxes/expressions/ExprRepeat.sk
Labels: feature, 2.8, feature-ready

#6198 Turkish Translation
  src/main/resources/config.sk
  src/main/resources/lang/turkish.lang
Labels: feature, 2.8, feature-ready

#6000 Cleanup lang
  .git-blame-ignore-revs
  code-conventions.md
  src/main/java/ch/njol/skript/classes/ClassInfo.java
  src/main/java/ch/njol/skript/classes/Converter.java
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/events/EvtGrow.java
  src/main/java/ch/njol/skript/expressions/ExprItems.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
  src/main/java/ch/njol/skript/expressions/base/SimplePropertyExpression.java
  src/main/java/ch/njol/skript/expressions/base/WrapperExpression.java
  src/main/java/ch/njol/skript/lang/Condition.java
  src/main/java/ch/njol/skript/lang/Debuggable.java
  src/main/java/ch/njol/skript/lang/DefaultExpression.java
  src/main/java/ch/njol/skript/lang/Effect.java
  src/main/java/ch/njol/skript/lang/EffectSection.java
  src/main/java/ch/njol/skript/lang/EffectSectionEffect.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/ExpressionInfo.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/main/java/ch/njol/skript/lang/Literal.java
  src/main/java/ch/njol/skript/lang/LiteralList.java
  src/main/java/ch/njol/skript/lang/ParseContext.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/SectionSkriptEvent.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/Statement.java
  src/main/java/ch/njol/skript/lang/SyntaxElement.java
  src/main/java/ch/njol/skript/lang/SyntaxElementInfo.java
  src/main/java/ch/njol/skript/lang/Trigger.java
  src/main/java/ch/njol/skript/lang/TriggerItem.java
  src/main/java/ch/njol/skript/lang/TriggerSection.java
  src/main/java/ch/njol/skript/lang/Unit.java
  src/main/java/ch/njol/skript/lang/UnparsedLiteral.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/main/java/ch/njol/skript/lang/util/ContainerExpression.java
  src/main/java/ch/njol/skript/lang/util/ConvertedExpression.java
  src/main/java/ch/njol/skript/lang/util/ConvertedLiteral.java
  src/main/java/ch/njol/skript/lang/util/SimpleEvent.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
  src/main/java/ch/njol/skript/lang/util/SimpleLiteral.java
  src/main/java/ch/njol/skript/structures/StructCommand.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
Labels: enhancement, breaking changes, 2.8, feature-ready

#6249 Optimize CommandHelp instantiation to prevent misleading errors
  src/main/java/ch/njol/skript/command/CommandHelp.java
Labels: bug, patch-ready

#5114 Update to world events
  src/main/java/ch/njol/skript/effects/EffWorldLoad.java
  src/main/java/ch/njol/skript/effects/EffWorldSave.java
  src/main/java/ch/njol/skript/events/EvtWorld.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: enhancement, feature, 2.8

#4281 Rewrite ExprFurnaceSlot
  src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
  src/test/skript/tests/syntaxes/expressions/ExprFurnaceSlot.sk
Labels: bug, feature, breaking changes, 2.8

#6101 Copy Effect
  src/main/java/ch/njol/skript/effects/EffCopy.java
  src/test/skript/tests/syntaxes/effects/EffCopy.sk
Labels: enhancement, 2.8, hacktoberfest-accepted

#5478 Improve ExprElement
  src/main/java/ch/njol/skript/expressions/ExprElement.java
  src/main/java/ch/njol/util/coll/CollectionUtils.java
  src/test/skript/tests/syntaxes/expressions/ExprElement.sk
Labels: bug, enhancement, 2.8

#6286 Fix Command Parsing
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/syntaxes/structures/StructCommand.sk
Labels: bug, 2.8, patch-ready

#6287 Fix Erroneous Player UUID Warnings
  src/main/java/ch/njol/skript/lang/VariableString.java
Labels: bug, 2.8, patch-ready

#6292 Fix event data pollution for event priority
  src/main/java/ch/njol/skript/structures/StructEvent.java
  src/test/skript/tests/regressions/6288-event data priority pollution.sk
Labels: bug, 2.8

#6294 Fixes IllegalArgumentException when trying to get shoes of entity
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/test/skript/tests/regressions/6237-equip slot shoes exception.sk
Labels: bug, 2.8, patch-ready

#6298 Fixes outdated website link
  src/main/resources/plugin.yml
Labels: bug, 2.8, patch-ready

#6310 Force "to location" in ExprLocationFromVector
  src/main/java/ch/njol/skript/expressions/ExprLocationFromVector.java
Labels: bug, 2.8, patch-ready

#6312 Fix ReleaseChannel Logic
  build.gradle
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/resources/config.sk
Labels: bug, 2.8, feature-ready

#6317 Fix "parsed as a player" Not Working
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: bug, 2.8, patch-ready

#6323 Fix conflict between ExprItemsIn and ExprInventory
  src/main/java/ch/njol/skript/expressions/ExprInventory.java
  src/test/skript/tests/regressions/6290-item-inventory-conflict.sk
Labels: bug, 2.8, patch-ready

#6325 Try to fix archive docs
  .github/workflows/release-docs.yml
Labels: documentation, 2.8, github related

#6357 🚀 Allow `armour` in armor change event
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: enhancement

#6356 ⚒️ Fix isSingle of ExprArmorSlot
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
Labels: bug, 2.8, patch-ready
