Repository SkriptLang/Skript, pull requests merged in 2024-10, with the labels that each got.

#7031 Fix Message when reloading multiple scripts with an error.
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/resources/lang/english.lang
  src/main/resources/lang/french.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/japanese.lang
  src/main/resources/lang/korean.lang
  src/main/resources/lang/polish.lang
  src/main/resources/lang/russian.lang
  src/main/resources/lang/simplifiedchinese.lang
  src/main/resources/lang/turkish.lang
Labels: bug, patch-ready, 2.9

#7058 Nicer description for EffSort.
  src/main/java/ch/njol/skript/effects/EffSort.java
Labels: enhancement, feature-ready, 2.9

#7091 Preventing NPE caused by creation of PlayerProfile from OfflinePlayer
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/expressions/ExprSkull.java
  src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
Labels: bug, patch-ready, 2.9

#7095 Disallow delay within the testing system
  src/main/java/ch/njol/skript/test/runner/EffAssert.java
  src/test/skript/tests/syntaxes/expressions/ExprEntities.sk
Labels: enhancement, patch-ready

#7066 Update EffCancelEvent
  src/main/java/ch/njol/skript/effects/EffCancelEvent.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffCancelEventTest.java
  src/test/skript/junit/EffCancelEvent.sk
  src/test/skript/tests/regressions/7054-update event cancelling.sk
Labels: enhancement, patch-ready

#7121 Shouldn't check length of Material
  src/main/java/ch/njol/skript/bukkitutil/BukkitUnsafe.java
Labels: bug, patch-ready

#7124 Fixes 5804-is-burning regression test
  src/test/skript/tests/regressions/5804-is-burning.sk
Labels: bug, feature-ready

#7125 Fixes missing and/or warnings
  src/test/skript/tests/syntaxes/expressions/ExprJoinSplit.sk
  src/test/skript/tests/syntaxes/sections/SecFilter.sk
Labels: enhancement, feature-ready

#5552 Internal Events API
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/events/bukkit/PreScriptLoadEvent.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/org/skriptlang/skript/lang/script/Script.java
  src/main/java/org/skriptlang/skript/lang/script/ScriptEvent.java
  src/main/java/org/skriptlang/skript/util/event/Event.java
  src/main/java/org/skriptlang/skript/util/event/EventRegistry.java
Labels: feature, breaking changes, feature-ready

#6741 Added gamemode to CondIsInvulnerable.java
  src/main/java/ch/njol/skript/conditions/CondIsInvulnerable.java
  src/test/skript/tests/syntaxes/conditions/CondIsInvulnerable.sk
Labels: enhancement, feature-ready

#6851 Variable Backup Files Purger
  src/main/java/ch/njol/skript/util/FileUtils.java
  src/main/java/ch/njol/skript/variables/VariablesStorage.java
  src/main/resources/config.sk
  src/test/java/org/skriptlang/skript/test/tests/files/BackupPurgeTest.java
Labels: feature, feature-ready

#6859 Adds some command block syntax
  src/main/java/ch/njol/skript/conditions/CondIsCommandBlockConditional.java
  src/main/java/ch/njol/skript/effects/EffCommandBlockConditional.java
  src/main/java/ch/njol/skript/expressions/ExprCommandBlockCommand.java
  src/test/skript/tests/syntaxes/conditions/CondIsConditional.sk
  src/test/skript/tests/syntaxes/expressions/ExprCommandBlockCommand.sk
Labels: feature, feature-ready

#6861 Adds domestication syntax
  src/main/java/ch/njol/skript/expressions/ExprDomestication.java
  src/test/skript/tests/syntaxes/expressions/ExprDomestication.sk
Labels: feature, feature-ready

#6203 Add "Time Until" to ExprTimeSince and Add CondPastFuture
  src/main/java/ch/njol/skript/conditions/CondPastFuture.java
  src/main/java/ch/njol/skript/expressions/ExprTimeSince.java
  src/test/skript/tests/syntaxes/conditions/CondPastFuture.sk
  src/test/skript/tests/syntaxes/expressions/ExprTimeSince.sk
Labels: enhancement, feature, breaking changes, feature-ready

#6900 Add cuboid syntax to ExprEntities
  src/main/java/ch/njol/skript/expressions/ExprEntities.java
  src/test/skript/tests/syntaxes/expressions/ExprEntities.sk
Labels: enhancement, feature-ready

#6958 Warning when reloading Skript.
  src/main/java/ch/njol/skript/Skript.java
  src/main/resources/lang/english.lang
Labels: enhancement, feature-ready

#6960 Unreachable Code
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/effects/EffContinue.java
  src/main/java/ch/njol/skript/effects/EffExit.java
  src/main/java/ch/njol/skript/effects/EffReturn.java
  src/main/java/ch/njol/skript/effects/EffSuppressWarnings.java
  src/main/java/ch/njol/skript/lang/ExecutionIntent.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/main/java/ch/njol/skript/lang/TriggerItem.java
  src/main/java/ch/njol/skript/lang/TriggerSection.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/sections/SecConditional.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/main/java/ch/njol/skript/sections/SecWhile.java
  src/main/java/org/skriptlang/skript/lang/script/ScriptWarning.java
  src/main/resources/config.sk
  src/test/skript/tests/syntaxes/effects/EffContinue.sk
Labels: bug, enhancement, feature-ready, 2.10

#6970 ExprPrefixSuffix Cleanup
  src/main/java/ch/njol/skript/hooks/chat/expressions/ExprPrefixSuffix.java
Labels: enhancement, feature-ready, 2.10

#6989 Connect Changes.
  src/main/java/ch/njol/skript/effects/EffConnect.java
Labels: enhancement, feature-ready

#7001 Shortened Timespans (again)
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/util/Timespan.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/misc/timespans.sk
Labels: enhancement, feature-ready

#7013 Updates EffCharge and CondIsCharged
  src/main/java/ch/njol/skript/conditions/CondIsCharged.java
  src/main/java/ch/njol/skript/effects/EffCharge.java
  src/test/skript/tests/syntaxes/conditions/CondIsCharged.sk
Labels: feature, feature-ready

#7019 Adds entity sound expression and test
  src/main/java/ch/njol/skript/expressions/ExprEntitySound.java
  src/main/java/ch/njol/skript/util/Patterns.java
  src/test/skript/tests/syntaxes/expressions/ExprEntitySound.sk
Labels: feature, feature-ready

#7030 Add underscore formatting in numbers
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
  src/test/skript/tests/misc/underscores in numbers.sk
Labels: enhancement, feature-ready

#7040 Adds block sound expression and test
  src/main/java/ch/njol/skript/expressions/ExprBlockSound.java
  src/test/skript/tests/syntaxes/expressions/ExprBlockSound.sk
Labels: feature, feature-ready

#7041 Wolf Variants
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/entity/WolfData.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/effects/EffSpawn.sk
Labels: enhancement, feature-ready

#7043 Adds PropertyExpression helper method
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
  src/main/java/ch/njol/skript/expressions/base/SimplePropertyExpression.java
Labels: enhancement, feature-ready

#7045 Adds last death location expression and JUnit test
  src/main/java/ch/njol/skript/expressions/ExprLastDeathLocation.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprLastDeathLocationTest.java
Labels: enhancement, feature, feature-ready

#7046 Piglin Barter Fix
  src/test/skript/junit/EvtPiglinBarter.sk
  src/test/skript/junit/EvtPiglinBarterTest.sk
Labels: bug, feature-ready

#7053 Add async JUnit tests, on broadcast event and hover list test
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprMessage.java
  src/main/java/ch/njol/skript/test/runner/SkriptAsyncJUnitTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtBroadcastTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprHoverListTest.java
  src/test/skript/junit/EvtBroadcast.sk
  src/test/skript/junit/ExprHoverList.sk
Labels: feature, unit testing, feature-ready

#7073 Auto Generate Missing Aliases
  src/main/java/ch/njol/skript/util/EnumUtils.java
Labels: enhancement, feature-ready

#7075 BlockDropItemEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtBlock.java
  src/main/java/ch/njol/skript/expressions/ExprDrops.java
Labels: enhancement, feature-ready

#7055 Boats+
  src/main/java/ch/njol/skript/entity/BoatChestData.java
  src/main/java/ch/njol/skript/entity/BoatData.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/effects/EffSpawn.sk
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: enhancement, feature-ready

#7094 Eff + Cond Lidded
  src/main/java/ch/njol/skript/conditions/CondLidState.java
  src/main/java/ch/njol/skript/effects/EffLidState.java
  src/test/skript/tests/syntaxes/effects/EffLidStates.sk
Labels: enhancement, feature-ready

#7097 Add supplier to EnumClassInfo
  src/main/java/ch/njol/skript/classes/ClassInfo.java
  src/main/java/ch/njol/skript/classes/EnumClassInfo.java
  src/main/java/ch/njol/skript/util/EnumUtils.java
Labels: enhancement, feature-ready

#7106 Avoid sending update message on join when testing
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement, feature-ready

#6867 Rework entity visibility
  src/main/java/ch/njol/skript/conditions/CondCanSee.java
  src/main/java/ch/njol/skript/effects/EffEntityVisibility.java
  src/main/java/ch/njol/skript/effects/EffPlayerVisibility.java
  src/main/java/ch/njol/skript/expressions/ExprHiddenPlayers.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/conditions/CondCanSeeTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffEntityVisibilityTest.java
Labels: enhancement, feature-ready

#6898 Add Detonate effect
  src/main/java/ch/njol/skript/effects/EffDetonate.java
  src/test/skript/tests/syntaxes/effects/EffDetonate.sk
Labels: feature, feature-ready

#7145 remove eclipse annotations in display rotation packageinfo
  build.gradle
  src/main/java/org/skriptlang/skript/bukkit/misc/rotation/package-info.java
Labels: bug, feature-ready

#7147 Fix unformatted Skript system messages
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/log/LogEntry.java
Labels: bug, feature-ready

#7142 Add some test expressions
  src/main/java/ch/njol/skript/test/runner/EvtTestCase.java
  src/main/java/ch/njol/skript/test/runner/ExprTestBlock.java
  src/main/java/ch/njol/skript/test/runner/ExprTestLocation.java
  src/main/java/ch/njol/skript/test/runner/ExprTestWorld.java
  src/test/skript/tests/misc/2584-HealthUtils - update.sk
  src/test/skript/tests/misc/default variables.sk
  src/test/skript/tests/misc/test expressions.sk
  src/test/skript/tests/regressions/3253-entitydata fixes.sk
  src/test/skript/tests/regressions/3281-itemamount fixes.sk
  src/test/skript/tests/regressions/3284-itemcrack particle.sk
  src/test/skript/tests/regressions/3303-item durability.sk
  src/test/skript/tests/regressions/3314-chunk is loaded.sk
  src/test/skript/tests/regressions/3419-item comparisons.sk
  src/test/skript/tests/regressions/4773-composter-the-imposter.sk
  src/test/skript/tests/regressions/5491-xp orb merge overwrite.sk
  src/test/skript/tests/regressions/551-item amount on itemstacks.sk
  src/test/skript/tests/regressions/5804-is-burning.sk
  src/test/skript/tests/regressions/6032-local-vars-created-in-effsecspawn.sk
  src/test/skript/tests/regressions/6424-inventory-holder-location.sk
  src/test/skript/tests/regressions/6612-nearest entity cast error.sk
  src/test/skript/tests/regressions/6623-wrong parsing order for math.sk
  src/test/skript/tests/regressions/6707-spawn-fish-types.sk
  src/test/skript/tests/regressions/6762-cant spawn a firework.sk
  src/test/skript/tests/regressions/6811-inventory-holder-location-doublechest.sk
  src/test/skript/tests/regressions/6907-playsound entity method doesn't exist.sk
  src/test/skript/tests/regressions/pull-5566-block iterator being 100 always.sk
  src/test/skript/tests/regressions/pull-6746-spawn-dropped-item.sk
  src/test/skript/tests/regressions/pull-7024-efflook-stack-trace
  src/test/skript/tests/syntaxes/conditions/CondHasLineOfSight.sk
  src/test/skript/tests/syntaxes/conditions/CondIsTamed.sk
  src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
  src/test/skript/tests/syntaxes/effects/EffExplodeCreeper.sk
  src/test/skript/tests/syntaxes/effects/EffExplodeWithFire.sk
  src/test/skript/tests/syntaxes/effects/EffHandedness.sk
  src/test/skript/tests/syntaxes/effects/EffInvisible.sk
  src/test/skript/tests/syntaxes/effects/EffPotion.sk
  src/test/skript/tests/syntaxes/effects/EffVisualEffect.sk
  src/test/skript/tests/syntaxes/expressions/ExprArmorSlot.sk
  src/test/skript/tests/syntaxes/expressions/ExprArrowsStuck.sk
  src/test/skript/tests/syntaxes/expressions/ExprBlockData.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityAttribute.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityTamer.sk
  src/test/skript/tests/syntaxes/expressions/ExprExplosiveYield.sk
  src/test/skript/tests/syntaxes/expressions/ExprFreezeTicks.sk
  src/test/skript/tests/syntaxes/expressions/ExprFurnaceSlot.sk
  src/test/skript/tests/syntaxes/expressions/ExprLocationVectorOffset.sk
  src/test/skript/tests/syntaxes/expressions/ExprNearestEntity.sk
  src/test/skript/tests/syntaxes/expressions/ExprPortalCooldown.sk
  src/test/skript/tests/syntaxes/expressions/ExprPotionEffects.sk
  src/test/skript/tests/syntaxes/expressions/ExprRemainingAir.sk
  src/test/skript/tests/syntaxes/expressions/ExprSpawnerType.sk
  src/test/skript/tests/syntaxes/expressions/ExprTotalExperience.sk
  src/test/skript/tests/syntaxes/expressions/ExprYawPitch.sk
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: enhancement, unit testing, feature-ready

#7104 Adds a condition for is divisible by
  src/main/java/ch/njol/skript/conditions/CondIsDivisibleBy.java
  src/test/skript/tests/syntaxes/conditions/CondIsDivisibleBy.sk
Labels: feature, feature-ready

#7076 PlayerExpCooldown
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprExperienceCooldown.java
  src/main/java/ch/njol/skript/expressions/ExprExperienceCooldownChangeReason.java
  src/main/resources/lang/default.lang
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtExperienceCooldownChangeTest.java
  src/test/skript/junit/EvtExperienceCooldownChangeTest.sk
Labels: enhancement, feature-ready

#7166 Add number format function
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/test/skript/tests/regressions/7166-formatted numbers.sk
Labels: feature, feature-ready

#7143 Make KeyValueEntryData validation not case-sensitive
  src/main/java/org/skriptlang/skript/lang/entry/KeyValueEntryData.java
Labels: bug, enhancement, patch-ready

#7141 Fix leather horse armor being unequipable
  src/main/java/ch/njol/skript/effects/EffEquip.java
  src/test/skript/tests/regressions/7140-leather horse armor unequipable.sk
Labels: bug, patch-ready

#7130 On Click BlockData
  src/main/java/ch/njol/skript/events/EvtClick.java
Labels: enhancement, feature-ready

#7115 Remove delay in tests
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement, unit testing, feature-ready

#7113 Implement ADD and REMOVE changers to ExprMetadata
  src/main/java/ch/njol/skript/expressions/ExprMetadata.java
  src/test/skript/tests/syntaxes/expressions/ExprMetadata.sk
Labels: enhancement, feature-ready

#7110 Add breeding
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/expressions/ExprExperience.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/BreedingModule.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondCanAge.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondCanBreed.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondIsAdult.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondIsBaby.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondIsInLove.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/EffAllowAging.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/EffBreedable.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/EffMakeAdultOrBaby.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/EvtBreed.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/ExprBreedingFamily.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/ExprLoveTime.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtBreedTest.java
  src/test/skript/junit/EvtBreed.sk
  src/test/skript/tests/syntaxes/conditions/CondIsInLove.sk
  src/test/skript/tests/syntaxes/effects/EffAllowAging.sk
  src/test/skript/tests/syntaxes/effects/EffBreedable.sk
  src/test/skript/tests/syntaxes/effects/EffMakeAdultOrBaby.sk
  src/test/skript/tests/syntaxes/expressions/ExprLoveTime.sk
Labels: feature, feature-ready

#7105 Add chat client options
  src/main/java/ch/njol/skript/conditions/CondChatColors.java
  src/main/java/ch/njol/skript/conditions/CondChatFiltering.java
  src/main/java/ch/njol/skript/conditions/CondChatVisibility.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/conditions/CondChatVisibilityTest.java
  src/test/skript/junit/CondChatVisibility.sk
Labels: feature, feature-ready
