Repository SkriptLang/Skript, pull requests merged in 2024-07, with the labels that each got.

#6836 fix exception when removing air from slot
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/test/skript/tests/regressions/6830-remove air from slot.sk
Labels: bug, patch-ready, 2.9

#6835 EffBan - add option to kick
  src/main/java/ch/njol/skript/effects/EffBan.java
Labels: enhancement, feature-ready, 2.9

#6829 BlockData - add cloner
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/test/java/org/skriptlang/skript/test/tests/regression/BlockDataNotCloned6829.java
Labels: bug, patch-ready, 2.9

#6791 default.lang - add MC 1.21 attributes
  src/main/resources/lang/default.lang
Labels: enhancement, patch-ready, 2.9

#6832 Add potion effect type comparator
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/test/skript/tests/regressions/pull-6832-potioneffecttype-compare.sk
Labels: bug, feature-ready, 2.9

#6797 ExprLastDamage - fix everything
  src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java
  src/main/java/ch/njol/skript/expressions/ExprLastDamage.java
  src/test/skript/tests/syntaxes/expressions/ExprLastDamage.sk
Labels: bug, patch-ready, 2.9

#6828 Add delete changer to ExprMessage
  src/main/java/ch/njol/skript/expressions/ExprMessage.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprDropsTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprMessageTest.java
  src/test/skript/junit/ExprDrops.sk
  src/test/skript/junit/ExprMessage.sk
Labels: enhancement, feature-ready, 2.9

#6823 Added holder instanceof DoubleChest check to converter
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/test/skript/tests/regressions/6811-inventory-holder-location-doublechest.sk
Labels: bug, patch-ready, 2.9

#6806 Registry - more registries
  src/main/java/ch/njol/skript/bukkitutil/BukkitUtils.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/resources/lang/default.lang
Labels: enhancement, feature-ready, 2.9

#6805 Fix/registry pr whoops
  src/main/java/ch/njol/skript/classes/registry/RegistrySerializer.java
Labels: enhancement, feature-ready, 2.9

#6733 Improve new line pattern.
  src/main/java/ch/njol/skript/expressions/LitNewLine.java
Labels: enhancement, breaking changes, feature-ready, 2.9

#6164 Add tests for item syntaxes.
  src/test/skript/tests/syntaxes/expressions/ExprAmountOfItems.sk
  src/test/skript/tests/syntaxes/expressions/ExprItemWithCustomModelData.sk
  src/test/skript/tests/syntaxes/expressions/ExprItemsIn.sk
Labels: patch-ready, adds-missing-test, 2.9

#6680 Add config toggle for whether to listen to cancelled events by default.
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/resources/config.sk
Labels: enhancement, feature-ready, 2.9

#6583 Change comment parsing
  src/main/java/ch/njol/skript/config/Node.java
  src/main/java/ch/njol/skript/expressions/ExprChestInventory.java
  src/main/java/ch/njol/skript/expressions/ExprLoopIteration.java
  src/main/java/ch/njol/skript/expressions/ExprLoopValue.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/main/resources/config.sk
  src/main/resources/scripts/-examples/text formatting.sk
  src/test/java/org/skriptlang/skript/test/tests/config/NodeTest.java
  src/test/skript/tests/misc/comments.sk
  src/test/skript/tests/regressions/4235-floating point errors rounding functions.sk
  src/test/skript/tests/regressions/4664-formatted time.sk
  src/test/skript/tests/regressions/4769-fire-visualeffect.sk
  src/test/skript/tests/regressions/535-math is done in the wrong order.sk
  src/test/skript/tests/regressions/590-escaping quotes is required in some places it shouldn't be.sk
  src/test/skript/tests/regressions/837-getting a uuid of a var inside code.sk
  src/test/skript/tests/syntaxes/conditions/CondContains.sk
  src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
  src/test/skript/tests/syntaxes/conditions/CondMethodExists.sk
  src/test/skript/tests/syntaxes/effects/EffContinue.sk
  src/test/skript/tests/syntaxes/effects/EffHealth.sk
  src/test/skript/tests/syntaxes/expressions/ExprArrowsStuck.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityAttribute.sk
  src/test/skript/tests/syntaxes/expressions/ExprFreezeTicks.sk
  src/test/skript/tests/syntaxes/expressions/ExprItemsIn.sk
  src/test/skript/tests/syntaxes/expressions/ExprNoDamageTicks.sk
  src/test/skript/tests/syntaxes/expressions/ExprPortalCooldown.sk
  src/test/skript/tests/syntaxes/functions/caseEquals.sk
  src/test/skript/tests/syntaxes/sections/SecConditional.sk
Labels: enhancement, needs testing, breaking changes, require docs update, feature-ready, 2.9

#6798 1.21 Support
  build.gradle
  gradle.properties
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/bukkitutil/block/BlockCompat.java
  src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/test/skript/environments/java21/paper-1.21.0.json
  src/test/skript/tests/regressions/5491-xp orb merge overwrite.sk
  src/test/skript/tests/syntaxes/effects/EffGlowingText.sk
Labels: bug, needs testing, patch-ready, 2.9

#6611 Attempt to estimate world in teleport when it's not specified.
  src/main/java/ch/njol/skript/effects/EffTeleport.java
Labels: bug, 2.9

#6737 Add EffSort, rework ExprInput to use ParserData
  src/main/java/ch/njol/skript/effects/EffSort.java
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
  src/main/java/ch/njol/skript/expressions/ExprInput.java
  src/main/java/ch/njol/skript/lang/InputSource.java
  src/test/skript/tests/syntaxes/effects/EffSort.sk
  src/test/skript/tests/syntaxes/expressions/ExprFilter.sk
Labels: enhancement, feature, feature-ready, 2.9

#5298 ExprYawPitch: support for entities, better description
  src/main/java/ch/njol/skript/expressions/ExprYawPitch.java
Labels: enhancement, feature-ready, 2.9

#5691 🚀 Add Cancellable section
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
Labels: feature, documentation, feature-ready, 2.9

#5979 Make EffBroadcast calls BroadcastMessageEvent
  src/main/java/ch/njol/skript/effects/EffBroadcast.java
Labels: enhancement, feature-ready

#6276 Fixes JUnit before and after being called on cleanup regardless of override
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/test/runner/SkriptJUnitTest.java
Labels: enhancement, feature-ready, 2.9

#6339 Update healing event and related expressions
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtHealing.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprHealAmount.java
  src/main/java/ch/njol/skript/expressions/ExprHealReason.java
Labels: enhancement, feature-ready, 2.9

#6844 RegistryParser - strip out minecraft namespaces from docs
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/registry/RegistryParser.java
Labels: enhancement, documentation, 2.9

#6712 Adds tooltip syntax
  src/main/java/ch/njol/skript/conditions/CondTooltip.java
  src/main/java/ch/njol/skript/effects/EffTooltip.java
  src/test/skript/tests/syntaxes/conditions/CondTooltip.sk
Labels: feature, feature-ready, 2.9

#6834 Exposes 'load default aliases' config option and removes hardcoded alias dependencies
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/effects/EffEquip.java
  src/main/java/ch/njol/skript/effects/EffOpenBook.java
  src/main/java/ch/njol/skript/entity/BoatChestData.java
  src/main/java/ch/njol/skript/entity/BoatData.java
  src/main/java/ch/njol/skript/entity/ThrownPotionData.java
  src/main/java/ch/njol/skript/events/EvtMoveOn.java
  src/main/java/ch/njol/skript/events/EvtPressurePlate.java
  src/main/java/ch/njol/skript/expressions/ExprBurnCookTime.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/main/java/ch/njol/skript/expressions/ExprSignText.java
  src/main/java/ch/njol/skript/expressions/ExprSkull.java
  src/main/java/ch/njol/skript/expressions/ExprSpawnerType.java
  src/main/resources/config.sk
Labels: bug, enhancement, feature-ready, 2.9

#6845 Fix current section update issues
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/TriggerSection.java
  src/test/skript/tests/regressions/6843-current section reference issue.sk
Labels: bug, 2.9

#6659 Support for LogLevel in EffLog
  src/main/java/ch/njol/skript/effects/EffLog.java
Labels: enhancement, feature-ready, 2.9

#6831 add allowLookups option to offlineplayer function
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/test/skript/tests/syntaxes/functions/offlinePlayer.sk
Labels: enhancement, feature-ready, 2.9

#6687 EnchantmentType - prepare for MC 1.21 custom enchantments
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/main/java/ch/njol/skript/bukkitutil/EnchantmentUtils.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/util/EnchantmentType.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/regressions/pull-6687-enchantment-update.sk
Labels: enhancement, feature-ready, 2.9

#6694 More Keyword Tweaks
  src/main/java/ch/njol/skript/patterns/Keyword.java
Labels: enhancement, feature-ready, 2.9

#6131 Sound seeds and entity sound emitters
  src/main/java/ch/njol/skript/bukkitutil/AdventureSoundReceiver.java
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
Labels: enhancement, feature-ready, 2.9

#5284 Add lowest solid block
  src/main/java/ch/njol/skript/expressions/ExprHighestSolidBlock.java
  src/main/java/ch/njol/skript/expressions/ExprLowestHighestSolidBlock.java
  src/test/skript/tests/syntaxes/expressions/ExprLowestHighestSolidBlock.sk
Labels: feature, breaking changes, feature-ready, 2.9

#6803 ExprDurability/ExprMaxDurability - account for custom durability
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/expressions/ExprDurability.java
  src/main/java/ch/njol/skript/expressions/ExprMaxDurability.java
  src/test/skript/tests/syntaxes/expressions/ExprDurability.sk
  src/test/skript/tests/syntaxes/expressions/ExprMaxDurability.sk
Labels: enhancement, feature-ready, 2.9

#6530 Added Entity Teleport event.
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtTeleport.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: feature, breaking changes, feature-ready, 2.9

#5698 Expression Skull Owner
  src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
Labels: feature, feature-ready, 2.9

#6718 String literal.
  src/main/java/ch/njol/skript/lang/LiteralString.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/main/java/ch/njol/skript/test/runner/ExprTestStringLiteral.java
  src/test/skript/tests/misc/string literals.sk
Labels: enhancement, feature-ready, 2.9

#6870 ItemUtils - fix error when setting damage lower than 0
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/test/skript/tests/syntaxes/expressions/ExprDurability.sk
Labels: bug, 2.9

#6871 EnchantmentType - fix toString showing namespacedkeys
  src/main/java/ch/njol/skript/util/EnchantmentType.java
Labels: bug, 2.9

#6876 Fix Incorrect BlockValues#isDefault
  src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
Labels: bug, patch-ready, 2.9

#6848 Fix archive docs requiring release-docs job
  .github/workflows/archive-docs.yml
Labels: bug, 2.9

#6874 Fix ExprName InventoryView IncompatibleClassChangeError
  src/main/java/ch/njol/skript/bukkitutil/InventoryUtils.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/main/java/ch/njol/skript/expressions/ExprOpenedInventory.java
Labels: bug, 2.9

#6886 ItemType Random Safety Improvements
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/conditions/CondIsPreferredTool.java
  src/main/java/ch/njol/skript/effects/EffOpenBook.java
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/main/java/ch/njol/skript/entity/BoatChestData.java
  src/main/java/ch/njol/skript/entity/BoatData.java
  src/main/java/ch/njol/skript/entity/DroppedItemData.java
  src/main/java/ch/njol/skript/expressions/ExprMaxStack.java
  src/main/java/ch/njol/skript/expressions/ExprPlain.java
  src/main/java/ch/njol/skript/util/visual/VisualEffects.java
  src/test/java/org/skriptlang/skript/test/tests/regression/ExprPlainAliasTest.java
Labels: bug, 2.9

#6846 Fix index of player's tool
  src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
Labels: bug, 2.9

#6888 Fix ItemData#equals check
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/test/skript/tests/syntaxes/effects/EffEquip.sk
Labels: bug, 2.9

#6895 Add Missing 1.21 Lang Entries
  src/main/resources/lang/default.lang
Labels: enhancement, feature-ready, 2.9

#6894 Improve ReturnHandler#returnValues method
  src/main/java/ch/njol/skript/effects/EffReturn.java
  src/main/java/ch/njol/skript/lang/ReturnHandler.java
  src/main/java/ch/njol/skript/lang/ReturnableTrigger.java
  src/main/java/ch/njol/skript/lang/function/ScriptFunction.java
  src/main/java/ch/njol/skript/test/runner/SecReturnable.java
Labels: enhancement, feature-ready, 2.9

#6903 Prepare For Release (2.9.0)
  gradle.properties
  src/main/java/ch/njol/skript/effects/EffBroadcast.java
  src/main/java/ch/njol/skript/expressions/ExprInput.java
Labels: 2.9

#6909 Fix bugs with Timespan#getAs
  src/main/java/ch/njol/skript/util/Timespan.java
  src/test/skript/tests/regressions/6908-timespan too big.sk
Labels: bug, patch-ready, 2.9

#6926 Fix compilation/runtime errors due to Bukkit enum changes
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/entity/CatData.java
  src/main/java/ch/njol/skript/entity/FrogData.java
  src/main/java/ch/njol/skript/entity/VillagerData.java
  src/main/java/ch/njol/skript/entity/ZombieVillagerData.java
Labels: bug, 2.9

#6918 Apply new conventions to lang package
  src/main/java/ch/njol/skript/classes/Changer.java
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/lang/Condition.java
  src/main/java/ch/njol/skript/lang/Debuggable.java
  src/main/java/ch/njol/skript/lang/Effect.java
  src/main/java/ch/njol/skript/lang/EffectSection.java
  src/main/java/ch/njol/skript/lang/EffectSectionEffect.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/ExpressionInfo.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/main/java/ch/njol/skript/lang/InputSource.java
  src/main/java/ch/njol/skript/lang/Literal.java
  src/main/java/ch/njol/skript/lang/LiteralList.java
  src/main/java/ch/njol/skript/lang/ReturnableTrigger.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/SectionSkriptEvent.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/Statement.java
  src/main/java/ch/njol/skript/lang/Trigger.java
  src/main/java/ch/njol/skript/lang/TriggerItem.java
  src/main/java/ch/njol/skript/lang/TriggerSection.java
  src/main/java/ch/njol/skript/lang/UnparsedLiteral.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/main/java/ch/njol/skript/lang/function/EffFunctionCall.java
  src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java
  src/main/java/ch/njol/skript/lang/function/Function.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
  src/main/java/ch/njol/skript/lang/function/JavaFunction.java
  src/main/java/ch/njol/skript/lang/function/Namespace.java
  src/main/java/ch/njol/skript/lang/function/Parameter.java
  src/main/java/ch/njol/skript/lang/function/ScriptFunction.java
  src/main/java/ch/njol/skript/lang/function/Signature.java
  src/main/java/ch/njol/skript/lang/function/SimpleJavaFunction.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/lang/util/ContainerExpression.java
  src/main/java/ch/njol/skript/lang/util/ContextlessEvent.java
  src/main/java/ch/njol/skript/lang/util/ConvertedExpression.java
  src/main/java/ch/njol/skript/lang/util/ConvertedLiteral.java
  src/main/java/ch/njol/skript/lang/util/SimpleEvent.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
  src/main/java/ch/njol/skript/lang/util/SimpleLiteral.java
Labels: enhancement, feature-ready

#6884 Always allow effect commands on testing servers
  src/main/java/ch/njol/skript/command/Commands.java
Labels: feature

#6897 Fix sorting indices of a list with children
  src/main/java/ch/njol/skript/expressions/ExprIndices.java
  src/test/skript/tests/regressions/6881-sorted indices with children.sk
Labels: bug

#6854 Properly name PotionEffectType in lang
  src/main/resources/lang/default.lang
Labels: enhancement, patch-ready, 2.9

#6919 allow pufferfish as entitydata
  src/main/resources/lang/default.lang
Labels: enhancement, patch-ready, 2.9
