Repository SkriptLang/Skript, pull requests merged in 2024-02, with the labels that each got.

#6378 fix 404 error
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
Labels: bug, documentation, 2.8, patch-ready

#6367 SimpleEntityData - add new MC 1.20.3 entities
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/resources/lang/default.lang
Labels: enhancement, 2.8, patch-ready

#6352 Fix Skript MinecraftServer.isRunning reflection on 1.20(.1)
  src/main/java/ch/njol/skript/Skript.java
Labels: bug, 2.8

#6383 Fix "vector from" syntax conflict by making ExprVectorFromDirection parse later.
  src/main/java/ch/njol/skript/expressions/ExprLocationFromVector.java
  src/main/java/ch/njol/skript/expressions/ExprLocationVectorOffset.java
  src/main/java/ch/njol/skript/expressions/ExprVectorAngleBetween.java
  src/main/java/ch/njol/skript/expressions/ExprVectorBetweenLocations.java
  src/main/java/ch/njol/skript/expressions/ExprVectorCrossProduct.java
  src/main/java/ch/njol/skript/expressions/ExprVectorCylindrical.java
  src/main/java/ch/njol/skript/expressions/ExprVectorDotProduct.java
  src/main/java/ch/njol/skript/expressions/ExprVectorFromDirection.java
  src/main/java/ch/njol/skript/expressions/ExprVectorFromXYZ.java
  src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java
  src/main/java/ch/njol/skript/expressions/ExprVectorNormalize.java
  src/main/java/ch/njol/skript/expressions/ExprVectorOfLocation.java
  src/main/java/ch/njol/skript/expressions/ExprVectorSpherical.java
  src/test/skript/tests/regressions/6348-vector from expressions conflict.sk
Labels: bug, 2.8, patch-ready

#6374 Fix paths for enabled scripts in ExprScripts.
  src/main/java/ch/njol/skript/expressions/ExprScripts.java
Labels: bug, 2.8, patch-ready

#6375 Avoid NPE by defaulting to enum name when no language node available in EnumUtil's toString.
  src/main/java/ch/njol/skript/util/EnumUtils.java
Labels: bug, 2.8, patch-ready

#6360 Improve UnparsedLiteral Handling
  src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java
  src/main/java/ch/njol/skript/log/ParseLogHandler.java
  src/main/java/ch/njol/skript/patterns/TypePatternElement.java
  src/test/skript/tests/misc/invalid unparsed literals.sk
  src/test/skript/tests/syntaxes/expressions/ExprArithmetic.sk
Labels: bug, 2.8

#6399 Fix loading on Spigot versions older than 1.18
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
Labels: bug, 2.8

#6391 Fix ExprPlain always getting the base material from ItemTypes
  src/main/java/ch/njol/skript/expressions/ExprPlain.java
  src/test/java/org/skriptlang/skript/test/tests/regression/ExprPlainAliasTest.java
Labels: bug, 2.8, patch-ready

#6387 Fix AIOOB with ExprVectorXYZ when used with non-vectors
  src/main/java/ch/njol/skript/expressions/ExprVectorXYZ.java
  src/test/skript/tests/regressions/6385-x component of block.sk
Labels: bug, 2.8, patch-ready

#6429 Fix Compilation Issues (Address DamageEvent Constructor Changes)
  src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java
  src/test/skript/tests/syntaxes/expressions/ExprLastDamageCause
Labels: bug, 2.8, patch-ready

#6192 Ask for player's groups off the main thread.
  build.gradle
  src/main/java/ch/njol/skript/hooks/permission/expressions/ExprGroup.java
Labels: enhancement, 2.8, patch-ready

#6275 Ignore cleanup lang in git blame
  .git-blame-ignore-revs
Labels: enhancement, 2.8, patch-ready

#6328 Fix Timespan Addition Overflow Exception
  src/main/java/ch/njol/skript/classes/data/DefaultOperations.java
  src/main/java/ch/njol/util/Math2.java
  src/test/skript/tests/regressions/6328-timespan operations can cause exceptions if there's an overflow.sk
Labels: bug, 2.8, patch-ready

#6388 Make function parameters respect the case-insensitive-variables setting.
  src/main/java/ch/njol/skript/lang/function/Parameter.java
Labels: bug, 2.8, patch-ready

#6392 Make bucket fill events provide the correct event-block.
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtBlock.java
Labels: bug, 2.8, patch-ready

#6393 Add "invincible" as a synonym of "invulnerable" in related syntaxes.
  src/main/java/ch/njol/skript/conditions/CondIsInvulnerable.java
  src/main/java/ch/njol/skript/effects/EffInvulnerability.java
  src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java
Labels: enhancement, feature-ready, 2.9
