Repository SkriptLang/Skript, pull requests merged in 2024-03, with the labels that each got.

#6309 Fix duplicate calls of certain click events
  src/main/java/ch/njol/skript/events/EvtClick.java
Labels: bug, 2.8, patch-ready

#6455 Fix parsing errors caused by special characters
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/regressions/6246-special character parsing issues.sk
Labels: bug, 2.8, patch-ready

#6233 Fix InventoryItemMoveEvent Implementations (#5462)
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtItem.java
  src/main/java/ch/njol/skript/expressions/ExprEvtInitiator.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/InventoryMoveItemEventTest.java
  src/test/skript/junit/InventoryMoveItemEvent.sk
Labels: bug, 2.8, patch-ready

#6349 Create SectionExitHandler interface
  src/main/java/ch/njol/skript/effects/EffExit.java
  src/main/java/ch/njol/skript/effects/EffReturn.java
  src/main/java/ch/njol/skript/lang/LoopSection.java
  src/main/java/ch/njol/skript/lang/SectionExitHandler.java
Labels: enhancement, feature-ready, 2.9

#6484 EntityData - check if entity can spawn
  src/main/java/ch/njol/skript/entity/EntityData.java
Labels: bug

#6307 Throw an exception when attempting to register an abstract class
  src/main/java/ch/njol/skript/lang/SyntaxElementInfo.java
Labels: enhancement, feature-ready, 2.9

#4661 🚀 Add timespan details expression & Improvements
  src/main/java/ch/njol/skript/expressions/ExprTimespanDetails.java
  src/main/java/ch/njol/skript/util/Timespan.java
Labels: enhancement, feature, breaking changes, feature-ready, 2.9

#6475 Fixes entitydata consumer on versions 1.20.1 and below.
  src/main/java/ch/njol/skript/entity/EntityData.java
Labels: bug, 2.8, patch-ready

#5676 Change uuid default
  src/main/resources/config.sk
Labels: enhancement, breaking changes, feature-ready, 2.9

#6510 Examples Update
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/expressions/ExprAnvilText.java
Labels: bug, enhancement, documentation, 2.8

#6502 Handle invalid amounts in ExprRandomCharacter
  src/main/java/ch/njol/skript/expressions/ExprRandomCharacter.java
  src/test/skript/tests/syntaxes/expressions/ExprCharacters.sk
Labels: bug, 2.8, patch-ready

#6512 🛠️ Fix ExprRandom missing canInitSafely
  src/main/java/ch/njol/skript/expressions/ExprRandom.java
Labels: bug

#6506 Adds pathfinding condition
  src/main/java/ch/njol/skript/conditions/CondIsPathfinding.java
Labels: feature

#6505 Remove Player name/UUID in variables warning.
  src/main/java/ch/njol/skript/lang/VariableString.java
Labels: enhancement, feature-ready, 2.9

#6413 Add MC 1.20.5 Attributes
  src/main/resources/lang/default.lang
Labels: enhancement

#6473 ItemData/BlockCompat - strip out BlockState middleman
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/bukkitutil/block/BlockCompat.java
  src/main/java/ch/njol/skript/bukkitutil/block/NewBlockCompat.java
  src/main/java/ch/njol/skript/entity/FallingBlockData.java
  src/main/java/ch/njol/skript/events/EvtBlock.java
  src/main/java/ch/njol/skript/events/EvtGrow.java
Labels: bug, 2.8, patch-ready

#6495 ExprIndices - fix strings not sorting alphabetically
  src/main/java/ch/njol/skript/expressions/ExprIndices.java
  src/main/java/ch/njol/skript/expressions/ExprSortedList.java
  src/test/skript/tests/syntaxes/expressions/ExprIndices.sk
Labels: bug, breaking changes, patch-ready
