Repository SkriptLang/Skript, pull requests merged in 2024-11, with the labels that each got.

#7173 Adds basic 1.21.3 support.
  build.gradle
  gradle.properties
  src/main/java/ch/njol/skript/entity/BoatChestData.java
  src/main/java/ch/njol/skript/entity/BoatData.java
  src/main/resources/lang/default.lang
  src/test/skript/environments/java21/paper-1.21.3.json
  src/test/skript/tests/syntaxes/effects/EffHealth.sk
Labels: bug, enhancement, 2.9

#7176 more 1.21.3 support
  src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/resources/lang/default.lang
Labels: 2.9

#7188 Fix the time states expression not accepting plural expressions
  src/main/java/ch/njol/skript/expressions/ExprTimeState.java
Labels: bug

#7199 SoundUtils - handle Sound class for enum/interface
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
  src/main/java/ch/njol/skript/util/SoundUtils.java
  src/test/skript/tests/syntaxes/effects/EffPlaySound.sk
Labels: bug

#7205 fix sound for the third time (on dev/feature this time)
  src/main/java/ch/njol/skript/bukkitutil/SoundUtils.java
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
  src/main/java/ch/njol/skript/expressions/ExprBlockSound.java
  src/main/java/ch/njol/skript/expressions/ExprEntitySound.java
  src/test/skript/tests/syntaxes/expressions/ExprBlockSound.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntitySound.sk
Labels: bug

#7168 Add utility class for easier building of toString
  src/main/java/ch/njol/skript/effects/EffBan.java
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/main/java/ch/njol/skript/lang/SyntaxStringBuilder.java
Labels: enhancement, feature-ready

#7221 Fix EffContinue
  src/main/java/ch/njol/skript/effects/EffContinue.java
  src/test/skript/tests/syntaxes/effects/EffContinue.sk
Labels: bug, priority: high, 2.10

#7215 Expression to get ARGB values of colours
  src/main/java/ch/njol/skript/expressions/ExprARGB.java
  src/main/java/ch/njol/skript/expressions/ExprColorOf.java
  src/main/java/ch/njol/skript/util/Color.java
  src/main/java/ch/njol/skript/util/ColorRGB.java
  src/main/java/ch/njol/skript/util/SkriptColor.java
  src/test/skript/tests/syntaxes/expressions/ExprARGB.sk
Labels: feature, feature-ready

#7210 Prevent long overflow in arithemetic
  src/main/java/ch/njol/skript/classes/data/DefaultOperations.java
  src/test/skript/tests/regressions/7209-long overflow.sk
Labels: bug, patch-ready, 2.9

#7219 Add entity to display converter
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/org/skriptlang/skript/bukkit/displays/DisplayModule.java
  src/test/skript/tests/regressions/7187-display entities conversion.sk
Labels: bug, feature-ready, 2.10

#7202 Handle invalid regex pattern in ExprJoinSplit
  src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
  src/test/skript/tests/regressions/7159-regex exceptions not handled.sk
Labels: bug, patch-ready

#7195 Fix some messages in Turkish
  src/main/resources/lang/turkish.lang
Labels: bug, patch-ready

#7190 Input API
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/main/java/ch/njol/util/coll/CollectionUtils.java
  src/main/java/org/skriptlang/skript/bukkit/input/InputKey.java
  src/main/java/org/skriptlang/skript/bukkit/input/InputModule.java
  src/main/java/org/skriptlang/skript/bukkit/input/elements/conditions/CondIsPressingKey.java
  src/main/java/org/skriptlang/skript/bukkit/input/elements/events/EvtPlayerInput.java
  src/main/java/org/skriptlang/skript/bukkit/input/elements/expressions/ExprCurrentInputKeys.java
  src/main/resources/lang/default.lang
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/conditions/CondIsPressingKeyTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtPlayerInputTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprCurrentInputKeysTest.java
  src/test/java/org/skriptlang/skript/test/utils/InputHelper.java
  src/test/skript/junit/EvtPlayerInput.sk
Labels: feature, feature-ready, 2.10

#7084 Async alias loading
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/aliases/Aliases.java
Labels: enhancement, feature-ready

#7152 Require skull texture lookup on paper servers
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
Labels: bug, patch-ready

#7120 Fix some syntaxes overwriting variable list indices and add new helper method for changing expressions.
  src/main/java/ch/njol/skript/effects/EffEnchant.java
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/main/java/ch/njol/skript/expressions/ExprVectorLength.java
  src/main/java/ch/njol/skript/expressions/ExprVectorXYZ.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/test/skript/tests/regressions/pull-7120-changes overwriting indices.sk
Labels: bug, enhancement, patch-ready

#7129 Pretty Quote Error
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/misc/pull-7129-pretty-quotes.sk
Labels: enhancement, feature-ready

#7037 Secspressions!
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/expressions/base/SectionExpression.java
  src/main/java/ch/njol/skript/lang/ExpressionSection.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/Statement.java
  src/main/java/ch/njol/skript/log/LogEntry.java
  src/main/java/ch/njol/skript/log/RetainingLogHandler.java
  src/main/java/ch/njol/skript/test/runner/EffRunRunnable.java
  src/main/java/ch/njol/skript/test/runner/ExprSecRunnable.java
  src/test/skript/tests/misc/expression sections.sk
Labels: enhancement, feature, feature-ready, 2.10

#6698 Changeable Max Stack Size for Items and Inventory
  src/main/java/ch/njol/skript/expressions/ExprMaxStack.java
  src/test/skript/tests/syntaxes/expressions/ExprMaxStack.sk
Labels: feature, feature-ready

#6706 Allow any script in `using` condition.
  src/main/java/ch/njol/skript/conditions/CondIsUsingFeature.java
Labels: enhancement
