Repository SkriptLang/Skript, pull requests merged in 2024-12, with the labels that each got.

#7232 Updated Projectile Hit event description
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: documentation, patch-ready

#7230 Add missing tree types to prevent EvtGrow causing errors.
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/test/java/org/skriptlang/skript/test/tests/regression/MissingTreeSaplingMapEntriesTest.java
Labels: bug, priority: medium, patch-ready

#7062 ExprBlocks - BlockLineIterator
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
  src/main/java/ch/njol/skript/util/BlockLineIterator.java
  src/test/skript/tests/syntaxes/expressions/ExprBlocks.sk
Labels: bug

#7207 Arithmetic Private Methods Changed to Public
  src/main/java/org/skriptlang/skript/lang/arithmetic/Arithmetics.java
Labels: enhancement

#7047 Database File Limit
  src/main/java/ch/njol/skript/variables/FlatFileStorage.java
  src/main/java/ch/njol/skript/variables/MySQLStorage.java
  src/main/java/ch/njol/skript/variables/SQLStorage.java
  src/main/java/ch/njol/skript/variables/SQLiteStorage.java
  src/main/java/ch/njol/skript/variables/Variables.java
  src/main/java/ch/njol/skript/variables/VariablesStorage.java
Labels: enhancement, breaking changes, feature-ready

#7163 Fix the REMOVE changer of variables
  src/main/java/ch/njol/skript/lang/Variable.java
  src/test/skript/tests/regressions/7162-removing from variable skips duplicates.sk
Labels: bug, patch-ready, 2.10

#7057 Compound Conditionals API
  src/main/java/ch/njol/skript/lang/Condition.java
  src/main/java/ch/njol/skript/sections/SecConditional.java
  src/main/java/org/skriptlang/skript/lang/condition/CompoundConditional.java
  src/main/java/org/skriptlang/skript/lang/condition/Conditional.java
  src/main/java/org/skriptlang/skript/lang/condition/DNFConditionalBuilder.java
  src/test/java/org/skriptlang/skript/test/tests/lang/ConditionalTest.java
Labels: enhancement, feature-ready

#6849 Updates EffEquip, CondIsWearing, and adds CondIsSaddled
  src/main/java/ch/njol/skript/conditions/CondIsSaddled.java
  src/main/java/ch/njol/skript/conditions/CondIsWearing.java
  src/main/java/ch/njol/skript/effects/EffEquip.java
  src/test/skript/tests/syntaxes/conditions/CondIsSaddled.sk
  src/test/skript/tests/syntaxes/effects/EffEquip.sk
Labels: enhancement, feature-ready

#7061 ExprArmorSlot - Body Armor
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
  src/test/skript/tests/syntaxes/expressions/ExprArmorSlot.sk
Labels: enhancement, feature-ready

#7083 ExprAffectedEntities
  src/main/java/ch/njol/skript/expressions/ExprAffectedEntities.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprAffectedEntitiesTest.java
  src/test/skript/junit/ExprAffectedEntities.sk
Labels: enhancement, feature-ready

#7086 Add Item Flags
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprItemFlags.java
  src/main/java/ch/njol/skript/expressions/ExprWithItemFlags.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprItemFlags.sk
Labels: enhancement, feature-ready

#7088 Adding entity expressions & conditions
  src/main/java/ch/njol/skript/conditions/CondFromMobSpawner.java
  src/main/java/ch/njol/skript/conditions/CondIsCustomNameVisible.java
  src/main/java/ch/njol/skript/conditions/CondIsTicking.java
  src/main/java/ch/njol/skript/effects/EffCustomName.java
  src/main/java/ch/njol/skript/expressions/ExprFireTicks.java
  src/test/skript/tests/syntaxes/conditions/CondIsCustomNameVisible.sk
  src/test/skript/tests/syntaxes/conditions/CondIsTicking.sk
Labels: enhancement, feature-ready

#7131 Fireworks Fix
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtFirework.java
  src/main/java/ch/njol/skript/expressions/ExprFireworkEffect.java
  src/main/java/ch/njol/skript/util/SkriptColor.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtFireworkTest.java
  src/test/skript/junit/EvtFireworkTest.sk
Labels: enhancement, feature-ready

#7139 Rework number parser and angle support
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
  src/main/java/ch/njol/skript/effects/EffContinue.java
  src/main/java/ch/njol/skript/effects/EffExit.java
  src/main/java/ch/njol/skript/expressions/ExprAngle.java
  src/main/java/ch/njol/skript/hooks/economy/classes/Money.java
  src/main/java/org/skriptlang/skript/bukkit/misc/effects/EffRotate.java
  src/main/java/org/skriptlang/skript/bukkit/misc/expressions/ExprRotate.java
  src/test/skript/tests/misc/angle.sk
Labels: enhancement, feature-ready

#7174 Item Skull Owner
  src/main/java/ch/njol/skript/expressions/ExprSkullOwner.java
  src/test/skript/tests/syntaxes/expressions/ExprSkullOwner.sk
Labels: enhancement, feature-ready

#7189 Update Timespan
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/conditions/CondDate.java
  src/main/java/ch/njol/skript/effects/Delay.java
  src/main/java/ch/njol/skript/effects/EffBan.java
  src/main/java/ch/njol/skript/effects/EffIgnite.java
  src/main/java/ch/njol/skript/effects/EffPoison.java
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/main/java/ch/njol/skript/effects/EffSendTitle.java
  src/main/java/ch/njol/skript/effects/IndeterminateDelay.java
  src/main/java/ch/njol/skript/events/EvtPeriodical.java
  src/main/java/ch/njol/skript/expressions/ExprBurnCookTime.java
  src/main/java/ch/njol/skript/expressions/ExprCmdCooldownInfo.java
  src/main/java/ch/njol/skript/expressions/ExprEntityItemUseTime.java
  src/main/java/ch/njol/skript/expressions/ExprFireTicks.java
  src/main/java/ch/njol/skript/expressions/ExprFreezeTicks.java
  src/main/java/ch/njol/skript/expressions/ExprItemCooldown.java
  src/main/java/ch/njol/skript/expressions/ExprMaxFreezeTicks.java
  src/main/java/ch/njol/skript/expressions/ExprMaxItemUseTime.java
  src/main/java/ch/njol/skript/expressions/ExprPickupDelay.java
  src/main/java/ch/njol/skript/expressions/ExprPortalCooldown.java
  src/main/java/ch/njol/skript/expressions/ExprPotionEffect.java
  src/main/java/ch/njol/skript/expressions/ExprResonatingTime.java
  src/main/java/ch/njol/skript/expressions/ExprRingingTime.java
  src/main/java/ch/njol/skript/expressions/ExprTimePlayed.java
  src/main/java/ch/njol/skript/expressions/ExprTimespanDetails.java
  src/main/java/ch/njol/skript/util/Date.java
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
  src/main/java/ch/njol/skript/util/Timespan.java
  src/main/java/ch/njol/skript/util/visual/VisualEffects.java
  src/main/java/ch/njol/skript/variables/SQLStorage.java
  src/main/java/ch/njol/skript/variables/VariablesStorage.java
Labels: feature-ready, housekeeping

#7192 Fix reload notify permission and bump api version in plugin.yml
  src/main/resources/plugin.yml
Labels: bug, enhancement, feature-ready, 2.10

#7169 Fix PropertyExpression's expr annotation
  src/main/java/ch/njol/skript/expressions/ExprTime.java
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
Labels: enhancement, feature-ready

#7228 Add warning when pausing is enabled
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement, feature-ready

#7235 Added "Thrice" to ExprTimes
  src/main/java/ch/njol/skript/expressions/ExprTimes.java
  src/test/skript/tests/syntaxes/expressions/ExprTimes.sk
Labels: enhancement, feature-ready

#7241 Fix CIP implementation for Variable
  src/main/java/ch/njol/skript/lang/Variable.java
Labels: bug, feature-ready, 2.10

#7244 Updates SyntaxStringBuilder to return itself
  src/main/java/ch/njol/skript/lang/SyntaxStringBuilder.java
Labels: enhancement, feature-ready

#7255 Helper for running code with copied local variables
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: enhancement, feature-ready

#7247 Fix async alias loading on 1.19.4
  src/main/java/ch/njol/skript/entity/EntityData.java
Labels: bug, 2.10

#7262 fix detonate test contamination
  src/test/skript/tests/syntaxes/effects/EffDetonate.sk
Labels: bug, 2.10

#7240 Test - Update for MC 1.19+
  src/test/skript/tests/misc/displaydata.sk
  src/test/skript/tests/misc/displays.sk
  src/test/skript/tests/misc/registry.sk
  src/test/skript/tests/regressions/2535-foxdata fixes.sk
  src/test/skript/tests/regressions/2537-missing mooshroom variations in 1.14+.sk
  src/test/skript/tests/regressions/2625-villager comparisons.sk
  src/test/skript/tests/regressions/3253-entitydata fixes.sk
  src/test/skript/tests/regressions/3303-item durability.sk
  src/test/skript/tests/regressions/4769-fire-visualeffect.sk
  src/test/skript/tests/regressions/4773-composter-the-imposter.sk
  src/test/skript/tests/regressions/5491-xp orb merge overwrite.sk
  src/test/skript/tests/regressions/7140-leather horse armor unequipable.sk
  src/test/skript/tests/regressions/pull-5566-block iterator being 100 always.sk
  src/test/skript/tests/syntaxes/conditions/CondIsPreferredTool.sk
  src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
  src/test/skript/tests/syntaxes/effects/EffDetonate.sk
  src/test/skript/tests/syntaxes/effects/EffExplodeCreeper.sk
  src/test/skript/tests/syntaxes/effects/EffGlowingText.sk
  src/test/skript/tests/syntaxes/effects/EffHandedness.sk
  src/test/skript/tests/syntaxes/effects/EffInvisible.sk
  src/test/skript/tests/syntaxes/expressions/ExprBlockData.sk
  src/test/skript/tests/syntaxes/expressions/ExprColorOf.sk
  src/test/skript/tests/syntaxes/expressions/ExprCustomModelData.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayBillboard.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayBrightness.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayGlowOverride.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayHeightWidth.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayInterpolation.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayShadow.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayTransformation.sk
  src/test/skript/tests/syntaxes/expressions/ExprDisplayViewRange.sk
  src/test/skript/tests/syntaxes/expressions/ExprExplosiveYield.sk
  src/test/skript/tests/syntaxes/expressions/ExprFreezeTicks.sk
  src/test/skript/tests/syntaxes/expressions/ExprItemDisplayTransform.sk
  src/test/skript/tests/syntaxes/expressions/ExprLowestHighestSolidBlock.sk
  src/test/skript/tests/syntaxes/expressions/ExprMaxPlayers.sk
  src/test/skript/tests/syntaxes/expressions/ExprQuaternionAxisAngle.sk
  src/test/skript/tests/syntaxes/expressions/ExprTextDisplayAlignment.sk
  src/test/skript/tests/syntaxes/expressions/ExprTextDisplayLineWidth.sk
  src/test/skript/tests/syntaxes/expressions/ExprTextDisplayOpacity.sk
  src/test/skript/tests/syntaxes/expressions/ExprWhitelist.sk
  src/test/skript/tests/syntaxes/expressions/ExprXYZComponent.sk
  src/test/skript/tests/syntaxes/functions/offlinePlayer.sk
  src/test/skript/tests/syntaxes/functions/quaternions.sk
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: unit testing, feature-ready

#7268 Fix Improperly Typed Array in ExprXOf
  src/main/java/ch/njol/skript/expressions/ExprXOf.java
  src/test/skript/tests/regressions/6817-null of x incorrect type.sk
Labels: bug, patch-ready

#7265 Add Reload Event for SkriptConfig
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/org/skriptlang/skript/util/event/EventRegistry.java
Labels: feature, feature-ready

#7273 Fix ExprTextOf error on Spigot
  src/main/java/org/skriptlang/skript/bukkit/misc/expressions/ExprTextOf.java
Labels: bug, feature-ready, 2.10

#7271 SoundReceiver - fix error on Spigot when adventure API is implemented
  src/main/java/ch/njol/skript/bukkitutil/sounds/SoundReceiver.java
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
Labels: bug, feature-ready, 2.10

#7072 Keyed Set Mode
  src/main/java/ch/njol/skript/classes/Changer.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/lang/KeyProviderExpression.java
  src/main/java/ch/njol/skript/lang/KeyReceiverExpression.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/test/runner/ExprKeyValueSet.java
  src/test/skript/tests/misc/keyed set mode.sk
Labels: enhancement, feature-ready, 2.10

#6562 For each index & value loop.
  src/main/java/ch/njol/skript/registrations/Feature.java
  src/main/java/ch/njol/skript/sections/SecFor.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/test/skript/tests/syntaxes/sections/SecFor.sk
Labels: feature, feature-ready, 2.10

#7167 Add regex replacement
  src/main/java/ch/njol/skript/effects/EffReplace.java
  src/test/skript/tests/syntaxes/effects/EffReplace.sk
Labels: enhancement, feature-ready, 2.10

#6439 Adds skript list command
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
  src/main/resources/lang/english.lang
Labels: feature, feature-ready, 2.10

#6609 Reserve variable starting characters.
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/variables/Variables.java
  src/main/java/ch/njol/skript/variables/VariablesStorage.java
Labels: enhancement, variables, feature-ready, 2.10

#7260 Vehicle Events
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtVehicleCollision.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtVehicleCollisionTest.java
  src/test/skript/junit/EvtVehicleCollisionTest.sk
Labels: feature, feature-ready, 2.10

#7239 Remove 'download' argument from Skript command
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
  src/main/resources/lang/dutch.lang
  src/main/resources/lang/english.lang
  src/main/resources/lang/french.lang
  src/main/resources/lang/german.lang
  src/main/resources/lang/japanese.lang
  src/main/resources/lang/korean.lang
  src/main/resources/lang/polish.lang
  src/main/resources/lang/russian.lang
  src/main/resources/lang/simplifiedchinese.lang
  src/main/resources/lang/turkish.lang
Labels: enhancement, feature-ready, 2.10

#7251 Comparators - add default comparators
  src/main/java/ch/njol/skript/classes/EnumClassInfo.java
  src/main/java/ch/njol/skript/classes/registry/RegistryClassInfo.java
  src/test/skript/tests/misc/registry-enum-comparators.sk
Labels: bug, feature-ready, 2.10

#7245 Update Paper API
  build.gradle
  src/test/skript/environments/java21/paper-1.21.4.json
Labels: enhancement, feature-ready, 2.10

#7137 Add fishing
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprExperience.java
  src/main/java/ch/njol/util/StringUtils.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/FishingModule.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/CondFishingLure.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/CondIsInOpenWater.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EffFishingLure.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EffPullHookedEntity.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EvtBucketEntity.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EvtFish.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingApproachAngle.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingBiteTime.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingHook.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingHookEntity.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/ExprFishingWaitTime.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtBucketEntityTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtFishTest.java
  src/test/skript/junit/EvtBucketEntity.sk
  src/test/skript/junit/EvtFish.sk
Labels: feature, breaking changes, feature-ready, 2.10

#7233 Salmon Variants
  src/main/java/ch/njol/skript/entity/SalmonData.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: enhancement, feature-ready, 2.10

#7132 Previous+Next Loop-Value
  src/main/java/ch/njol/skript/expressions/ExprLoopValue.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/Loopable.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/main/java/ch/njol/skript/test/runner/ExprTestLoopPeeking.java
  src/main/java/ch/njol/util/coll/iterator/ArrayIterator.java
  src/test/skript/tests/syntaxes/expressions/ExprLoopValue.sk
Labels: enhancement, feature-ready, 2.10

#7279 Inventory - prevent opening a non-creatable inventory
  src/main/java/ch/njol/skript/effects/EffOpenInventory.java
  src/main/java/ch/njol/skript/expressions/ExprNamed.java
  src/test/skript/tests/regressions/7279-create-uncreatable-inventory.sk
Labels: bug, feature-ready, 2.10

#7079 BeaconEvents + Expressions
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtBeaconEffect.java
  src/main/java/ch/njol/skript/events/EvtBeaconToggle.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprAppliedEffect.java
  src/main/java/ch/njol/skript/expressions/ExprBeaconValues.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtBeaconTest.java
  src/test/skript/junit/EvtBeaconTest.sk
  src/test/skript/tests/syntaxes/expressions/ExprBeaconValues.sk
Labels: enhancement, feature-ready, 2.10

#7269 Improve registering event values
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/registrations/EventValues.java
  src/main/java/ch/njol/skript/util/Getter.java
Labels: enhancement, feature-ready, 2.10

#7291 Fix registering EventValues for addons
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug, feature-ready, 2.10

#7296 SkriptCommand - don't double send reload messages
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/log/RedirectingLogHandler.java
Labels: bug, feature-ready, 2.10

#7303 Added missing space.
  src/main/java/ch/njol/skript/expressions/ExprExperienceCooldownChangeReason.java
Labels: documentation, feature-ready

#7305 Fix dependency incompatibility caused by Paper.
  build.gradle
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
Labels: bug, priority: high, 2.10

#7293 Aliases - remove thread sleep
  src/main/java/ch/njol/skript/aliases/Aliases.java
Labels: enhancement, feature-ready, 2.10

#7220 Spawn Egg Meta + EntitySnapshots
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/expressions/ExprEntitySnapshot.java
  src/main/java/ch/njol/skript/expressions/ExprSpawnEggEntity.java
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprEntitySnapshot.sk
Labels: feature, feature-ready, 2.10

#7242 Adds Loot Tables
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/LootContextCreateEvent.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/LootContextWrapper.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/LootTableModule.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/LootTableUtils.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/conditions/CondHasLootTable.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/conditions/CondIsLootable.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/effects/EffGenerateLoot.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLoot.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootContext.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootContextEntity.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootContextLocation.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootContextLooter.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootContextLuck.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootItems.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootTable.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootTableFromString.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprLootTableSeed.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprSecCreateLootContext.java
  src/main/resources/lang/default.lang
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprLootContextLooterTest.java
  src/test/skript/junit/ExprLootContextLooter.sk
  src/test/skript/tests/syntaxes/conditions/CondHasLootTable.sk
  src/test/skript/tests/syntaxes/conditions/CondIsLootable.sk
  src/test/skript/tests/syntaxes/expressions/ExprLootContext.sk
  src/test/skript/tests/syntaxes/expressions/ExprLootItems.sk
  src/test/skript/tests/syntaxes/expressions/ExprLootTable.sk
  src/test/skript/tests/syntaxes/expressions/ExprLootTableSeed.sk
Labels: feature, feature-ready, 2.10

#7065 EffBlockUpdate
  src/main/java/ch/njol/skript/effects/EffBlockUpdate.java
  src/test/skript/tests/syntaxes/effects/EffBlockUpdate.sk
Labels: feature, feature-ready, 2.10

#7107 Add a way to get patterns from the PropertyCondition
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
Labels: enhancement, feature-ready, 2.10

#7250 Add villager expressions
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprVillagerLevel.java
  src/main/java/ch/njol/skript/expressions/ExprVillagerProfession.java
  src/main/java/ch/njol/skript/expressions/ExprVillagerType.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprVillagerLevel.sk
  src/test/skript/tests/syntaxes/expressions/ExprVillagerProfession.sk
  src/test/skript/tests/syntaxes/expressions/ExprVillagerType.sk
Labels: feature, feature-ready, 2.10

#7224 Add safe config updating
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/config/Config.java
  src/main/java/ch/njol/skript/config/EntryNode.java
  src/main/java/ch/njol/skript/config/InvalidNode.java
  src/main/java/ch/njol/skript/config/Node.java
  src/main/java/ch/njol/skript/config/SectionNode.java
  src/main/java/ch/njol/skript/config/SimpleNode.java
  src/main/java/ch/njol/skript/config/VoidNode.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/test/java/ch/njol/skript/config/ConfigHelper.java
  src/test/java/org/skriptlang/skript/test/tests/config/ConfigTest.java
  src/test/resources/invalid-config.sk
  src/test/resources/new-config.sk
  src/test/resources/old-config.sk
Labels: bug, feature-ready, 2.10

#7093 FurnaceEvents, Expressions
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprBurnCookTime.java
  src/main/java/ch/njol/skript/expressions/ExprFireTicks.java
  src/main/java/ch/njol/skript/expressions/ExprFurnaceSlot.java
  src/main/java/org/skriptlang/skript/bukkit/furnace/FurnaceModule.java
  src/main/java/org/skriptlang/skript/bukkit/furnace/elements/EvtFurnace.java
  src/main/java/org/skriptlang/skript/bukkit/furnace/elements/ExprFurnaceEventItems.java
  src/main/java/org/skriptlang/skript/bukkit/furnace/elements/ExprFurnaceSlot.java
  src/main/java/org/skriptlang/skript/bukkit/furnace/elements/ExprFurnaceTime.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtFurnaceTest.java
  src/test/skript/junit/EvtFurnaceTest.sk
  src/test/skript/tests/syntaxes/expressions/ExprFurnace.sk
Labels: enhancement, feature-ready, 2.10

#7283 Elytra Boost
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/conditions/CondElytraBoostConsume.java
  src/main/java/ch/njol/skript/effects/EffElytraBoostConsume.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/PlayerElytraBoostEventTest.java
  src/test/skript/junit/PlayerElytraBoostEventTest.sk
Labels: feature, feature-ready

#7267 Util Additions
  src/main/java/ch/njol/skript/bukkitutil/SoundUtils.java
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
  src/main/java/ch/njol/skript/effects/EffStopSound.java
Labels: enhancement

#7284 EntryContainer#hasEntry
  src/main/java/ch/njol/skript/test/runner/StructEntryContainerTest.java
  src/main/java/org/skriptlang/skript/lang/entry/EntryContainer.java
  src/test/java/org/skriptlang/skript/test/tests/lang/EntryContainerTest.java
  src/test/skript/junit/EntryContainerTest.sk
Labels: enhancement

#7309 Support damage entity with damage-causes in MC 1.20.4+ (rehash #7044)
  src/main/java/ch/njol/skript/bukkitutil/DamageUtils.java
  src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java
  src/main/java/ch/njol/skript/effects/EffHealth.java
  src/test/skript/tests/syntaxes/effects/EffHealth.sk
Labels: don't merge me !!

#7299 Fix outdated for-each loop example.
  src/main/java/ch/njol/skript/sections/SecFor.java
Labels: documentation, feature-ready, 2.10

#7301 Add boat data check to prevent error.
  src/main/java/ch/njol/skript/entity/BoatData.java
Labels: bug, feature-ready, 2.10

#7304 Fix plural identification for class infos in patterns.
  src/main/java/ch/njol/skript/test/runner/EffTestPluralClassInfos.java
  src/main/java/ch/njol/skript/util/Utils.java
Labels: bug, 2.10

#7252 Fix BlockIgniteEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: bug, patch-ready, 2.10

#7319 RegistryClassInfo - fix comparator (Failing Tests)
  src/main/java/ch/njol/skript/classes/registry/RegistryClassInfo.java
Labels: bug

#7281 Supported events
  src/main/java/ch/njol/skript/expressions/ExprArgument.java
  src/main/java/ch/njol/skript/expressions/ExprAttacked.java
  src/main/java/ch/njol/skript/expressions/ExprAttacker.java
  src/main/java/ch/njol/skript/expressions/ExprCommand.java
  src/main/java/ch/njol/skript/expressions/ExprDrops.java
  src/main/java/ch/njol/skript/expressions/ExprExplodedBlocks.java
  src/main/java/ch/njol/skript/expressions/ExprPushedBlocks.java
  src/main/java/ch/njol/skript/lang/EventRestrictedSyntax.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/misc/supported events.sk
Labels: enhancement, feature-ready

#7312 Add unicode tag
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
  src/test/skript/tests/misc/unicode.sk
Labels: enhancement, feature-ready

#7320 Add event-block to command struct
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: enhancement, feature-ready

#6246 New Registration API
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptAddon.java
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
  src/main/java/ch/njol/skript/lang/Condition.java
  src/main/java/ch/njol/skript/lang/ExpressionType.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/java/ch/njol/skript/lang/SyntaxElementInfo.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/main/java/org/skriptlang/skript/Skript.java
  src/main/java/org/skriptlang/skript/SkriptImpl.java
  src/main/java/org/skriptlang/skript/addon/AddonModule.java
  src/main/java/org/skriptlang/skript/addon/SkriptAddon.java
  src/main/java/org/skriptlang/skript/addon/SkriptAddonImpl.java
  src/main/java/org/skriptlang/skript/bukkit/registration/BukkitRegistryKeys.java
  src/main/java/org/skriptlang/skript/bukkit/registration/BukkitSyntaxInfos.java
  src/main/java/org/skriptlang/skript/bukkit/registration/BukkitSyntaxInfosImpl.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
  src/main/java/org/skriptlang/skript/lang/structure/StructureInfo.java
  src/main/java/org/skriptlang/skript/localization/Localizer.java
  src/main/java/org/skriptlang/skript/localization/LocalizerImpl.java
  src/main/java/org/skriptlang/skript/registration/DefaultSyntaxInfos.java
  src/main/java/org/skriptlang/skript/registration/DefaultSyntaxInfosImpl.java
  src/main/java/org/skriptlang/skript/registration/SyntaxInfo.java
  src/main/java/org/skriptlang/skript/registration/SyntaxInfoImpl.java
  src/main/java/org/skriptlang/skript/registration/SyntaxOrigin.java
  src/main/java/org/skriptlang/skript/registration/SyntaxRegister.java
  src/main/java/org/skriptlang/skript/registration/SyntaxRegistry.java
  src/main/java/org/skriptlang/skript/registration/SyntaxRegistryImpl.java
  src/main/java/org/skriptlang/skript/util/Builder.java
  src/main/java/org/skriptlang/skript/util/ClassLoader.java
  src/main/java/org/skriptlang/skript/util/ClassUtils.java
  src/main/java/org/skriptlang/skript/util/Priority.java
  src/main/java/org/skriptlang/skript/util/PriorityImpl.java
  src/main/java/org/skriptlang/skript/util/Registry.java
  src/main/java/org/skriptlang/skript/util/ViewProvider.java
Labels: enhancement, feature, needs testing, breaking changes, 2.10

#6728 Any X
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/classes/AnyInfo.java
  src/main/java/ch/njol/skript/classes/ClassInfo.java
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/conditions/CondContains.java
  src/main/java/ch/njol/skript/conditions/CondIsEmpty.java
  src/main/java/ch/njol/skript/expressions/ExprAmount.java
  src/main/java/ch/njol/skript/expressions/ExprItemAmount.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/main/java/ch/njol/skript/lang/util/common/AnyAmount.java
  src/main/java/ch/njol/skript/lang/util/common/AnyContains.java
  src/main/java/ch/njol/skript/lang/util/common/AnyNamed.java
  src/main/java/ch/njol/skript/lang/util/common/AnyProvider.java
  src/main/java/ch/njol/skript/util/slot/Slot.java
  src/main/java/org/skriptlang/skript/lang/converter/Converter.java
  src/main/java/org/skriptlang/skript/lang/converter/Converters.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprAmount.sk
  src/test/skript/tests/syntaxes/expressions/ExprName.sk
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: bug, enhancement, 2.10

#7308 'sk test' command upgrades
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
  src/main/java/ch/njol/skript/test/utils/TestResults.java
Labels: enhancement, feature-ready

#7315 SkriptCommand - fix sending hidden files
  src/main/java/ch/njol/skript/SkriptCommand.java
Labels: enhancement, feature-ready

#7318 ExprVillagerLevel - add experience
  src/main/java/ch/njol/skript/expressions/ExprVillagerLevel.java
  src/test/skript/tests/syntaxes/expressions/ExprVillagerLevel.sk
Labels: enhancement, feature-ready

#7313 Github Issue Update
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: github related, feature-ready

#7165 Fix expression conversion
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/util/ConvertedExpression.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
  src/test/skript/tests/regressions/7164-expressions sometimes dont convert.sk
Labels: bug

#7216 Banner Patterns
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/expressions/ExprBannerItem.java
  src/main/java/ch/njol/skript/expressions/ExprBannerPatterns.java
  src/main/java/ch/njol/skript/expressions/ExprColorOf.java
  src/main/java/ch/njol/skript/expressions/ExprNewBannerPattern.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprBannerItem.sk
  src/test/skript/tests/syntaxes/expressions/ExprNewBannerPattern.sk
Labels: feature, 2.10

#7330 Use tabs consistently with all other files.
  src/main/java/ch/njol/skript/doc/DocumentationId.java
  src/main/java/ch/njol/skript/doc/RequiredPlugins.java
  src/main/java/ch/njol/skript/update/GithubChecker.java
  src/main/java/ch/njol/util/Math2.java
  src/main/java/ch/njol/util/NotifyingReference.java
  src/main/java/ch/njol/util/SynchronizedReference.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/LootContextWrapper.java
  src/test/skript/junit/-BellEventsPaper.sk
  src/test/skript/junit/-BellEventsSpigot.sk
  src/test/skript/junit/BellEvents.sk
  src/test/skript/tests/regressions/4988-function uuid multiple parameters.sk
  src/test/skript/tests/regressions/6288-event data priority pollution.sk
  src/test/skript/tests/regressions/6290-item-inventory-conflict.sk
  src/test/skript/tests/regressions/7279-create-uncreatable-inventory.sk
  src/test/skript/tests/regressions/pull-6361-function-param.sk
  src/test/skript/tests/syntaxes/conditions/CondIsOfType.sk
  src/test/skript/tests/syntaxes/effects/EffDoIf.sk
  src/test/skript/tests/syntaxes/effects/EffPvP.sk
  src/test/skript/tests/syntaxes/expressions/ExprArithmetic.sk
  src/test/skript/tests/syntaxes/expressions/ExprInventory.sk
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
  src/test/skript/tests/syntaxes/sections/SecParse.sk
  src/test/skript/tests/syntaxes/structures/StructParse.sk
Labels: patch-ready, feature-ready, 2.10

#7327 ExprSets - fix return issue
  src/main/java/ch/njol/skript/expressions/ExprSets.java
  src/test/skript/tests/regressions/7327-expr-sets-return.sk
Labels: bug, feature-ready, 2.10

#7175 UpDate
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/conditions/CondDate.java
  src/main/java/ch/njol/skript/expressions/ExprFormatDate.java
  src/main/java/ch/njol/skript/expressions/ExprUnixTicks.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/util/Date.java
  src/test/java/org/skriptlang/skript/test/tests/utils/DateTest.java
Labels: enhancement, feature-ready, 2.10

#7285 The End of the Getter era
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtExperienceChange.java
  src/main/java/ch/njol/skript/events/EvtExperienceSpawn.java
  src/main/java/ch/njol/skript/events/EvtVehicleCollision.java
  src/main/java/ch/njol/skript/events/bukkit/ScheduledEvent.java
  src/main/java/ch/njol/skript/expressions/ExprBeaconValues.java
  src/main/java/ch/njol/skript/expressions/ExprFoodLevel.java
  src/main/java/ch/njol/skript/expressions/ExprFormatDate.java
  src/main/java/ch/njol/skript/expressions/ExprHealth.java
  src/main/java/ch/njol/skript/expressions/ExprHotbarSlot.java
  src/main/java/ch/njol/skript/expressions/ExprLastDamageCause.java
  src/main/java/ch/njol/skript/expressions/ExprNamed.java
  src/main/java/ch/njol/skript/expressions/ExprOpenedInventory.java
  src/main/java/ch/njol/skript/expressions/ExprSeed.java
  src/main/java/ch/njol/skript/expressions/ExprTool.java
  src/main/java/ch/njol/skript/expressions/ExprWeather.java
  src/main/java/ch/njol/skript/hooks/regions/events/EvtRegionBorder.java
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/main/java/ch/njol/skript/test/runner/EvtTestCase.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/BreedingModule.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EvtBucketEntity.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EvtFish.java
  src/main/java/org/skriptlang/skript/bukkit/input/InputModule.java
Labels: housekeeping, 2.10

#7321 EntitySnapshot ClassInfo Parser + Converter
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/test/skript/tests/syntaxes/expressions/ExprEntitySnapshot.sk
Labels: bug, enhancement, feature-ready, 2.10

#6427 Add Leash Event and Its Methods
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/conditions/CondLeashWillDrop.java
  src/main/java/ch/njol/skript/effects/EffDropLeash.java
  src/main/java/ch/njol/skript/events/EvtLeash.java
  src/main/java/ch/njol/skript/expressions/ExprUnleashReason.java
  src/main/resources/lang/default.lang
Labels: feature, feature-ready, 2.10

#7148 Improve kill effect
  src/main/java/ch/njol/skript/effects/EffKill.java
Labels: bug, breaking changes, feature-ready, 2.10
