Repository SkriptLang/Skript, pull requests merged in 2024-05, with the labels that each got.

#6628 Append version to artefact name.
  build.gradle
Labels: enhancement, 2.8

#6614 Fix entity casting issue and add regression test.
  src/main/java/ch/njol/skript/expressions/ExprNearestEntity.java
  src/main/java/ch/njol/skript/util/Utils.java
  src/test/skript/tests/regressions/6612-nearest entity cast error.sk
Labels: bug, 2.8

#6586 Fix weird item mutation bug with EffHealth
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/effects/EffHealth.java
  src/test/skript/tests/regressions/pull-6586-effhealth item mutation.sk
Labels: bug, 2.8, patch-ready

#6632 Add 1.20.5 entities
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/resources/lang/default.lang
Labels: 2.8

#6631 Bump version to 2.8.5
  gradle.properties
Labels: 2.8

#6644 Fix EffHealth - slot durability not accounting correctly
  src/main/java/ch/njol/skript/effects/EffHealth.java
  src/test/skript/tests/regressions/6643-effhealth slot not accounting existing damage
Labels: bug, 2.8, patch-ready

#6664 Deprecate outdated utils/vector math
  src/main/java/ch/njol/skript/effects/EffVectorRotateAroundAnother.java
  src/main/java/ch/njol/skript/effects/EffVectorRotateXYZ.java
  src/main/java/ch/njol/skript/expressions/ExprVectorCylindrical.java
  src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java
  src/main/java/ch/njol/skript/expressions/ExprVectorSpherical.java
  src/main/java/ch/njol/skript/expressions/ExprYawPitch.java
  src/main/java/ch/njol/util/VectorMath.java
Labels: housekeeping

#6576 Support string concatenation.
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/classes/data/DefaultOperations.java
  src/test/skript/tests/misc/string concatenation.sk
  src/test/skript/tests/syntaxes/functions/concat.sk
Labels: enhancement, feature, feature-ready

#6556 Allow look-behind for headless effect sections during init.
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/lang/Statement.java
Labels: enhancement, feature-ready, 2.9

#6558 Add `###` multi-line comment support.
  src/main/java/ch/njol/skript/config/Node.java
  src/main/java/ch/njol/skript/config/SectionNode.java
  src/test/skript/tests/misc/block comments.sk
Labels: feature, feature-ready, 2.9

#6646 EffHealth - fix max damage on custom items
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
  src/main/java/ch/njol/skript/effects/EffHealth.java
Labels: bug, 2.8, patch-ready

#6627 Add dynamic usage messages for commands
  src/main/java/ch/njol/skript/command/CommandUsage.java
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/structures/StructCommand.java
Labels: enhancement, feature-ready, 2.9

#6549 Add deprecated syntax warning type
  src/main/java/ch/njol/skript/effects/EffSuppressWarnings.java
  src/main/java/ch/njol/skript/expressions/ExprVectorArithmetic.java
  src/main/java/org/skriptlang/skript/lang/script/ScriptWarning.java
Labels: feature, feature-ready, 2.9

#6361 🚀 Making function param rules stricter for the better
  src/main/java/ch/njol/skript/lang/function/Parameter.java
  src/test/skript/tests/regressions/pull-6361-function-param.sk
Labels: enhancement, breaking changes, feature-ready, 2.9

#5422 Fix & Enhance Whitelist
  src/main/java/ch/njol/skript/conditions/CondIsWhitelisted.java
  src/main/java/ch/njol/skript/effects/EffEnforceWhitelist.java
  src/main/java/ch/njol/skript/expressions/ExprWhitelist.java
  src/test/skript/tests/syntaxes/expressions/ExprWhitelist.sk
Labels: bug, enhancement, feature-ready, 2.9

#6334 Add support for character codepoints
  src/main/java/ch/njol/skript/expressions/ExprCharacterFromCodepoint.java
  src/main/java/ch/njol/skript/expressions/ExprCodepoint.java
  src/test/skript/tests/syntaxes/expressions/ExprCodepoint.sk
Labels: feature

#6160 Add Breakable Syntax to Existing Unbreakable Syntaxes
  src/main/java/ch/njol/skript/conditions/CondIsUnbreakable.java
  src/main/java/ch/njol/skript/expressions/ExprUnbreakable.java
  src/test/skript/tests/syntaxes/expressions/ExprUnbreakable.sk
Labels: enhancement, feature-ready, 2.9

#6673 Delete ExprVectorArithmetic
  src/main/java/ch/njol/skript/expressions/ExprVectorArithmetic.java
  src/test/skript/tests/syntaxes/expressions/ExprArithmetic.sk
  src/test/skript/tests/syntaxes/expressions/ExprVectorArithmetic.sk
Labels: enhancement, feature-ready

#6422 Feature/target block update
  src/main/java/ch/njol/skript/expressions/ExprTargetedBlock.java
Labels: enhancement, breaking changes, feature-ready

#6674 Remove 1.13 method/version checks from conditions.
  src/main/java/ch/njol/skript/conditions/CondHasResourcePack.java
  src/main/java/ch/njol/skript/conditions/CondIgnitionProcess.java
  src/main/java/ch/njol/skript/conditions/CondIsFuel.java
  src/main/java/ch/njol/skript/conditions/CondIsInteractable.java
  src/main/java/ch/njol/skript/conditions/CondIsPassable.java
  src/main/java/ch/njol/skript/conditions/CondIsSwimming.java
Labels: housekeeping

#6675 Remove 1.13 version checks from effects.
  src/main/java/ch/njol/skript/effects/EffMakeFly.java
  src/main/java/ch/njol/skript/effects/EffPlayerVisibility.java
  src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
  src/main/java/ch/njol/skript/effects/EffSendTitle.java
Labels: housekeeping

#6639 Adds some fire resistant syntax
  src/main/java/ch/njol/skript/conditions/CondIsFireResistant.java
  src/main/java/ch/njol/skript/effects/EffFireResistant.java
  src/main/java/ch/njol/skript/expressions/ExprWithFireResistance.java
  src/test/skript/tests/syntaxes/conditions/CondIsFireResistant.sk
  src/test/skript/tests/syntaxes/effects/EffFireResistant.sk
  src/test/skript/tests/syntaxes/expressions/ExprWithFireResistance.sk
Labels: feature, feature-ready

#6568 Variable-arity returns and function contracts.
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/JavaFunction.java
  src/main/java/ch/njol/skript/lang/function/Signature.java
  src/main/java/ch/njol/skript/lang/function/SimpleJavaFunction.java
  src/main/java/ch/njol/skript/util/Contract.java
  src/test/skript/tests/syntaxes/functions/clamp.sk
Labels: enhancement, feature, functions, feature-ready

#6683 Copy the SimpleLiteral backing data instead of exposing it.
  src/main/java/ch/njol/skript/lang/util/SimpleLiteral.java
Labels: bug, 2.8

#6692 Fix compilation error due to Spigot changes to EntityDeathEvent
  src/test/java/org/skriptlang/skript/test/tests/lang/CancelledEventsTest.java
  src/test/skript/junit/CancelledEventTest.sk
Labels: bug, 2.9

#6552 Experimental features & the `using` structure.
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/conditions/CondIsUsingFeature.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/registrations/Feature.java
  src/main/java/ch/njol/skript/structures/StructUsing.java
  src/main/java/ch/njol/skript/test/runner/ExprExperimentalOnly.java
  src/main/java/ch/njol/skript/test/runner/TestFeatures.java
  src/main/java/org/skriptlang/skript/lang/experiment/Experiment.java
  src/main/java/org/skriptlang/skript/lang/experiment/ExperimentRegistry.java
  src/main/java/org/skriptlang/skript/lang/experiment/ExperimentSet.java
  src/main/java/org/skriptlang/skript/lang/experiment/Experimented.java
  src/main/java/org/skriptlang/skript/lang/experiment/LifeCycle.java
  src/test/skript/tests/syntaxes/structures/StructUsing.sk
Labels: enhancement, feature, feature-ready, 2.9

#6696 Removed some redundant exists checks and formatting stuff
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: housekeeping

#6716 Particle Compatibility Improvements
  src/main/java/ch/njol/skript/util/visual/VisualEffect.java
  src/main/java/ch/njol/skript/util/visual/VisualEffects.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/regressions/3284-itemcrack particle.sk
  src/test/skript/tests/syntaxes/effects/EffVisualEffect.sk
Labels: bug, enhancement, needs testing, 2.8, patch-ready

#6742 Fix bug with target distance and clean up method
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
Labels: bug, 2.8, patch-ready

#6724 Fix make look at vector
  src/main/java/ch/njol/skript/bukkitutil/PaperEntityUtils.java
Labels: bug, 2.8, patch-ready

#6693 Removed PassengerUtils class and replaced methods in referencing classes
  src/main/java/ch/njol/skript/bukkitutil/PassengerUtils.java
  src/main/java/ch/njol/skript/effects/EffVehicle.java
  src/main/java/ch/njol/skript/expressions/ExprPassenger.java
Labels: housekeeping

#6654 Improve /skript subcommand help colours
  src/main/java/ch/njol/skript/SkriptCommand.java
Labels: enhancement, 2.8, patch-ready

#6642 Adds checks to not normalize zero vectors
  src/main/java/ch/njol/skript/expressions/ExprVectorLength.java
  src/main/java/ch/njol/skript/expressions/ExprVectorNormalize.java
  src/main/java/ch/njol/util/VectorMath.java
  src/test/skript/tests/regressions/6194-vectors + push.sk
Labels: bug, 2.8, patch-ready

#6624 Allow multiple potential return types & defer expression type checking.
  src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java
  src/main/java/ch/njol/skript/expressions/base/WrapperExpression.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/main/java/ch/njol/skript/lang/LiteralList.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/util/ConvertedExpression.java
  src/main/java/ch/njol/skript/lang/util/SimpleExpression.java
  src/main/java/ch/njol/skript/util/LiteralUtils.java
  src/main/java/org/skriptlang/skript/lang/arithmetic/Arithmetics.java
  src/test/skript/tests/regressions/6623-wrong parsing order for math.sk
Labels: bug, 2.8, patch-ready

#6746 Add support for spawning dropped items
  src/main/java/ch/njol/skript/entity/DroppedItemData.java
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/test/skript/tests/regressions/pull-6746-spawn-dropped-item.sk
Labels: bug, 2.8, patch-ready

#6699 Context Switch Enhancements
  src/main/java/ch/njol/skript/events/bukkit/SkriptParseEvent.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/sections/SecConditional.java
Labels: enhancement, feature, feature-ready
