Repository SkriptLang/Skript, pull requests merged in 2024-08, with the labels that each got.

#6932 Fixes an error with SimplifiedChinese language file
  src/main/resources/lang/simplifiedchinese.lang
Labels: bug, 2.9

#6949 Fix missing aliases not regenerating for reloads
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
Labels: bug, 2.9

#6906 Adds new spawn reasons for 1.21
  src/main/resources/lang/default.lang
Labels: enhancement, patch-ready, 2.9

#6948 Delay listening behavior logic until after the event implementation initializes
  src/main/java/ch/njol/skript/events/EvtMove.java
  src/main/java/ch/njol/skript/lang/SkriptEvent.java
Labels: bug, 2.9

#6947 Fix ExprRemainingAir Negative Value Handling
  src/main/java/ch/njol/skript/expressions/ExprRemainingAir.java
  src/test/skript/tests/syntaxes/expressions/ExprRemainingAir.sk
Labels: bug, 2.9

#6910 allow entity emitters to be null, since 1.17 and below don't support them.
  src/main/java/ch/njol/skript/effects/EffPlaySound.java
  src/test/skript/tests/regressions/6907-playsound entity method doesn't exist.sk
Labels: bug, 2.9

#6905 Raise the minimum Java version to 17
  .github/workflows/java-11-builds.yml
  .github/workflows/java-17-builds.yml
  .github/workflows/junit-11-builds.yml
  .github/workflows/junit-17-builds.yml
  README.md
  build.gradle
  code-conventions.md
  src/test/skript/environments/java11/paper-1.13.2.json
  src/test/skript/environments/java11/paper-1.14.4.json
  src/test/skript/environments/java11/paper-1.15.2.json
  src/test/skript/environments/java11/paper-1.16.5.json
  src/test/skript/environments/java17/paper-1.17.1.json
  src/test/skript/environments/java17/paper-1.18.2.json
Labels: enhancement, breaking changes, 2.10

#6873 Allows for multiple return types in ExpressionEntryData
  src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java
Labels: enhancement, feature-ready

#6930 Add trailing empty string ignoring and tests to ExprJoinSplit
  src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java
  src/test/skript/tests/syntaxes/expressions/ExprJoinSplit.sk
Labels: enhancement, feature-ready

#6850 Adds some more taming syntax
  src/main/java/ch/njol/skript/conditions/CondIsTamed.java
  src/main/java/ch/njol/skript/effects/EffTame.java
  src/test/skript/tests/syntaxes/conditions/CondIsTamed.sk
Labels: feature, feature-ready

#6936 Bandaid fix for single quotes in command args
  src/main/java/ch/njol/skript/command/CommandUsage.java
  src/test/skript/tests/regressions/pull-6936-single quotes in commands.sk
Labels: bug, 2.9

#6950 Update EasyMock to 5.4.0; Re-enable JUnitJava21
  .github/workflows/junit-21-builds.yml
  build.gradle
  src/test/skript/junit/BellEvents.sk
Labels: bug, patch-ready, 2.9

#5073 Re-add support for itemtypes in CondIsOfType
  src/main/java/ch/njol/skript/conditions/CondIsOfType.java
  src/test/skript/tests/syntaxes/conditions/CondIsOfType.sk
Labels: bug, patch-ready, 2.9

#5809 Add condition type to fix parsing order
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/conditions/CondCompare.java
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
  src/main/java/ch/njol/skript/lang/Condition.java
  src/test/skript/tests/regressions/5804-is-burning.sk
Labels: bug, enhancement, feature-ready

#6983 Fix EffReturn error message
  src/main/java/ch/njol/skript/effects/EffReturn.java
Labels: bug, patch-ready

#6997 Add explicit sort order to EffSort
  src/main/java/ch/njol/skript/effects/EffSort.java
  src/test/skript/tests/syntaxes/effects/EffSort.sk
Labels: enhancement

#6993 Timespan <-> Duration Conversion methods.
  src/main/java/ch/njol/skript/util/Timespan.java
Labels: enhancement, feature-ready

#6768 Add piglin bartering event
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprBarterDrops.java
  src/main/java/ch/njol/skript/expressions/ExprBarterInput.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtPiglinBarterTest.java
  src/test/skript/junit/-EvtPiglinBarter.sk
  src/test/skript/junit/EvtPiglinBarterTest.sk
Labels: feature, feature-ready

#6860 Update charged syntax
  src/main/java/ch/njol/skript/conditions/CondIsCharged.java
  src/main/java/ch/njol/skript/effects/EffCharge.java
  src/test/skript/tests/syntaxes/conditions/CondIsCharged.sk
  src/test/skript/tests/syntaxes/effects/EffChargeCreeper.sk
Labels: enhancement, feature-ready

#6780 Operators reloading info
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/log/RedirectingLogHandler.java
  src/main/resources/lang/english.lang
Labels: feature, feature-ready, 2.10

#6996 Fix default variables concurrency issues
  src/main/java/ch/njol/skript/structures/StructVariables.java
Labels: bug, 2.9

#6942 Small fix in german.lang and adds dutch.lang
  src/main/resources/lang/dutch.lang
  src/main/resources/lang/german.lang
Labels: bug, enhancement, patch-ready, 2.9

#6984 BStats overhaul
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/config/Option.java
  src/main/java/org/skriptlang/skript/bukkit/SkriptMetrics.java
  src/main/resources/config.sk
Labels: enhancement, patch-ready

#7018 Fix key attribute missing horse
  src/main/resources/lang/default.lang
Labels: bug, patch-ready

#6982 Temporary fix for plural endings error.
  src/main/java/ch/njol/skript/util/Utils.java
  src/test/java/org/skriptlang/skript/test/tests/localization/UtilsPlurals.java
Labels: bug, patch-ready, 2.9
