Repository SkriptLang/Skript, pull requests merged in 2025-01, with the labels that each got.

#7334 Mass-merge for script reflection pull requests.
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/conditions/CondIsLoaded.java
  src/main/java/ch/njol/skript/conditions/CondIsUsingFeature.java
  src/main/java/ch/njol/skript/conditions/CondIsValid.java
  src/main/java/ch/njol/skript/conditions/CondScriptLoaded.java
  src/main/java/ch/njol/skript/config/Config.java
  src/main/java/ch/njol/skript/config/EntryNode.java
  src/main/java/ch/njol/skript/config/Node.java
  src/main/java/ch/njol/skript/config/NodeNavigator.java
  src/main/java/ch/njol/skript/config/SectionNode.java
  src/main/java/ch/njol/skript/config/SimpleNode.java
  src/main/java/ch/njol/skript/config/VoidNode.java
  src/main/java/ch/njol/skript/effects/EffRun.java
  src/main/java/ch/njol/skript/effects/EffScriptFile.java
  src/main/java/ch/njol/skript/expressions/ExprConfig.java
  src/main/java/ch/njol/skript/expressions/ExprFunction.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/main/java/ch/njol/skript/expressions/ExprNode.java
  src/main/java/ch/njol/skript/expressions/ExprNodeValue.java
  src/main/java/ch/njol/skript/expressions/ExprResult.java
  src/main/java/ch/njol/skript/expressions/ExprScript.java
  src/main/java/ch/njol/skript/expressions/ExprScripts.java
  src/main/java/ch/njol/skript/expressions/ExprScriptsOld.java
  src/main/java/ch/njol/skript/expressions/ExprValue.java
  src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/main/java/ch/njol/skript/registrations/Feature.java
  src/main/java/org/skriptlang/skript/lang/script/Script.java
  src/main/java/org/skriptlang/skript/util/Executable.java
  src/main/java/org/skriptlang/skript/util/Validated.java
  src/main/resources/lang/default.lang
  src/test/java/org/skriptlang/skript/test/tests/config/ConfigTest.java
  src/test/java/org/skriptlang/skript/test/tests/files/FilesGenerate.java
  src/test/skript/tests/misc/-disabled.sk
  src/test/skript/tests/misc/dummy.sk
  src/test/skript/tests/misc/legacy script name.sk
  src/test/skript/tests/syntaxes/conditions/CondIsLoaded.sk
  src/test/skript/tests/syntaxes/effects/EffRun.sk
  src/test/skript/tests/syntaxes/effects/EffScriptFile.sk
  src/test/skript/tests/syntaxes/expressions/ExprConfig.sk
  src/test/skript/tests/syntaxes/expressions/ExprFunction.sk
  src/test/skript/tests/syntaxes/expressions/ExprName.sk
  src/test/skript/tests/syntaxes/expressions/ExprNode.sk
  src/test/skript/tests/syntaxes/expressions/ExprNodeValue.sk
  src/test/skript/tests/syntaxes/expressions/ExprResult.sk
  src/test/skript/tests/syntaxes/expressions/ExprScript.sk
Labels: 2.10, don't merge me !!

#7341 Registry Cleanup
  src/main/java/ch/njol/skript/bukkitutil/EnchantmentUtils.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/test/skript/tests/misc/registry.sk
Labels: enhancement, breaking changes, feature-ready, 2.10

#7064 Queue
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/conditions/CondIsEmpty.java
  src/main/java/ch/njol/skript/expressions/ExprDequeuedQueue.java
  src/main/java/ch/njol/skript/expressions/ExprElement.java
  src/main/java/ch/njol/skript/expressions/ExprQueue.java
  src/main/java/ch/njol/skript/expressions/ExprQueueStartEnd.java
  src/main/java/ch/njol/skript/registrations/Feature.java
  src/main/java/org/skriptlang/skript/lang/util/SkriptQueue.java
  src/main/java/org/skriptlang/skript/lang/util/package-info.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprQueue.sk
Labels: feature, feature-ready, 2.10

#7345 Allow plurals in any name-of.
  src/main/java/ch/njol/skript/expressions/ExprAmount.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/test/skript/tests/syntaxes/expressions/ExprName.sk
Labels: bug, 2.10

#7346 Silence unavoidable removal warnings during build & remove getters.
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/bukkitutil/HealthUtils.java
  src/main/java/ch/njol/skript/bukkitutil/SoundUtils.java
  src/main/java/ch/njol/skript/classes/SerializableGetter.java
  src/main/java/ch/njol/skript/command/Commands.java
  src/main/java/ch/njol/skript/effects/EffHidePlayerFromServerList.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/expressions/ExprAnvilRepairCost.java
  src/main/java/ch/njol/skript/expressions/ExprAnvilText.java
  src/main/java/ch/njol/skript/expressions/ExprColorOf.java
  src/main/java/ch/njol/skript/expressions/ExprHoverList.java
  src/main/java/ch/njol/skript/expressions/ExprMaxItemUseTime.java
  src/main/java/ch/njol/skript/lang/SelfRegisteringSkriptEvent.java
  src/main/java/ch/njol/skript/registrations/EventValues.java
  src/main/java/ch/njol/skript/sections/EffSecShoot.java
  src/main/java/ch/njol/skript/timings/SkriptTimings.java
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
  src/main/java/ch/njol/skript/util/PotionDataUtils.java
  src/main/java/ch/njol/skript/util/PotionEffectUtils.java
  src/main/java/ch/njol/skript/util/Task.java
  src/main/java/ch/njol/skript/util/visual/VisualEffects.java
Labels: housekeeping, 2.10

#7127 Minecraft Tags
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/util/Pair.java
  src/main/java/org/skriptlang/skript/bukkit/tags/SkriptTag.java
  src/main/java/org/skriptlang/skript/bukkit/tags/TagModule.java
  src/main/java/org/skriptlang/skript/bukkit/tags/TagRegistry.java
  src/main/java/org/skriptlang/skript/bukkit/tags/TagType.java
  src/main/java/org/skriptlang/skript/bukkit/tags/elements/CondIsTagged.java
  src/main/java/org/skriptlang/skript/bukkit/tags/elements/EffRegisterTag.java
  src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTag.java
  src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTagContents.java
  src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTagKey.java
  src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTagsOf.java
  src/main/java/org/skriptlang/skript/bukkit/tags/elements/ExprTagsOfType.java
  src/main/java/org/skriptlang/skript/bukkit/tags/sources/BukkitTagSource.java
  src/main/java/org/skriptlang/skript/bukkit/tags/sources/CustomTagSource.java
  src/main/java/org/skriptlang/skript/bukkit/tags/sources/PaperTagSource.java
  src/main/java/org/skriptlang/skript/bukkit/tags/sources/SkriptTagSource.java
  src/main/java/org/skriptlang/skript/bukkit/tags/sources/TagOrigin.java
  src/main/java/org/skriptlang/skript/bukkit/tags/sources/TagSource.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/conditions/CondIsTagged.sk
  src/test/skript/tests/syntaxes/effects/EffRegisterTag.sk
  src/test/skript/tests/syntaxes/expressions/ExprTagContents.sk
  src/test/skript/tests/syntaxes/expressions/ExprTagsOf.sk
  src/test/skript/tests/syntaxes/expressions/ExprTagsOfType.sk
Labels: feature, feature-ready, 2.10

#7350 Fix color chars not being registered
  src/main/java/ch/njol/skript/util/chat/ChatMessages.java
Labels: bug, 2.10

#7348 Fix tests for Windows computers & add test functions.
  src/main/java/ch/njol/skript/test/runner/EffAssert.java
  src/main/java/ch/njol/skript/test/runner/TestFunctions.java
  src/test/skript/README.md
  src/test/skript/tests/misc/legacy script name.sk
  src/test/skript/tests/syntaxes/expressions/ExprBookAuthor.sk
  src/test/skript/tests/syntaxes/expressions/ExprBookTitle.sk
  src/test/skript/tests/syntaxes/expressions/ExprScript.sk
  src/test/skript/tests/syntaxes/expressions/ExprStringCase.sk
  src/test/skript/tests/syntaxes/functions/caseEquals.sk
  src/test/skript/tests/syntaxes/functions/case_equals.sk
  src/test/skript/tests/syntaxes/functions/offlineplayer.sk
Labels: bug, housekeeping, 2.10

#7155 Runtime errors
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptConfig.java
  src/main/java/ch/njol/skript/config/Node.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/expressions/base/SimplePropertyExpression.java
  src/main/java/ch/njol/skript/lang/Condition.java
  src/main/java/ch/njol/skript/lang/Effect.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/SyntaxElement.java
  src/main/java/ch/njol/skript/util/visual/VisualEffect.java
  src/main/java/org/skriptlang/skript/bukkit/log/runtime/BukkitRuntimeErrorConsumer.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
  src/main/java/org/skriptlang/skript/log/runtime/ErrorSource.java
  src/main/java/org/skriptlang/skript/log/runtime/Frame.java
  src/main/java/org/skriptlang/skript/log/runtime/RuntimeError.java
  src/main/java/org/skriptlang/skript/log/runtime/RuntimeErrorConsumer.java
  src/main/java/org/skriptlang/skript/log/runtime/RuntimeErrorManager.java
  src/main/java/org/skriptlang/skript/log/runtime/RuntimeErrorProducer.java
  src/main/java/org/skriptlang/skript/log/runtime/SyntaxRuntimeErrorProducer.java
  src/main/resources/config.sk
  src/main/resources/lang/english.lang
  src/main/resources/plugin.yml
Labels: feature, feature-ready, 2.10

#7028 Add list transformation expression and effect
  src/main/java/ch/njol/skript/classes/ClassInfo.java
  src/main/java/ch/njol/skript/effects/EffSort.java
  src/main/java/ch/njol/skript/effects/EffTransform.java
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
  src/main/java/ch/njol/skript/expressions/ExprTransform.java
  src/main/java/ch/njol/skript/lang/InputSource.java
  src/main/java/ch/njol/skript/sections/SecFilter.java
  src/test/skript/tests/syntaxes/effects/EffTransform.sk
  src/test/skript/tests/syntaxes/expressions/ExprTransform.sk
  src/test/skript/tests/syntaxes/sections/SecFilter.sk
Labels: feature, feature-ready, 2.10

#7116 Slight Exception message changes
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/update/ReleaseStatus.java
Labels: enhancement, feature-ready, 2.10

#7338 BukkitEventValues - remove future event-block for block break event
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: breaking changes, feature-ready, 2.10

#7337 Tests - name consistency
  src/test/skript/tests/regressions/2584-health-utils-update.sk
  src/test/skript/tests/regressions/5566-block iterator being 100 always.sk
  src/test/skript/tests/regressions/5748-fix bugs in the random number expression.sk
  src/test/skript/tests/regressions/6361-function-param.sk
  src/test/skript/tests/regressions/6586-effhealth item mutation.sk
  src/test/skript/tests/regressions/6600-variable-set-changer-aiiob.sk
  src/test/skript/tests/regressions/6687-enchantment-update.sk
  src/test/skript/tests/regressions/6746-spawn-dropped-item.sk
  src/test/skript/tests/regressions/6760-particle itemtype conflicts.sk
  src/test/skript/tests/regressions/6832-potioneffecttype-compare.sk
  src/test/skript/tests/regressions/6936-single quotes in commands.sk
  src/test/skript/tests/regressions/7024-efflook-stack-trace
  src/test/skript/tests/regressions/7067-events in structs.sk
  src/test/skript/tests/regressions/7120-changes overwriting indices.sk
  src/test/skript/tests/regressions/7129-pretty-quotes.sk
Labels: enhancement, feature-ready, 2.10

#7217 ItemUtils#changeItemMeta, #setItem
  src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java
Labels: feature, feature-ready, 2.10

#6498 Add teleport flags
  src/main/java/ch/njol/skript/bukkitutil/EntityUtils.java
  src/main/java/ch/njol/skript/bukkitutil/SkriptTeleportFlag.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/effects/EffTeleport.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/effects/EffTeleport.sk
Labels: feature, 2.10

#7352 Villager expression updates
  src/main/java/ch/njol/skript/expressions/ExprVillagerProfession.java
  src/main/java/ch/njol/skript/expressions/ExprVillagerType.java
Labels: enhancement, 2.10

#7353 HTMLGenerator - fix new lines not showing in docs
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
Labels: documentation, feature-ready

#7370 ExprName - combine elements and cleanup docs
  src/main/java/ch/njol/skript/expressions/ExprName.java
Labels: enhancement, feature-ready

#7371 Increase test delay time.
  src/main/java/ch/njol/skript/Skript.java
Labels: bug, feature-ready, 2.10

#7369 Make sure the alias submodule updates via the correct branch
  .gitmodules
Labels: bug, feature-ready

#7357 Fix fishing event docs
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EvtFish.java
Labels: enhancement, documentation, feature-ready

#7366 Fix wrong unknown nullability on suppress warning enum
  src/main/java/org/skriptlang/skript/lang/script/ScriptWarning.java
Labels: enhancement

#7381 Since (annotation) - support multiple lines
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/doc/JSONGenerator.java
  src/main/java/ch/njol/skript/doc/Since.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
Labels: enhancement, documentation

#7383 Fix missing newline and handle syntaxes without documentation in Runtime Errors.
  src/main/java/org/skriptlang/skript/log/runtime/ErrorSource.java
  src/main/resources/lang/english.lang
Labels: bug

#7390 SkriptCommand - fix test command again
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/SkriptCommandTabCompleter.java
Labels: bug, 2.10

#7391 Supports multiple commands in EvtCommand
  src/main/java/ch/njol/skript/events/EvtCommand.java
  src/test/skript/tests/syntaxes/structures/EvtCommand.sk
Labels: bug, enhancement, 2.10

#7368 DocumentationIdProvider - fix getId methods returning "2"
  src/main/java/ch/njol/skript/doc/DocumentationIdProvider.java
Labels: bug

#7398 ParserInstance - fix throwing errors in effect commands
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
Labels: bug

#7396 HTMLGenerator - fix new line in "since" not working
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
Labels: enhancement, documentation, require docs update

#7409 Fix Duplicate Secspression Logging
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/patterns/TypePatternElement.java
  src/test/skript/tests/misc/expression sections.sk
Labels: bug, 2.10

#7410 ScriptLoader - fix error catching
  src/main/java/ch/njol/skript/ScriptLoader.java
Labels: bug

#7382 Re-add backwards-compatible Getter methods to EventValues
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/registrations/EventValues.java
Labels: bug, feature-ready, 2.10

#7379 Fix tests running while world has not loaded
  src/main/java/ch/njol/skript/Skript.java
Labels: bug, unit testing, feature-ready

#7404 Adds second pattern to ExprVectorFromYawAndPitch
  src/main/java/ch/njol/skript/expressions/ExprVectorFromYawAndPitch.java
Labels: enhancement, feature-ready

#7424 Fix config updating adding nodes incorrectly
  src/main/java/ch/njol/skript/config/Config.java
  src/main/java/ch/njol/skript/config/Node.java
  src/main/java/ch/njol/skript/config/SectionNode.java
  src/test/java/ch/njol/skript/config/ConfigHelper.java
  src/test/java/ch/njol/skript/config/ConfigTest.java
  src/test/java/ch/njol/skript/config/NodeTest.java
  src/test/java/org/skriptlang/skript/test/tests/config/package-info.java
  src/test/resources/new-config.sk
  src/test/resources/old-config.sk
Labels: bug, priority: high, 2.10

#7425 Fix config sub-node duplication.
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/config/Config.java
  src/main/java/ch/njol/skript/config/EntryNode.java
  src/test/java/ch/njol/skript/config/ConfigTest.java
  src/test/java/ch/njol/skript/config/NodeTest.java
  src/test/resources/new-config.sk
  src/test/resources/old-config.sk
Labels: bug, 2.10

#7378 Fix JUnit warnings on test runs
  src/main/java/ch/njol/skript/events/EvtFirework.java
  src/main/java/ch/njol/skript/localization/Adjective.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/test/java/org/skriptlang/skript/test/tests/files/BackupPurgeTest.java
  src/test/skript/junit/CancelledEventTest.sk
  src/test/skript/junit/EvtFurnaceTest.sk
  src/test/skript/junit/PlayerElytraBoostEventTest.sk
Labels: unit testing, feature-ready, housekeeping

#7356 Compatiblity patch for abandoned addons.
  src/main/java/ch/njol/skript/classes/Converter.java
  src/main/java/ch/njol/skript/registrations/Converters.java
  src/main/java/ch/njol/skript/util/Utils.java
Labels: up for debate, housekeeping, 2.10

#7392 adds delay checks to input key syntaxes
  src/main/java/org/skriptlang/skript/bukkit/input/elements/conditions/CondIsPressingKey.java
  src/main/java/org/skriptlang/skript/bukkit/input/elements/expressions/ExprCurrentInputKeys.java
Labels: bug, 2.10

#7359 Allow addons to use the `%classinfo% value` property expression.
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/config/EntryNode.java
  src/main/java/ch/njol/skript/expressions/ExprValue.java
  src/main/java/ch/njol/skript/lang/util/common/AnyValued.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/resources/lang/default.lang
Labels: feature

#7333 Registration API Fixes/Enhancements
  src/main/java/ch/njol/skript/ModernSkriptBridge.java
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/SkriptAddon.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/java/ch/njol/skript/test/runner/StructTestEntryContainer.java
  src/main/java/org/skriptlang/skript/SkriptImpl.java
  src/main/java/org/skriptlang/skript/bukkit/registration/BukkitSyntaxInfos.java
  src/main/java/org/skriptlang/skript/bukkit/registration/BukkitSyntaxInfosImpl.java
  src/main/java/org/skriptlang/skript/registration/DefaultSyntaxInfos.java
  src/main/java/org/skriptlang/skript/registration/DefaultSyntaxInfosImpl.java
  src/main/java/org/skriptlang/skript/registration/SyntaxInfo.java
  src/main/java/org/skriptlang/skript/registration/SyntaxInfoImpl.java
  src/main/java/org/skriptlang/skript/registration/SyntaxRegistry.java
  src/main/java/org/skriptlang/skript/registration/SyntaxRegistryImpl.java
  src/main/java/org/skriptlang/skript/util/Builder.java
  src/main/java/org/skriptlang/skript/util/ClassLoader.java
  src/main/java/org/skriptlang/skript/util/PriorityImpl.java
  src/test/java/org/skriptlang/skript/SkriptTest.java
  src/test/java/org/skriptlang/skript/addon/BaseSkriptAddonTests.java
  src/test/java/org/skriptlang/skript/addon/SkriptAddonTest.java
  src/test/java/org/skriptlang/skript/bukkit/registration/EventSyntaxInfoTest.java
  src/test/java/org/skriptlang/skript/registration/BaseSyntaxInfoTests.java
  src/test/java/org/skriptlang/skript/registration/ExpressionSyntaxInfoTest.java
  src/test/java/org/skriptlang/skript/registration/KeyTest.java
  src/test/java/org/skriptlang/skript/registration/StructureSyntaxInfoTest.java
  src/test/java/org/skriptlang/skript/registration/SyntaxInfoTest.java
  src/test/java/org/skriptlang/skript/registration/SyntaxRegistryTest.java
  src/test/java/org/skriptlang/skript/test/junit/registration/ExprJUnitTestName.java
  src/test/java/org/skriptlang/skript/test/tests/files/FilesGenerateTest.java
  src/test/java/org/skriptlang/skript/test/tests/localization/UtilsPluralsTest.java
  src/test/java/org/skriptlang/skript/test/tests/regression/BlockDataNotCloned6829Test.java
  src/test/java/org/skriptlang/skript/util/ClassLoaderTest.java
  src/test/java/org/skriptlang/skript/util/ClassUtilsTest.java
  src/test/java/org/skriptlang/skript/util/PriorityTest.java
Labels: bug, enhancement, 2.10

#7363 Clarify CIP edge case behavior and add type safety guard
  src/main/java/ch/njol/skript/classes/Changer.java
  src/main/java/ch/njol/skript/lang/Expression.java
Labels: enhancement

#7430 Fix Example Scripts
  src/main/java/ch/njol/skript/Skript.java
  src/main/resources/scripts/-examples/commands.sk
  src/main/resources/scripts/-examples/functions.sk
  src/main/resources/scripts/-examples/loops.sk
  src/main/resources/scripts/-examples/options and meta.sk
Labels: bug, enhancement, 2.10

#7340 ExprTypeOf - add support for EnchantmentType
  src/main/java/ch/njol/skript/expressions/ExprTypeOf.java
  src/test/skript/tests/syntaxes/expressions/ExprTypeOf.sk
Labels: enhancement, 2.10

#7444 Examples for the experimental features.
  src/main/java/ch/njol/skript/expressions/ExprQueue.java
  src/main/java/ch/njol/skript/registrations/Feature.java
  src/main/java/ch/njol/skript/sections/SecFor.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/main/java/ch/njol/skript/structures/StructExample.java
  src/main/java/org/skriptlang/skript/lang/util/SkriptQueue.java
  src/main/resources/scripts/-examples/chest menus.sk
  src/main/resources/scripts/-examples/commands.sk
  src/main/resources/scripts/-examples/events.sk
  src/main/resources/scripts/-examples/experimental features/for loops.sk
  src/main/resources/scripts/-examples/experimental features/queues.sk
  src/main/resources/scripts/-examples/experimental features/script reflection.sk
  src/main/resources/scripts/-examples/functions.sk
  src/main/resources/scripts/-examples/loops.sk
  src/main/resources/scripts/-examples/options and meta.sk
  src/main/resources/scripts/-examples/text formatting.sk
  src/main/resources/scripts/-examples/timings.sk
  src/main/resources/scripts/-examples/variables.sk
  src/test/skript/tests/syntaxes/expressions/ExprQueue.sk
  src/test/skript/tests/syntaxes/expressions/ExprScript.sk
  src/test/skript/tests/syntaxes/structures/StructExample.sk
Labels: bug, housekeeping, 2.10

#7503 ExprName - fix not being able to get/set name of block
  src/main/java/ch/njol/skript/classes/data/DefaultConverters.java
  src/main/java/ch/njol/skript/expressions/ExprName.java
  src/test/skript/tests/syntaxes/expressions/ExprName.sk
Labels: bug, patch-ready

#7455 Fix queue serialisation.
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/org/skriptlang/skript/lang/util/SkriptQueue.java
Labels: bug, 2.10

#7519 Fix a conflict with EffSend and EffConnect
  src/main/java/ch/njol/skript/effects/EffConnect.java
  src/test/java/org/skriptlang/skript/test/tests/regression/EffSendEffConnectConflict7517Test.java
Labels: bug, patch-ready

#7537 Fix loop behaviour from super call.
  src/main/java/ch/njol/skript/sections/SecFor.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/main/java/org/skriptlang/skript/lang/util/SkriptQueue.java
  src/test/skript/tests/regressions/7536-for-loop-ending.sk
  src/test/skript/tests/syntaxes/sections/SecFor.sk
Labels: bug, 2.11

#7534 Parsing stack (#5277)
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/parser/ParseStackOverflowException.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/lang/parser/ParsingStack.java
Labels: feature
