Repository SkriptLang/Skript, pull requests merged in 2025-05, with the labels that each got.

#7838 Clarify Create Virtual WorldBorder docs and behavior
  src/main/java/ch/njol/skript/expressions/ExprSecCreateWorldBorder.java
Labels: enhancement, documentation, patch-ready

#7827 Update ExprSecCreateWorldBorder
  src/main/java/ch/njol/skript/sections/ExprSecCreateWorldBorder.java
Labels: bug, patch-ready

#7828 Update Examples to Reflect Alias Changes
  src/main/java/ch/njol/skript/classes/data/SkriptClasses.java
  src/main/java/ch/njol/skript/conditions/CondIsEdible.java
  src/main/java/ch/njol/skript/conditions/CondIsEnchanted.java
  src/main/java/ch/njol/skript/conditions/CondIsFlammable.java
  src/main/java/ch/njol/skript/conditions/CondIsWearing.java
  src/main/java/ch/njol/skript/conditions/CondItemInHand.java
  src/main/java/ch/njol/skript/effects/EffEquip.java
  src/main/java/ch/njol/skript/events/EvtBlock.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprAmountOfItems.java
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/main/java/ch/njol/skript/expressions/ExprBarterDrops.java
  src/main/java/ch/njol/skript/expressions/ExprBlock.java
  src/main/java/ch/njol/skript/expressions/ExprColorOf.java
  src/main/java/ch/njol/skript/expressions/ExprDamagedItem.java
  src/main/java/ch/njol/skript/expressions/ExprItems.java
  src/main/java/ch/njol/skript/expressions/ExprTool.java
  src/main/java/ch/njol/skript/expressions/ExprXOf.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/conditions/CondIsLootable.java
Labels: bug, documentation, patch-ready

#7809 Fix StackOverflow in variable parsing
  src/main/java/ch/njol/skript/variables/FlatFileStorage.java
Labels: bug, patch-ready

#7775 Fix double evaluation when using VariableStrings with EffBroadcast.
  src/main/java/ch/njol/skript/effects/EffBroadcast.java
  src/main/java/ch/njol/skript/lang/VariableString.java
  src/test/skript/tests/regressions/7718-broadcast evaluates vstrings twice.sk
Labels: bug, patch-ready

#7698 Allow plural types in docs.json
  src/main/java/ch/njol/skript/doc/JSONGenerator.java
Labels: bug, documentation, patch-ready

#7829 EffSecShoot Fix Sections/Consumers
  src/main/java/ch/njol/skript/sections/EffSecShoot.java
  src/test/skript/tests/syntaxes/sections/EffSecShoot.sk
Labels: bug, patch-ready

#7845 Lang Types An Fix
  src/main/resources/lang/default.lang
Labels: bug, patch-ready

#7826 Cleanup Tests
  src/test/skript/tests/regressions/2581-all potions are water.sk
  src/test/skript/tests/regressions/4938-time played.sk
  src/test/skript/tests/regressions/6907-playsound entity method doesn't exist.sk
  src/test/skript/tests/syntaxes/effects/EffVisualEffect.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityAttribute.sk
Labels: patch-ready, housekeeping

#4154 Introduces toggle effect & expression
  src/main/java/ch/njol/skript/effects/EffToggle.java
  src/main/java/ch/njol/skript/expressions/ExprInverse.java
  src/test/skript/tests/syntaxes/effects/EffToggle.sk
Labels: enhancement, feature-ready

#7850 Properly Check Nested Lists in LiteralUtils.hasUnparsedLiteral()
  src/main/java/ch/njol/skript/util/LiteralUtils.java
  src/test/skript/tests/regressions/7850-invalid nested list throws exception.sk
Labels: bug, patch-ready

#7323 Add Indices of X in List
  src/main/java/ch/njol/skript/expressions/ExprIndexOf.java
  src/main/java/ch/njol/skript/expressions/ExprIndicesOf.java
  src/test/skript/tests/syntaxes/expressions/ExprIndicesOf.sk
Labels: enhancement, breaking changes, feature-ready

#7846 Pig Variants
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/entity/PigData.java
  src/main/java/ch/njol/skript/entity/WolfData.java
  src/main/java/ch/njol/skript/util/PaperUtils.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: enhancement, feature-ready

#7870 Update PR Template
  .github/pull_request_template.md
Labels: github related, patch-ready

#7889 Use StopTrigger ExecutionIntent in EffExit when applicable
  src/main/java/ch/njol/skript/effects/EffExit.java
Labels: bug, patch-ready

#7890 Use proper deprecation warning for ExprNoDamageTicks
  src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java
  src/test/skript/tests/syntaxes/expressions/ExprNoDamageTicks.sk
Labels: bug, enhancement, patch-ready

#7886 Properly Handle Blockdata in Click Event
  src/main/java/ch/njol/skript/events/EvtClick.java
Labels: bug, patch-ready
