Repository SkriptLang/Skript, pull requests merged in 2025-06, with the labels that each got.

#7746 EvtVillagerCareerChange
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/resources/lang/default.lang
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtVillagerCareerChangeTest.java
  src/test/skript/junit/EvtVillagerCareerChangeTest.sk
Labels: enhancement, feature-ready

#6902 Brush-related expressions
  src/main/java/ch/njol/skript/expressions/ExprBrushableItem.java
  src/main/java/ch/njol/skript/expressions/ExprDustedStage.java
  src/test/skript/tests/syntaxes/expressions/ExprDusted.sk
Labels: feature, feature-ready

#7685 Catalan Language
  src/main/resources/config.sk
  src/main/resources/lang/catalan.lang
Labels: feature-ready, translation

#7748 Strider Support
  src/main/java/ch/njol/skript/conditions/CondStriderIsShivering.java
  src/main/java/ch/njol/skript/effects/EffStriderShivering.java
  src/main/java/ch/njol/skript/entity/StriderData.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/misc/striderdata.sk
  src/test/skript/tests/syntaxes/effects/EffStriderShivering.sk
Labels: feature, feature-ready

#7791 SkriptJUnitTest#spawnTestEntity + Cleanup
  src/main/java/ch/njol/skript/test/runner/SkriptJUnitTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffGoatHornsTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/BellEventsTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtBreedTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtBucketEntityTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtFireworkTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtFishTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtPiglinBarterTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtVehicleCollisionTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/PlayerElytraBoostEventTest.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprAffectedEntitiesTest.java
Labels: feature, feature-ready

#7803 add 'along' to push pattern, cleanup code
  src/main/java/ch/njol/skript/effects/EffPush.java
Labels: enhancement, feature-ready

#7905 EntityData Event Value
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: feature, feature-ready

#7928 Fix EffSort clobbering duplicate inputs
  src/main/java/ch/njol/skript/effects/EffSort.java
  src/test/skript/tests/regressions/7926-eff sort doesn't allow duplicate values.sk
Labels: bug, patch-ready

#7927 PropertyCondition#getExpr
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
Labels: enhancement, feature-ready

#7913 Create the aliases folder
  src/main/java/ch/njol/skript/Skript.java
Labels: enhancement, feature-ready

#7935 Fixes examples of worldborder expand/shrink effect
  src/main/java/ch/njol/skript/effects/EffWorldBorderExpand.java
Labels: documentation, patch-ready

#7933 Scientific notation
  src/main/java/ch/njol/skript/classes/data/JavaClasses.java
  src/test/skript/tests/misc/scientific notation.sk
Labels: enhancement, feature-ready

#7915 EffChange Cleanup
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/lang/Expression.java
Labels: enhancement, feature-ready

#7931 Add tolerance to divisible by condition
  src/main/java/ch/njol/skript/conditions/CondIsDivisibleBy.java
  src/test/skript/tests/syntaxes/conditions/CondIsDivisibleBy.sk
Labels: bug, patch-ready

#7947 Comparing EnchantmentType to Enchantment
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/util/EnchantmentType.java
  src/test/skript/tests/regressions/7947-comparing enchantment type to enchantment.sk
Labels: bug, feature-ready

#7944 Tweak the pattern and description of ExprTarget
  src/main/java/ch/njol/skript/expressions/ExprTarget.java
Labels: enhancement, patch-ready

#7891 Return type accuracy and usage improvements
  src/main/java/ch/njol/skript/effects/EffToggle.java
  src/main/java/ch/njol/skript/effects/EffVisualEffect.java
  src/main/java/ch/njol/skript/events/EvtClick.java
  src/main/java/ch/njol/skript/expressions/ExprAge.java
  src/main/java/ch/njol/skript/expressions/ExprAttacker.java
  src/main/java/ch/njol/skript/expressions/ExprBannerPatterns.java
  src/main/java/ch/njol/skript/expressions/ExprBeaconValues.java
  src/main/java/ch/njol/skript/expressions/ExprColorOf.java
  src/main/java/ch/njol/skript/expressions/ExprDefaultValue.java
  src/main/java/ch/njol/skript/expressions/ExprElement.java
  src/main/java/ch/njol/skript/expressions/ExprFacing.java
  src/main/java/ch/njol/skript/expressions/ExprFilter.java
  src/main/java/ch/njol/skript/expressions/ExprInput.java
  src/main/java/ch/njol/skript/expressions/ExprLastAttacker.java
  src/main/java/ch/njol/skript/expressions/ExprLoopValue.java
  src/main/java/ch/njol/skript/expressions/ExprMetadata.java
  src/main/java/ch/njol/skript/expressions/ExprNamed.java
  src/main/java/ch/njol/skript/expressions/ExprReversedList.java
  src/main/java/ch/njol/skript/expressions/ExprShuffledList.java
  src/main/java/ch/njol/skript/expressions/ExprSortedList.java
  src/main/java/ch/njol/skript/expressions/ExprTernary.java
  src/main/java/ch/njol/skript/expressions/ExprTransform.java
  src/main/java/ch/njol/skript/expressions/ExprTypeOf.java
  src/main/java/ch/njol/skript/expressions/ExprXOf.java
  src/main/java/ch/njol/skript/lang/Expression.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/lang/function/ExprFunctionCall.java
  src/main/java/ch/njol/skript/lang/util/ConvertedExpression.java
  src/main/java/ch/njol/skript/sections/SecFor.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/main/java/ch/njol/skript/test/runner/ExprKeyValueSet.java
  src/main/java/ch/njol/skript/test/runner/ExprTestLoopPeeking.java
  src/test/skript/tests/syntaxes/expressions/ExprDefaultValue.sk
  src/test/skript/tests/syntaxes/expressions/ExprTernary.sk
Labels: bug, enhancement, needs testing, feature-ready

#7832 Remove 1.16-1.18 Reflection Checks
  src/main/java/ch/njol/skript/aliases/AliasesProvider.java
  src/main/java/ch/njol/skript/bukkitutil/WorldUtils.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/main/java/ch/njol/skript/conditions/CondAnchorWorks.java
  src/main/java/ch/njol/skript/conditions/CondEntityIsInLiquid.java
  src/main/java/ch/njol/skript/conditions/CondEntityIsWet.java
  src/main/java/ch/njol/skript/conditions/CondIsClimbing.java
  src/main/java/ch/njol/skript/conditions/CondIsLeftHanded.java
  src/main/java/ch/njol/skript/conditions/CondIsPreferredTool.java
  src/main/java/ch/njol/skript/conditions/CondIsWhitelisted.java
  src/main/java/ch/njol/skript/conditions/CondIsWithin.java
  src/main/java/ch/njol/skript/conditions/CondLeashWillDrop.java
  src/main/java/ch/njol/skript/conditions/CondRespawnLocation.java
  src/main/java/ch/njol/skript/effects/EffApplyBoneMeal.java
  src/main/java/ch/njol/skript/effects/EffCancelItemUse.java
  src/main/java/ch/njol/skript/effects/EffEnforceWhitelist.java
  src/main/java/ch/njol/skript/effects/EffForceAttack.java
  src/main/java/ch/njol/skript/effects/EffMessage.java
  src/main/java/ch/njol/skript/effects/EffStopSound.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/java/ch/njol/skript/events/EvtItem.java
  src/main/java/ch/njol/skript/events/EvtMove.java
  src/main/java/ch/njol/skript/events/EvtPressurePlate.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprBreakSpeed.java
  src/main/java/ch/njol/skript/expressions/ExprCharges.java
  src/main/java/ch/njol/skript/expressions/ExprMaxPlayers.java
  src/main/java/ch/njol/skript/expressions/ExprMoonPhase.java
  src/main/java/ch/njol/skript/expressions/ExprQuitReason.java
  src/main/java/ch/njol/skript/util/AABB.java
Labels: patch-ready, housekeeping

#7808 Add warning for ambiguous arg subtraction
  src/main/java/ch/njol/skript/expressions/ExprArgument.java
  src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java
Labels: enhancement, patch-ready

#7957 Paper 1.21.6 Update
  build.gradle
  gradle.properties
  src/main/resources/lang/default.lang
  src/test/skript/environments/java21/paper-1.21.6.json
Labels: bug, enhancement, patch-ready

#7964 Enforce main thread when changing variables during structure loading
  src/main/java/ch/njol/skript/structures/StructVariables.java
  src/main/java/ch/njol/skript/test/runner/StructParse.java
Labels: bug, patch-ready

#7976 Fix ExprArithmetic Type Resolutions
  src/main/java/ch/njol/skript/expressions/arithmetic/ExprArithmetic.java
  src/main/java/org/skriptlang/skript/lang/arithmetic/Arithmetics.java
  src/test/skript/tests/syntaxes/expressions/ExprArithmetic.sk
Labels: bug, feature-ready

#7971 Pig Variant Update + EntityData JavaDocs
  src/main/java/ch/njol/skript/entity/AxolotlData.java
  src/main/java/ch/njol/skript/entity/BeeData.java
  src/main/java/ch/njol/skript/entity/BoatChestData.java
  src/main/java/ch/njol/skript/entity/BoatData.java
  src/main/java/ch/njol/skript/entity/CatData.java
  src/main/java/ch/njol/skript/entity/CreeperData.java
  src/main/java/ch/njol/skript/entity/DroppedItemData.java
  src/main/java/ch/njol/skript/entity/EndermanData.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/FallingBlockData.java
  src/main/java/ch/njol/skript/entity/FoxData.java
  src/main/java/ch/njol/skript/entity/FrogData.java
  src/main/java/ch/njol/skript/entity/GoatData.java
  src/main/java/ch/njol/skript/entity/LlamaData.java
  src/main/java/ch/njol/skript/entity/MinecartData.java
  src/main/java/ch/njol/skript/entity/MooshroomData.java
  src/main/java/ch/njol/skript/entity/OcelotData.java
  src/main/java/ch/njol/skript/entity/PandaData.java
  src/main/java/ch/njol/skript/entity/ParrotData.java
  src/main/java/ch/njol/skript/entity/PigData.java
  src/main/java/ch/njol/skript/entity/RabbitData.java
  src/main/java/ch/njol/skript/entity/SalmonData.java
  src/main/java/ch/njol/skript/entity/SheepData.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/java/ch/njol/skript/entity/StriderData.java
  src/main/java/ch/njol/skript/entity/ThrownPotionData.java
  src/main/java/ch/njol/skript/entity/TropicalFishData.java
  src/main/java/ch/njol/skript/entity/VillagerData.java
  src/main/java/ch/njol/skript/entity/WolfData.java
  src/main/java/ch/njol/skript/entity/XpOrbData.java
  src/main/java/ch/njol/skript/entity/ZombieVillagerData.java
  src/main/java/org/skriptlang/skript/bukkit/displays/DisplayData.java
  src/main/resources/lang/default.lang
Labels: enhancement, feature-ready

#7972 EntityData Parse Tags
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/resources/lang/default.lang
Labels: enhancement, feature-ready

#7256 API for custom default values during parsing.
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/parser/DefaultValueData.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/test/runner/ExprDefaultNumberValue.java
  src/main/java/ch/njol/skript/test/runner/SecCustomDefault.java
  src/test/skript/tests/misc/custom default values.sk
Labels: enhancement, feature-ready

#7707 Add support for itemstacks in item cooldown expression/condition
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/conditions/CondHasItemCooldown.java
  src/main/java/ch/njol/skript/expressions/ExprItemCooldown.java
Labels: enhancement, feature-ready
