Repository SkriptLang/Skript, pull requests merged in 2025-10, with the labels that each got.

#8206 Runtime error for when EffSort aborts due to null value
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/effects/EffBlockUpdate.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/effects/EffSort.java
  src/main/java/ch/njol/skript/events/EvtRealTime.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/Statement.java
  src/main/java/ch/njol/skript/variables/Variables.java
  src/test/skript/tests/regressions/8187-functions behave wrong with all default args.sk
  src/test/skript/tests/regressions/8199-parse exprsecs in function args.sk
  src/test/skript/tests/syntaxes/effects/EffSort.sk
Labels: bug, feature-ready

#7888 ExprMidpoint
  src/main/java/ch/njol/skript/expressions/ExprMidpoint.java
  src/test/skript/tests/syntaxes/expressions/ExprMidpoint.sk
Labels: feature, feature-ready

#7878 EffForceAttack Damage Entity By Amount
  src/main/java/ch/njol/skript/effects/EffForceAttack.java
  src/test/skript/tests/syntaxes/effects/EffForceAttack.sk
Labels: enhancement, feature-ready

#8134 Add ExprTimeLived
  src/main/java/ch/njol/skript/expressions/ExprTimeLived.java
Labels: feature, feature-ready

#8064 Fixes and update Minecarts
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/MinecartData.java
Labels: bug, patch-ready

#7275 Brewing Stand Support
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/events/EvtItem.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/BrewingModule.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/CondBrewingConsume.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/EffBrewingConsume.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/EvtBrewingComplete.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/EvtBrewingFuel.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/EvtBrewingStart.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/ExprBrewingFuelLevel.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/ExprBrewingResults.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/ExprBrewingSlot.java
  src/main/java/org/skriptlang/skript/bukkit/brewing/elements/ExprBrewingTime.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/BrewingEventsTest.java
  src/test/skript/junit/BrewingEventsTest.sk
  src/test/skript/tests/syntaxes/expressions/ExprBrewingFuelLevel.sk
  src/test/skript/tests/syntaxes/expressions/ExprBrewingSlot.sk
Labels: enhancement

#8213 Fix getting java functions causing casting errors
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/doc/DocumentationIdProvider.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/doc/JSONGenerator.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
Labels: feature-ready
