Repository SkriptLang/Skript, pull requests merged in 2025-09, with the labels that each got.

#8171 ExprReversedList Fix
  src/main/java/ch/njol/skript/expressions/ExprReversedList.java
  src/test/skript/tests/regressions/8170-reversed-single.sk
Labels: bug, patch-ready

#8172 Prepare for release (2.12.2)
  gradle.properties
Labels: patch-ready

#8116 JSONGenerator for addons and `docs.json` improvements
  .github/workflows/docs/generate-docs/action.yml
  src/main/java/ch/njol/skript/SkriptCommand.java
  src/main/java/ch/njol/skript/doc/DocumentationGenerator.java
  src/main/java/ch/njol/skript/doc/DocumentationIdProvider.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/doc/JSONGenerator.java
  src/main/java/ch/njol/skript/structures/StructEvent.java
Labels: enhancement, documentation, breaking changes, feature-ready

#8180 Change registerExpression() parameter name
  src/main/java/ch/njol/skript/Skript.java
Labels: patch-ready

#8189 Fix type-aware function parsing for functions with only optional arguments
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/regressions/8187-functions behave wrong with all default args.sk
Labels: bug, patch-ready

#8150 SimplifiedCondition
  src/main/java/ch/njol/skript/conditions/CondAlphanumeric.java
  src/main/java/ch/njol/skript/conditions/CondCompare.java
  src/main/java/ch/njol/skript/conditions/CondContains.java
  src/main/java/ch/njol/skript/conditions/CondDate.java
  src/main/java/ch/njol/skript/conditions/CondIsFuel.java
  src/main/java/ch/njol/skript/conditions/CondIsInfinite.java
  src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
  src/main/java/ch/njol/skript/conditions/CondMatches.java
  src/main/java/ch/njol/skript/conditions/CondMinecraftVersion.java
  src/main/java/ch/njol/skript/conditions/CondPastFuture.java
  src/main/java/ch/njol/skript/conditions/CondStartsEndsWith.java
  src/main/java/ch/njol/skript/lang/Condition.java
  src/main/java/ch/njol/skript/lang/SimplifiedCondition.java
  src/main/java/ch/njol/skript/test/runner/CondMethodExists.java
  src/main/java/org/skriptlang/skript/lang/script/ScriptWarning.java
Labels: enhancement, feature-ready

#7797 Use the gradle properties for the latest environment reference
  build.gradle
Labels: enhancement, feature-ready

#8196 Runtime error when calculating distance between different worlds
  src/main/java/ch/njol/skript/expressions/ExprDistance.java
Labels: enhancement, feature-ready

#7464 Script development auto reloading on save
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/structures/StructAutoReload.java
  src/main/java/org/skriptlang/skript/lang/structure/Structure.java
  src/main/resources/lang/english.lang
Labels: feature-ready, needs reviews

#8101 Feature/players listed
  src/main/java/ch/njol/skript/expressions/ExprTablistedPlayers.java
Labels: feature, feature-ready

#7985 EntityData Overhaul
  .github/CODEOWNERS
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/conditions/CondIsSpawnable.java
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/entity/AxolotlData.java
  src/main/java/ch/njol/skript/entity/BeeData.java
  src/main/java/ch/njol/skript/entity/BoatChestData.java
  src/main/java/ch/njol/skript/entity/BoatData.java
  src/main/java/ch/njol/skript/entity/CatData.java
  src/main/java/ch/njol/skript/entity/ChickenData.java
  src/main/java/ch/njol/skript/entity/CowData.java
  src/main/java/ch/njol/skript/entity/CreeperData.java
  src/main/java/ch/njol/skript/entity/DroppedItemData.java
  src/main/java/ch/njol/skript/entity/EndermanData.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/main/java/ch/njol/skript/entity/EntityType.java
  src/main/java/ch/njol/skript/entity/FallingBlockData.java
  src/main/java/ch/njol/skript/entity/FoxData.java
  src/main/java/ch/njol/skript/entity/FrogData.java
  src/main/java/ch/njol/skript/entity/GoatData.java
  src/main/java/ch/njol/skript/entity/LlamaData.java
  src/main/java/ch/njol/skript/entity/MinecartData.java
  src/main/java/ch/njol/skript/entity/MooshroomData.java
  src/main/java/ch/njol/skript/entity/OcelotData.java
  src/main/java/ch/njol/skript/entity/PandaData.java
  src/main/java/ch/njol/skript/entity/ParrotData.java
  src/main/java/ch/njol/skript/entity/PigData.java
  src/main/java/ch/njol/skript/entity/RabbitData.java
  src/main/java/ch/njol/skript/entity/SalmonData.java
  src/main/java/ch/njol/skript/entity/SheepData.java
  src/main/java/ch/njol/skript/entity/SimpleEntityData.java
  src/main/java/ch/njol/skript/entity/StriderData.java
  src/main/java/ch/njol/skript/entity/ThrownPotionData.java
  src/main/java/ch/njol/skript/entity/TropicalFishData.java
  src/main/java/ch/njol/skript/entity/VillagerData.java
  src/main/java/ch/njol/skript/entity/WolfData.java
  src/main/java/ch/njol/skript/entity/XpOrbData.java
  src/main/java/ch/njol/skript/entity/ZombieVillagerData.java
  src/main/java/ch/njol/skript/localization/Language.java
  src/main/java/ch/njol/skript/util/Patterns.java
  src/main/java/ch/njol/skript/util/SkriptColor.java
  src/main/java/ch/njol/yggdrasil/SimpleClassResolver.java
  src/main/java/org/skriptlang/skript/bukkit/displays/DisplayData.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/misc/EntityData.sk
Labels: bug, enhancement, breaking changes
