Repository SkriptLang/Skript, pull requests merged in 2025-08, with the labels that each got.

#8068 Limit literal specification regex pattern to improve matching behavior.
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/misc/literal specification.sk
Labels: bug, patch-ready

#8096 Fix function calling and improve error with single list params
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
  src/test/skript/tests/misc/function overloading.sk
Labels: bug, patch-ready

#8109 Fix loss of converter info with ExprLoopValue
  src/main/java/ch/njol/skript/expressions/ExprLoopValue.java
  src/test/skript/tests/regressions/8108-exprloopvalue losing converter info.sk
Labels: bug, patch-ready

#8077 Update EffVisualEffect syntax to also include entities on the number syntax
  src/main/java/ch/njol/skript/effects/EffVisualEffect.java
Labels: bug, enhancement, patch-ready

#8151 Remove extra colon from fire resistant documentation example
  src/main/java/ch/njol/skript/effects/EffFireResistant.java
Labels: documentation, patch-ready

#8041 Make the temporary getRegistryClassInfo public and outside the BukkitClasses
  src/main/java/ch/njol/skript/bukkitutil/BukkitUtils.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: enhancement, patch-ready

#8098 Implement type-aware function argument parsing
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
  src/main/java/ch/njol/skript/test/runner/EffTestExprList.java
  src/test/skript/tests/misc/expression list parsing.sk
  src/test/skript/tests/syntaxes/structures/StructFunction.sk
Labels: bug, enhancement, needs testing, patch-ready, needs reviews

#8121 Fix nullable direction combine
  src/main/java/ch/njol/skript/util/Direction.java
Labels: enhancement, patch-ready

#8132 Allowed Sub Types in EntryDataExpression
  src/main/java/org/skriptlang/skript/lang/entry/util/ExpressionEntryData.java
Labels: enhancement, patch-ready

#8158 Expose SectionContext
  src/main/java/ch/njol/skript/lang/Section.java
Labels: enhancement, patch-ready

#8154 Ensure ExpressionList#possibleReturnTypes is accurate after getConvertedExpression
  src/main/java/ch/njol/skript/lang/ExpressionList.java
Labels: bug, patch-ready
