Repository SkriptLang/Skript, pull requests merged in 2025-04, with the labels that each got.

#7747 Panda Support
  src/main/java/ch/njol/skript/conditions/CondIsEating.java
  src/main/java/ch/njol/skript/conditions/CondPandaIsOnBack.java
  src/main/java/ch/njol/skript/conditions/CondPandaIsRolling.java
  src/main/java/ch/njol/skript/conditions/CondPandaIsScared.java
  src/main/java/ch/njol/skript/conditions/CondPandaIsSneezing.java
  src/main/java/ch/njol/skript/effects/EffEating.java
  src/main/java/ch/njol/skript/effects/EffPandaOnBack.java
  src/main/java/ch/njol/skript/effects/EffPandaRolling.java
  src/main/java/ch/njol/skript/effects/EffPandaSneezing.java
  src/main/java/ch/njol/skript/expressions/ExprPandaGene.java
  src/test/skript/tests/syntaxes/effects/EffEating.sk
  src/test/skript/tests/syntaxes/effects/EffPandaOnBack.sk
  src/test/skript/tests/syntaxes/effects/EffPandaRolling.sk
  src/test/skript/tests/syntaxes/effects/EffPandaSneezing.sk
  src/test/skript/tests/syntaxes/expressions/ExprPandaGene.sk
Labels: feature

#7453 PlayerArmorChangeEvent Update
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/events/EvtPlayerArmorChange.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprArmorChangeItem.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/resources/lang/default.lang
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/events/EvtPlayerArmorChangeTest.java
  src/test/skript/junit/EvtPlayerArmorChangeTest.sk
Labels: enhancement, breaking changes, feature-ready

#7762 Bell Events Registering+Test Update
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/test/skript/junit/-BellEventsPaper.sk
  src/test/skript/junit/-BellEventsSpigot.sk
  src/test/skript/junit/BellEvents.sk
Labels: enhancement

#7270 Additional Dropped Item Elements
  src/main/java/ch/njol/skript/bukkitutil/UUIDUtils.java
  src/main/java/ch/njol/skript/conditions/CondItemDespawn.java
  src/main/java/ch/njol/skript/effects/EffItemDespawn.java
  src/main/java/ch/njol/skript/expressions/ExprEntityOwner.java
  src/main/java/ch/njol/skript/expressions/ExprEntityTamer.java
  src/main/java/ch/njol/skript/expressions/ExprItemOwner.java
  src/main/java/ch/njol/skript/expressions/ExprItemThrower.java
  src/test/skript/tests/syntaxes/effects/EffItemLifetime.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityOwner.sk
  src/test/skript/tests/syntaxes/expressions/ExprItemOwner.sk
  src/test/skript/tests/syntaxes/expressions/ExprItemThrower.sk
Labels: enhancement

#7431 Multilined Conditional + Order Debug Fix
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/sections/SecConditional.java
Labels: bug, feature-ready

#7683 Fishing event additions
  src/main/java/org/skriptlang/skript/bukkit/fishing/FishingModule.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/EvtFish.java
  src/main/resources/lang/default.lang
Labels: enhancement, feature-ready

#7744 Fix TropicalFishData spawning incorrect type
  src/main/java/ch/njol/skript/entity/TropicalFishData.java
Labels: bug, patch-ready

#7750 Create itemWithTooltip expression and test
  src/main/java/ch/njol/skript/expressions/ExprItemWithTooltip.java
  src/test/skript/tests/syntaxes/expressions/ExprItemWithTooltip.sk
Labels: enhancement, feature-ready

#7530 Sub Entry Validators/Containers
  src/main/java/ch/njol/skript/test/runner/StructTestEntryContainer.java
  src/main/java/ch/njol/skript/test/runner/StructTestSubValidators.java
  src/main/java/org/skriptlang/skript/lang/entry/ContainerEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/EntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/EntryValidator.java
  src/main/java/org/skriptlang/skript/lang/entry/KeyValueEntryData.java
  src/main/java/org/skriptlang/skript/lang/entry/util/VariableStringEntryData.java
  src/test/skript/junit/StructTestSubValidators.sk
Labels: feature, feature-ready

#7736 Copy item inventories when setting blocks.
  src/main/java/ch/njol/skript/aliases/ItemType.java
Labels: bug, patch-ready

#7773 Fix double-claiming behavior with Secspressions that have no section.
  src/main/java/ch/njol/skript/lang/Statement.java
Labels: bug, patch-ready

#7774 Fixes armor change NoClassDefFound error on Spigot
  src/main/java/ch/njol/skript/events/EvtPlayerArmorChange.java
Labels: bug, patch-ready

#7776 Adds missing lang entries for bundle inventory actions and bucket spawn reason
  src/main/resources/lang/default.lang
Labels: bug, patch-ready

#7754 Update name and example of ExprDisplayTeleportDuration to match syntax
  src/main/java/org/skriptlang/skript/bukkit/displays/generic/ExprDisplayTeleportDuration.java
Labels: documentation, patch-ready

#7769 Fix BlockLineIterator error due to floating point error near edges of blocks.
  src/main/java/ch/njol/skript/util/BlockLineIterator.java
  src/test/skript/tests/regressions/7768-block line iterator overshoot.sk
Labels: bug, patch-ready

#7483 Fix Player Input Event Example
  src/main/java/org/skriptlang/skript/bukkit/input/elements/events/EvtPlayerInput.java
Labels: bug, patch-ready

#7697 Make ERS use names of events instead of class names
  src/main/java/ch/njol/skript/lang/EventRestrictedSyntax.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/misc/supported events.sk
Labels: bug, patch-ready

#7656 Fix non-empty event values in JSONGenerator
  src/main/java/ch/njol/skript/doc/JSONGenerator.java
Labels: bug, patch-ready

#7790 Use NamespacedKeys instead of Material ordinals for ItemData serialization
  src/main/java/ch/njol/skript/aliases/ItemData.java
Labels: bug, feature-ready

#7793 Fix SectionExpression errors not appearing in the final log.
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/test/skript/tests/misc/expression sections.sk
Labels: bug, patch-ready

#7787 Expose EntryValidator within ContainerEntryData 😊
  src/main/java/org/skriptlang/skript/lang/entry/ContainerEntryData.java
Labels: enhancement, patch-ready

#7786 Add since tag onto ExprWithItemFlags for "all itemflags"
  src/main/java/ch/njol/skript/expressions/ExprWithItemFlags.java
Labels: bug, patch-ready

#7495 Skip `-` prefix variable names when saving. (Ephemeral variables)
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: feature, feature-ready

#7658 [WIP] Add on screen kick message expr
  src/main/java/ch/njol/skript/expressions/ExprOnScreenKickMessage.java
Labels: enhancement, feature-ready

#7710 ExprTool - Cleanup & Additional Test
  src/main/java/ch/njol/skript/bukkitutil/BukkitUtils.java
  src/main/java/ch/njol/skript/expressions/ExprTool.java
  src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
  src/test/skript/tests/syntaxes/expressions/ExprTool.sk
Labels: enhancement, feature-ready

#7738 ExprExactItem
  src/main/java/ch/njol/skript/expressions/ExprExactItem.java
  src/test/skript/tests/syntaxes/expressions/ExprExactItem.sk
Labels: enhancement, feature-ready

#7796 Paper 1.21.5 Update
  build.gradle
  gradle.properties
  src/main/java/ch/njol/skript/bukkitutil/EntityUtils.java
  src/main/java/ch/njol/skript/effects/EffInvisible.java
  src/main/java/ch/njol/skript/entity/EntityData.java
  src/test/skript/environments/java21/paper-1.21.5.json
Labels: bug, enhancement, patch-ready

#7814 ExprAnyOf's acceptChange returning an empty array instead of null.
  src/main/java/ch/njol/skript/expressions/ExprAnyOf.java
Labels: bug, priority: medium, patch-ready

#7821 Add event-inventory to InventoryEvent
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
Labels: enhancement, patch-ready

#7834 Add missing suffocation method for Block implementations.
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
Labels: bug, patch-ready
