Repository SkriptLang/Skript, pull requests merged in 2025-07, with the labels that each got.

#7906 ExprArmorSlot With EquipmentSlots
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/expressions/ExprArmorSlot.sk
Labels: enhancement, needs reviews

#7956 Add infinite timespans
  src/main/java/ch/njol/skript/classes/data/DefaultOperations.java
  src/main/java/ch/njol/skript/conditions/CondIsInfinite.java
  src/main/java/ch/njol/skript/effects/EffPotion.java
  src/main/java/ch/njol/skript/expressions/ExprPotionEffect.java
  src/main/java/ch/njol/skript/expressions/LitEternity.java
  src/main/java/ch/njol/skript/util/Timespan.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/regressions/7645-floating point timespan math.sk
  src/test/skript/tests/syntaxes/expressions/LitEternity.sk
Labels: enhancement, feature, breaking changes, feature-ready

#7892 Local Variable Type Hints
  src/main/java/ch/njol/skript/ScriptLoader.java
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/command/Argument.java
  src/main/java/ch/njol/skript/command/ScriptCommand.java
  src/main/java/ch/njol/skript/effects/EffChange.java
  src/main/java/ch/njol/skript/effects/EffCopy.java
  src/main/java/ch/njol/skript/effects/EffDoIf.java
  src/main/java/ch/njol/skript/effects/EffReturn.java
  src/main/java/ch/njol/skript/effects/EffSuppressTypeHints.java
  src/main/java/ch/njol/skript/effects/EffTransform.java
  src/main/java/ch/njol/skript/expressions/ExprNode.java
  src/main/java/ch/njol/skript/expressions/base/SectionExpression.java
  src/main/java/ch/njol/skript/lang/ExpressionSection.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/lang/Variable.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/ScriptFunction.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/lang/util/SectionUtils.java
  src/main/java/ch/njol/skript/registrations/Classes.java
  src/main/java/ch/njol/skript/registrations/Feature.java
  src/main/java/ch/njol/skript/sections/EffSecShoot.java
  src/main/java/ch/njol/skript/sections/EffSecSpawn.java
  src/main/java/ch/njol/skript/sections/ExprSecCreateWorldBorder.java
  src/main/java/ch/njol/skript/sections/SecFor.java
  src/main/java/ch/njol/skript/sections/SecLoop.java
  src/main/java/ch/njol/skript/variables/HintManager.java
  src/main/java/ch/njol/skript/variables/TypeHints.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/expressions/ExprSecCreateLootContext.java
  src/test/skript/tests/misc/type hints.sk
  src/test/skript/tests/syntaxes/effects/EffCopy.sk
  src/test/skript/tests/syntaxes/effects/EffDoIf.sk
  src/test/skript/tests/syntaxes/effects/EffTransform.sk
  src/test/skript/tests/syntaxes/sections/SecFor.sk
  src/test/skript/tests/syntaxes/structures/StructCommand.sk
  src/test/skript/tests/syntaxes/structures/StructFunction.sk
Labels: bug, feature, needs testing, feature-ready

#7965 Split ExprSpecialNumber into separate literals, make 'value' optional
  src/main/java/ch/njol/skript/expressions/ExprSpecialNumber.java
  src/main/java/ch/njol/skript/expressions/LitInfinity.java
  src/main/java/ch/njol/skript/expressions/LitNaN.java
  src/main/java/ch/njol/skript/expressions/LitNegativeInfinity.java
Labels: enhancement, feature-ready

#7840 ExprTestPlayer + Comparator Update
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/test/runner/ExprTestOfflinePlayer.java
  src/main/java/ch/njol/skript/test/utils/TestOfflinePlayer.java
  src/test/skript/tests/syntaxes/expressions/ExprEntityOwner.sk
  src/test/skript/tests/syntaxes/expressions/ExprSkullOwner.sk
  src/test/skript/tests/syntaxes/expressions/ExprUUID.sk
  src/test/skript/tests/syntaxes/expressions/ExprWhitelist.sk
Labels: feature, feature-ready

#7949 EffSendBlockChange as Original
  src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
Labels: enhancement, feature-ready

#7904 ExprSkull - Breaking Change
  src/main/java/ch/njol/skript/expressions/ExprSkull.java
Labels: enhancement, breaking changes, feature-ready

#7706 SkriptEvent - Since array support
  src/main/java/ch/njol/skript/doc/Documentation.java
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
  src/main/java/ch/njol/skript/doc/JSONGenerator.java
  src/main/java/ch/njol/skript/lang/SkriptEventInfo.java
  src/main/java/ch/njol/skript/lang/SyntaxElementInfo.java
  src/main/java/org/skriptlang/skript/bukkit/registration/BukkitSyntaxInfos.java
  src/main/java/org/skriptlang/skript/bukkit/registration/BukkitSyntaxInfosImpl.java
  src/test/java/org/skriptlang/skript/bukkit/registration/EventSyntaxInfoTest.java
Labels: enhancement, breaking changes, feature-ready

#7757 Function overloading
  .github/CODEOWNERS
  src/main/java/ch/njol/skript/Skript.java
  src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
  src/main/java/ch/njol/skript/lang/function/JavaFunction.java
  src/main/java/ch/njol/skript/lang/function/Signature.java
  src/main/java/ch/njol/skript/lang/function/SimpleJavaFunction.java
  src/test/java/ch/njol/skript/lang/function/FunctionRegistryTest.java
  src/test/skript/tests/misc/function overloading.sk
Labels: feature, functions, 2.12

#7879 Fix Syntax Removal
  src/main/java/ch/njol/skript/effects/EffWorldLoad.java
  src/main/java/ch/njol/skript/expressions/ExprLocationVectorOffset.java
  src/main/java/ch/njol/skript/expressions/ExprSortedList.java
  src/main/java/ch/njol/skript/test/runner/EffRunRunnable.java
  src/main/java/org/skriptlang/skript/registration/DefaultSyntaxInfosImpl.java
  src/main/java/org/skriptlang/skript/registration/SyntaxRegister.java
  src/test/java/org/skriptlang/skript/registration/SyntaxRegistryTest.java
  src/test/skript/tests/misc/expression sections.sk
  src/test/skript/tests/syntaxes/effects/EffScriptFile.sk
Labels: bug, breaking changes, patch-ready

#7990 Prepare For Release (2.12.0-pre1)
  gradle.properties
  src/main/java/ch/njol/skript/aliases/ItemType.java
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/conditions/CondHasCustomModelData.java
  src/main/java/ch/njol/skript/conditions/CondHasItemCooldown.java
  src/main/java/ch/njol/skript/conditions/CondIsDivisibleBy.java
  src/main/java/ch/njol/skript/conditions/CondIsEnchanted.java
  src/main/java/ch/njol/skript/conditions/CondStriderIsShivering.java
  src/main/java/ch/njol/skript/config/EnumParser.java
  src/main/java/ch/njol/skript/effects/EffCancelDrops.java
  src/main/java/ch/njol/skript/effects/EffPush.java
  src/main/java/ch/njol/skript/effects/EffSendBlockChange.java
  src/main/java/ch/njol/skript/effects/EffStriderShivering.java
  src/main/java/ch/njol/skript/effects/EffSuppressTypeHints.java
  src/main/java/ch/njol/skript/effects/EffToggle.java
  src/main/java/ch/njol/skript/events/EvtHarvestBlock.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/main/java/ch/njol/skript/expressions/ExprAttachedBlock.java
  src/main/java/ch/njol/skript/expressions/ExprBrushableItem.java
  src/main/java/ch/njol/skript/expressions/ExprCaughtErrors.java
  src/main/java/ch/njol/skript/expressions/ExprCustomModelData.java
  src/main/java/ch/njol/skript/expressions/ExprDustedStage.java
  src/main/java/ch/njol/skript/expressions/ExprExactItem.java
  src/main/java/ch/njol/skript/expressions/ExprExcept.java
  src/main/java/ch/njol/skript/expressions/ExprFirstEmptySlot.java
  src/main/java/ch/njol/skript/expressions/ExprHash.java
  src/main/java/ch/njol/skript/expressions/ExprIndicesOf.java
  src/main/java/ch/njol/skript/expressions/ExprInverse.java
  src/main/java/ch/njol/skript/expressions/ExprItemCooldown.java
  src/main/java/ch/njol/skript/expressions/ExprItemWithCustomModelData.java
  src/main/java/ch/njol/skript/expressions/ExprKeyed.java
  src/main/java/ch/njol/skript/expressions/ExprOnScreenKickMessage.java
  src/main/java/ch/njol/skript/expressions/ExprSpawnerType.java
  src/main/java/ch/njol/skript/expressions/LitEternity.java
  src/main/java/ch/njol/skript/expressions/base/SectionExpression.java
  src/main/java/ch/njol/skript/lang/Section.java
  src/main/java/ch/njol/skript/sections/SecCatchErrors.java
  src/main/java/ch/njol/skript/util/EnumUtils.java
  src/main/java/ch/njol/skript/variables/TypeHints.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/DamageSourceModule.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/CondScalesWithDifficulty.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/CondWasIndirect.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprCausingEntity.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprCreatedDamageSource.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprDamageLocation.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprDamageType.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprDirectEntity.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprFoodExhaustion.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprSecDamageSource.java
  src/main/java/org/skriptlang/skript/bukkit/damagesource/elements/ExprSourceLocation.java
Labels: feature, feature-ready

#8005 Prevent FFS from saving ephemeral vars on shutdown
  src/main/java/ch/njol/skript/variables/FlatFileStorage.java
  src/main/java/ch/njol/skript/variables/Variables.java
Labels: bug, variables, feature-ready

#8001 Implement default simplify() on Expression
  src/main/java/ch/njol/skript/lang/Expression.java
Labels: enhancement, feature-ready

#7992 Fix Docs Example Formatting
  src/main/java/ch/njol/skript/doc/HTMLGenerator.java
Labels: bug, feature-ready

#8006 move ExprValueWithin to PROPERTY priority
  src/main/java/ch/njol/skript/expressions/ExprValueWithin.java
Labels: bug, feature-ready

#7993 Add SyntaxInfo builder methods
  src/main/java/ch/njol/skript/conditions/base/PropertyCondition.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java
Labels: enhancement, feature-ready

#8015 Fix bad FunctionRegistry#remove logic
  src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
  src/test/java/ch/njol/skript/lang/function/FunctionRegistryTest.java
Labels: bug, feature-ready, 2.12

#8027 Fix overzealous literal type spec. parsing
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/regressions/7861-overzealous literal type specification.sk
Labels: bug, feature-ready

#8032 Function overloading fixes and improvements
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/function/DynamicFunctionReference.java
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
  src/test/java/ch/njol/skript/lang/function/FunctionRegistryTest.java
  src/test/skript/tests/misc/function overloading.sk
  src/test/skript/tests/syntaxes/structures/StructFunction.sk
Labels: bug, enhancement, feature-ready, 2.12

#8037 Prep for 2.12 release
  gradle.properties
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/test/skript/tests/syntaxes/structures/StructFunction.sk
Labels: needs reviews

#8009 Add term launch to projectile launch event
  src/main/java/ch/njol/skript/events/SimpleEvents.java
Labels: enhancement, patch-ready

#8046 Fix function overloading for convertable arguments
  src/main/java/ch/njol/skript/lang/function/FunctionReference.java
  src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
  src/main/java/ch/njol/skript/lang/function/Functions.java
  src/test/java/ch/njol/skript/lang/function/FunctionRegistryTest.java
  src/test/skript/tests/misc/function overloading.sk
Labels: bug, 2.12

#8054 Paper 1.21.8 Update
  build.gradle
  gradle.properties
  src/main/java/ch/njol/skript/util/BlockStateBlock.java
  src/main/java/ch/njol/skript/util/DelayedChangeBlock.java
  src/test/skript/environments/java21/paper-1.21.8.json
Labels: enhancement, unit testing, patch-ready

#8071 Fix potential resolution failure with single list parameter function calls
  src/main/java/ch/njol/skript/lang/function/FunctionRegistry.java
  src/test/skript/tests/regressions/8070-single list parameter functions can fail to resolve.sk
Labels: bug, patch-ready

#8082 Fix expression section claim releasing
  src/main/java/ch/njol/skript/lang/Statement.java
Labels: bug, patch-ready

#8086 Happy Ghast Equipment
  src/main/java/ch/njol/skript/effects/EffEquip.java
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/test/skript/tests/regressions/8086-happy ghast equipment.sk
Labels: bug, patch-ready

#8087 catch rounding edge cases
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/test/skript/tests/regressions/8085-rounding nan.sk
Labels: bug, patch-ready

#8076 Improve default syntax ordering
  src/main/java/org/skriptlang/skript/registration/SyntaxRegister.java
Labels: enhancement, patch-ready
