Repository SkriptLang/Skript, pull requests merged in 2025-03, with the labels that each got.

#7513 Fix of the BlockLineIterator causing IllegalStateException
  src/main/java/ch/njol/skript/expressions/ExprBlocks.java
  src/main/java/ch/njol/skript/util/BlockLineIterator.java
  src/main/java/ch/njol/util/coll/iterator/StoppableIterator.java
  src/test/java/ch/njol/skript/util/BlockLineIteratorTest.java
  src/test/skript/tests/regressions/5566-block iterator being 100 always.sk
  src/test/skript/tests/regressions/7496-block iterator missing end block.sk
Labels: bug

#7611 Update release model to 4 feature releases a year.
  CLOCKWORK_RELEASE_MODEL.md
Labels: patch-ready, housekeeping

#7276 String Colors
  src/main/java/ch/njol/skript/expressions/ExprLastColor.java
  src/main/java/ch/njol/skript/expressions/ExprStringColor.java
  src/main/java/ch/njol/skript/util/SkriptColor.java
  src/test/skript/tests/syntaxes/expressions/ExprStringColors.sk
Labels: enhancement, feature-ready, 2.11

#7316 EntityBlockStorage + Beehive
  src/main/java/ch/njol/skript/conditions/CondEntityStorageIsFull.java
  src/main/java/ch/njol/skript/conditions/CondIsSedated.java
  src/main/java/ch/njol/skript/effects/EffClearEntityStorage.java
  src/main/java/ch/njol/skript/effects/EffInsertEntityStorage.java
  src/main/java/ch/njol/skript/effects/EffReleaseEntityStorage.java
  src/main/java/ch/njol/skript/expressions/ExprBeehiveFlower.java
  src/main/java/ch/njol/skript/expressions/ExprBeehiveHoneyLevel.java
  src/main/java/ch/njol/skript/expressions/ExprEntityStorageEntityCount.java
  src/test/skript/tests/syntaxes/expressions/ExprBeehiveFlower.sk
  src/test/skript/tests/syntaxes/expressions/ExprBeehiveHoneyLevel.sk
  src/test/skript/tests/syntaxes/expressions/ExprEntityStorageEntityCount.sk
Labels: feature, feature-ready

#7317 Add Location examples
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: documentation, feature-ready

#7332 EvtRealTime
  src/main/java/ch/njol/skript/events/EvtRealTime.java
  src/main/java/ch/njol/skript/util/Time.java
  src/test/java/org/skriptlang/skript/test/tests/utils/TimeTest.java
Labels: feature, feature-ready

#7351 (Zombie)VillagerData Update + EffZombify
  src/main/java/ch/njol/skript/effects/EffZombify.java
  src/main/java/ch/njol/skript/entity/VillagerData.java
  src/main/java/ch/njol/skript/entity/ZombieVillagerData.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/effects/EffZombify.sk
  src/test/skript/tests/syntaxes/sections/EffSecSpawn.sk
Labels: enhancement, feature, feature-ready

#7361 Axolotl Playing Dead
  src/main/java/ch/njol/skript/conditions/CondIsPlayingDead.java
  src/main/java/ch/njol/skript/effects/EffPlayingDead.java
  src/test/skript/tests/syntaxes/effects/EffPlayingDead.sk
Labels: enhancement, feature-ready, 2.11

#7512 EventValues - add an option to use changers
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/base/EventValueExpression.java
  src/main/java/ch/njol/skript/registrations/EventConverter.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/EventValueExpressionTest.java
  src/test/skript/junit/EventValueExpression.sk
Labels: enhancement, feature-ready

#7643 Adds GitHub Codeowners
  .github/CODEOWNERS
Labels: feature, github related

#7599 Event Values Fix
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/doc/JSONGenerator.java
  src/main/java/ch/njol/skript/expressions/ExprEntity.java
  src/main/java/ch/njol/skript/registrations/EventValues.java
  src/test/skript/tests/misc/EventValues.sk
  src/test/skript/tests/syntaxes/effects/EffDetonate.sk
Labels: bug, feature, patch-ready

#7665 Adds an isSingle check to EffSort's mapping expression
  src/main/java/ch/njol/skript/effects/EffSort.java
Labels: bug, patch-ready

#7688 ItemData - dont set damage if the item isnt damaged
  src/main/java/ch/njol/skript/aliases/ItemData.java
  src/test/skript/tests/regressions/7688-itemdata-copy.sk
Labels: bug, patch-ready

#7717 Fix array store exception in ExprAngle
  src/main/java/ch/njol/skript/expressions/ExprAngle.java
  src/test/skript/tests/regressions/7717-expr angle array store.sk
Labels: bug, patch-ready

#7365 Make Player Sprint + Camel Is Dashing
  src/main/java/ch/njol/skript/conditions/CondIsDashing.java
  src/main/java/ch/njol/skript/conditions/CondIsSprinting.java
  src/main/java/ch/njol/skript/effects/EffSprinting.java
Labels: enhancement, feature-ready

#7386 EffVehicle + CondIsRiding Update
  src/main/java/ch/njol/skript/conditions/CondIsRiding.java
  src/main/java/ch/njol/skript/effects/EffVehicle.java
  src/test/skript/tests/syntaxes/effects/EffVehicle.sk
Labels: enhancement, feature-ready

#7415 Update ViewDistance, Add SimulationDistance
  src/main/java/ch/njol/skript/expressions/ExprPlayerViewDistance.java
  src/main/java/ch/njol/skript/expressions/ExprSimulationDistance.java
  src/main/java/ch/njol/skript/expressions/ExprViewDistance.java
  src/test/skript/tests/syntaxes/expressions/ExprViewDistance.sk
Labels: enhancement, feature-ready, 2.11

#7440 BukkitClasses - make "effect" in PotionEffectType pattern non-optional
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: bug, breaking changes, feature-ready

#7622 Additional StructUsing Patterns
  src/main/java/ch/njol/skript/structures/StructUsing.java
Labels: enhancement, feature-ready

#7478 EquipSlot Deprecation
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/expressions/ExprArmorSlot.java
  src/main/java/ch/njol/skript/expressions/ExprTool.java
  src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
Labels: feature-ready, housekeeping

#7727 Enforce NotNull on EquipmentSlot constructors.
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
Labels: bug

#7492 Aliases - add support for aliases by MC keys
  src/main/java/ch/njol/skript/aliases/Aliases.java
  src/test/skript/tests/regressions/7492-aliases-from-key.sk
Labels: enhancement, feature-ready

#7549 Skript Tag Pattern
  src/main/java/org/skriptlang/skript/bukkit/tags/sources/TagOrigin.java
Labels: enhancement, feature-ready

#7550 More Math Functions
  src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java
  src/test/skript/tests/syntaxes/functions/combinations.sk
  src/test/skript/tests/syntaxes/functions/factorial.sk
  src/test/skript/tests/syntaxes/functions/mean.sk
  src/test/skript/tests/syntaxes/functions/median.sk
  src/test/skript/tests/syntaxes/functions/permutations.sk
  src/test/skript/tests/syntaxes/functions/root.sk
Labels: feature, feature-ready

#7552 Update ExprRound Allowing Multiple Numbers + Patterns
  src/main/java/ch/njol/skript/expressions/ExprRound.java
  src/test/skript/tests/syntaxes/expressions/ExprRound.sk
Labels: enhancement, feature-ready

#7597 Ghast Support
  src/main/java/ch/njol/skript/conditions/CondIsChargingFireball.java
  src/main/java/ch/njol/skript/expressions/ExprExplosiveYield.java
  src/test/skript/tests/syntaxes/expressions/ExprExplosiveYield.sk
Labels: enhancement, feature-ready

#7547 Is Within Multiple Objects
  src/main/java/ch/njol/skript/conditions/CondIsWithin.java
  src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
Labels: enhancement, feature-ready

#7554 Update ExprNoDamageTicks Allowing Timespans
  src/main/java/ch/njol/skript/expressions/ExprNoDamageTicks.java
  src/main/java/ch/njol/skript/expressions/ExprNoDamageTime.java
  src/test/skript/tests/syntaxes/expressions/ExprNoDamageTicks.sk
Labels: enhancement, feature-ready

#7564 Entity/Block Persistence + Entity Despawnable
  src/main/java/ch/njol/skript/conditions/CondEntityUnload.java
  src/main/java/ch/njol/skript/conditions/CondIsPersistent.java
  src/main/java/ch/njol/skript/effects/EffEntityUnload.java
  src/main/java/ch/njol/skript/effects/EffPersistent.java
  src/test/skript/tests/syntaxes/effects/EffPersistent.sk
Labels: enhancement, feature-ready

#7006 Add worldborders
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
  src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java
  src/main/java/ch/njol/skript/conditions/CondIsWithin.java
  src/main/java/ch/njol/skript/effects/EffWorldBorderExpand.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/main/java/ch/njol/skript/expressions/ExprSecCreateWorldBorder.java
  src/main/java/ch/njol/skript/expressions/ExprWorldBorder.java
  src/main/java/ch/njol/skript/expressions/ExprWorldBorderCenter.java
  src/main/java/ch/njol/skript/expressions/ExprWorldBorderDamageAmount.java
  src/main/java/ch/njol/skript/expressions/ExprWorldBorderDamageBuffer.java
  src/main/java/ch/njol/skript/expressions/ExprWorldBorderSize.java
  src/main/java/ch/njol/skript/expressions/ExprWorldBorderWarningDistance.java
  src/main/java/ch/njol/skript/expressions/ExprWorldBorderWarningTime.java
  src/main/resources/lang/default.lang
  src/test/skript/tests/syntaxes/conditions/CondIsWithin.sk
  src/test/skript/tests/syntaxes/effects/EffWorldBorderExpand.sk
  src/test/skript/tests/syntaxes/expressions/ExprWorldBorderCenter.sk
  src/test/skript/tests/syntaxes/expressions/ExprWorldBorderDamageAmount.sk
  src/test/skript/tests/syntaxes/expressions/ExprWorldBorderDamageBuffer.sk
  src/test/skript/tests/syntaxes/expressions/ExprWorldBorderSize.sk
  src/test/skript/tests/syntaxes/expressions/ExprWorldBorderWarningDistance.sk
  src/test/skript/tests/syntaxes/expressions/ExprWorldBorderWarningTime.sk
  src/test/skript/tests/syntaxes/sections/ExprSecCreateWorldBorder.sk
Labels: feature, feature-ready

#7730 Remove s01 sonatype maven repository
  build.gradle
Labels: bug

#7287 Improve default comparator resolution
  src/main/java/org/skriptlang/skript/lang/comparator/Comparators.java
Labels: bug, feature-ready, 2.11

#7442 ExprWeather + ExprPlayerWeather Merge
  src/main/java/ch/njol/skript/expressions/ExprPlayerWeather.java
  src/main/java/ch/njol/skript/expressions/ExprWeather.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/expressions/ExprWeatherTest.java
  src/test/skript/junit/ExprWeatherTest.sk
Labels: enhancement, feature-ready

#7566 Update extended Property Conditions
  src/main/java/ch/njol/skript/conditions/CondAI.java
  src/main/java/ch/njol/skript/conditions/CondCanFly.java
  src/main/java/ch/njol/skript/conditions/CondChatColors.java
  src/main/java/ch/njol/skript/conditions/CondChatFiltering.java
  src/main/java/ch/njol/skript/conditions/CondEntityIsInLiquid.java
  src/main/java/ch/njol/skript/conditions/CondEntityIsWet.java
  src/main/java/ch/njol/skript/conditions/CondGlowingText.java
  src/main/java/ch/njol/skript/conditions/CondHasClientWeather.java
  src/main/java/ch/njol/skript/conditions/CondHasCustomModelData.java
  src/main/java/ch/njol/skript/conditions/CondIgnitionProcess.java
  src/main/java/ch/njol/skript/conditions/CondIsAlive.java
  src/main/java/ch/njol/skript/conditions/CondIsBanned.java
  src/main/java/ch/njol/skript/conditions/CondIsBlock.java
  src/main/java/ch/njol/skript/conditions/CondIsBlocking.java
  src/main/java/ch/njol/skript/conditions/CondIsBurning.java
  src/main/java/ch/njol/skript/conditions/CondIsCharged.java
  src/main/java/ch/njol/skript/conditions/CondIsCommandBlockConditional.java
  src/main/java/ch/njol/skript/conditions/CondIsEdible.java
  src/main/java/ch/njol/skript/conditions/CondIsEmpty.java
  src/main/java/ch/njol/skript/conditions/CondIsFlammable.java
  src/main/java/ch/njol/skript/conditions/CondIsFlying.java
  src/main/java/ch/njol/skript/conditions/CondIsFuel.java
  src/main/java/ch/njol/skript/conditions/CondIsInfinite.java
  src/main/java/ch/njol/skript/conditions/CondIsInteractable.java
  src/main/java/ch/njol/skript/conditions/CondIsInvisible.java
  src/main/java/ch/njol/skript/conditions/CondIsInvulnerable.java
  src/main/java/ch/njol/skript/conditions/CondIsLeftHanded.java
  src/main/java/ch/njol/skript/conditions/CondIsOnline.java
  src/main/java/ch/njol/skript/conditions/CondIsOp.java
  src/main/java/ch/njol/skript/conditions/CondIsPassable.java
  src/main/java/ch/njol/skript/conditions/CondIsPoisoned.java
  src/main/java/ch/njol/skript/conditions/CondIsRiptiding.java
  src/main/java/ch/njol/skript/conditions/CondIsSheared.java
  src/main/java/ch/njol/skript/conditions/CondIsSilent.java
  src/main/java/ch/njol/skript/conditions/CondIsSkriptCommand.java
  src/main/java/ch/njol/skript/conditions/CondIsSleeping.java
  src/main/java/ch/njol/skript/conditions/CondIsSlimeChunk.java
  src/main/java/ch/njol/skript/conditions/CondIsSneaking.java
  src/main/java/ch/njol/skript/conditions/CondIsSolid.java
  src/main/java/ch/njol/skript/conditions/CondIsSwimming.java
  src/main/java/ch/njol/skript/conditions/CondIsTameable.java
  src/main/java/ch/njol/skript/conditions/CondIsTamed.java
  src/main/java/ch/njol/skript/conditions/CondIsTransparent.java
  src/main/java/ch/njol/skript/conditions/CondIsVectorNormalized.java
  src/main/java/ch/njol/skript/conditions/CondItemEnchantmentGlint.java
  src/main/java/ch/njol/skript/test/runner/CondMethodExists.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondCanAge.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondCanBreed.java
  src/main/java/org/skriptlang/skript/bukkit/breeding/elements/CondIsBaby.java
  src/main/java/org/skriptlang/skript/bukkit/fishing/elements/CondIsInOpenWater.java
  src/main/java/org/skriptlang/skript/bukkit/loottables/elements/conditions/CondHasLootTable.java
Labels: bug, feature-ready, housekeeping

#7586 Add spanish.lang
  src/main/resources/config.sk
  src/main/resources/lang/spanish.lang
Labels: feature-ready, translation

#7701 Add ExprAnyOf and fix bug with setting or lists
  src/main/java/ch/njol/skript/expressions/ExprAnyOf.java
  src/main/java/ch/njol/skript/lang/ExpressionList.java
  src/test/skript/tests/regressions/7701-changing or list changes all.sk
  src/test/skript/tests/syntaxes/expressions/ExprAnyOf.sk
Labels: bug, feature, feature-ready

#7704 Add "with all itemflags" to ExprWithItemFlags
  src/main/java/ch/njol/skript/expressions/ExprWithItemFlags.java
  src/test/skript/tests/syntaxes/expressions/ExprItemFlags.sk
Labels: enhancement, feature-ready

#7694 Add itemstack to itemstack's classinfo
  src/main/java/ch/njol/skript/classes/data/BukkitClasses.java
Labels: enhancement, feature-ready

#7479 Goat Support
  src/main/java/ch/njol/skript/conditions/CondGoatHasHorns.java
  src/main/java/ch/njol/skript/conditions/CondIsScreaming.java
  src/main/java/ch/njol/skript/effects/EffGoatHorns.java
  src/main/java/ch/njol/skript/effects/EffGoatRam.java
  src/main/java/ch/njol/skript/effects/EffScreaming.java
  src/test/java/org/skriptlang/skript/test/tests/syntaxes/effects/EffGoatHornsTest.java
  src/test/skript/junit/EffGoatHornsTest.sk
  src/test/skript/tests/syntaxes/effects/EffScreaming.sk
Labels: enhancement, feature-ready

#7716 Fix non-single functions being parsed for single-only expression infos
  src/main/java/ch/njol/skript/lang/SkriptParser.java
Labels: bug, patch-ready

#7722 Literal Class Info Parsing
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/localization/Noun.java
  src/test/skript/tests/misc/literal specification.sk
Labels: feature, feature-ready

#7679 Event Annotation/Doc Fix
  src/main/java/ch/njol/skript/events/EvtBeaconEffect.java
  src/main/java/ch/njol/skript/events/EvtBeaconToggle.java
Labels: bug, documentation, patch-ready

#7669 Include player as entity in on entity move
  src/main/java/ch/njol/skript/events/EvtMove.java
Labels: bug, patch-ready

#7699 .vscode gitignore
  .gitignore
Labels: enhancement, patch-ready

#7714 Add EntityShootBowEvent
  src/main/java/ch/njol/skript/events/EvtEntityShootBow.java
  src/main/java/ch/njol/skript/expressions/ExprConsumedItem.java
  src/main/java/ch/njol/skript/expressions/ExprProjectileForce.java
  src/main/java/ch/njol/skript/expressions/ExprShooter.java
Labels: feature, feature-ready

#7713 Update SlotWithIndex and InventorySlot Comparisons
  src/main/java/ch/njol/skript/classes/data/DefaultComparators.java
  src/main/java/ch/njol/skript/util/slot/CursorSlot.java
  src/main/java/ch/njol/skript/util/slot/DisplayEntitySlot.java
  src/main/java/ch/njol/skript/util/slot/DroppedItemSlot.java
  src/main/java/ch/njol/skript/util/slot/EquipmentSlot.java
  src/main/java/ch/njol/skript/util/slot/InventorySlot.java
  src/main/java/ch/njol/skript/util/slot/ItemFrameSlot.java
  src/main/java/ch/njol/skript/util/slot/Slot.java
  src/main/java/ch/njol/skript/util/slot/SlotWithIndex.java
  src/main/java/ch/njol/skript/util/slot/ThrowableProjectileSlot.java
Labels: bug, feature-ready

#7696 Fix bookshelf and decorated pot comparisons
  src/main/resources/lang/default.lang
  src/test/skript/tests/regressions/7620-can't-compare-bookshelf-with-block.sk
Labels: bug, breaking changes, feature-ready

#7548 AddonModule#canLoad
  src/main/java/org/skriptlang/skript/addon/AddonModule.java
  src/main/java/org/skriptlang/skript/addon/SkriptAddon.java
Labels: enhancement, feature-ready

#7480 Enderman Support
  src/main/java/ch/njol/skript/conditions/CondEndermanStaredAt.java
  src/main/java/ch/njol/skript/effects/EffEndermanTeleport.java
  src/main/java/ch/njol/skript/expressions/ExprCarryingBlockData.java
  src/test/skript/tests/syntaxes/expressions/ExprCarryingBlockData.sk
Labels: enhancement, feature-ready

#7358 Allay Support
  src/main/java/ch/njol/skript/conditions/CondAllayCanDuplicate.java
  src/main/java/ch/njol/skript/conditions/CondIsDancing.java
  src/main/java/ch/njol/skript/effects/EffAllayCanDuplicate.java
  src/main/java/ch/njol/skript/effects/EffAllayDuplicate.java
  src/main/java/ch/njol/skript/effects/EffDancing.java
  src/main/java/ch/njol/skript/expressions/ExprAllayJukebox.java
  src/main/java/ch/njol/skript/expressions/ExprDuplicateCooldown.java
  src/test/skript/tests/syntaxes/effects/EffDancing.sk
  src/test/skript/tests/syntaxes/expressions/ExprDuplicateCooldown.sk
Labels: feature, feature-ready

#7362 Bat Support
  src/main/java/ch/njol/skript/conditions/CondIsSleeping.java
  src/main/java/ch/njol/skript/effects/EffWakeupSleep.java
  src/main/java/ch/njol/skript/events/SimpleEvents.java
  src/test/skript/tests/syntaxes/effects/EffWakeupSleep.sk
Labels: feature, feature-ready

#7575 ExperimentalSyntax
  src/main/java/ch/njol/skript/expressions/ExprDequeuedQueue.java
  src/main/java/ch/njol/skript/expressions/ExprQueue.java
  src/main/java/ch/njol/skript/expressions/ExprQueueStartEnd.java
  src/main/java/ch/njol/skript/lang/SkriptParser.java
  src/main/java/ch/njol/skript/lang/parser/ParserInstance.java
  src/main/java/ch/njol/skript/sections/SecFor.java
  src/main/java/ch/njol/skript/structures/StructExample.java
  src/main/java/org/skriptlang/skript/lang/experiment/ExperimentalSyntax.java
Labels: enhancement, feature-ready
